### ISSUE TITLE
Error: Cannot find module 'inline-style-prefixer/static'

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#107]
**Version**: 3.0.7
**Environment**: DOM / Server / Both
**Type**: Bug

-------------------
![screen shot 2016-11-19 at 18 22 48](https://cloud.githubusercontent.com/assets/66249/20457157/3b3023f0-ae85-11e6-9861-316dbb852bb6.png)

**Comment by steida** [comment]
OK, it seems modules have to be installed manually. PeerDependencies ftw.

**Comment by steida** [comment]
And unitless-css-property as well.

**Comment by rofrischmann** [comment]
Seems like the single packages which require these additional packages do not add them so that the main package (which physically includes all other packages) is able to use them...

**Comment by rofrischmann** [comment]
I have tested this on my own and I do not get any errors. May I know what npm version you're using? @steida @cvle
I guess these issues can be solved by upgrading to the latest npm version.

**Comment by steida** [comment]
I switched to glamor/styled-components so I can't test it anymore, but I am always using the last NPM.

**Comment by cvle** [comment]
@rofrischmann Still using `3.10.3`

**Comment by rofrischmann** [comment]
Actually found out the problem. I was not shipping peerDeps with the presets :<

**Comment by steida** [comment]
That's what I wrote in the first comment ;-) Anyway, thank for your hard work. Btw, I was almost decided to used styled-components, but then I realised, that CSS strings sucks https://github.com/styled-components/styled-components/issues/256 

Now I am thinking back about glamor or fela. I like a design and modularity a lot, but, there really should be better DX onboarding experience without huge webpack-like configuration hell. I will give fela a second chance and maybe I will send PR. Thank you again.

**Comment by rofrischmann** [comment]
@steida Yeah, I really did not get what that comment meant until I finally realized :D 

And according the styled-components: I also think the biggest drawback is to actually write CSS. Not because it's CSS, but because its a single string and mixing props in feels just uncomfortable.

I would love to have some help getting ppl to use Fela more simple. I guess a guideline, package or tutorial would help.
