### ISSUE TITLE
As for dynamic styles

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#117]
I understand reasons behind, but maybe it should be implemented via inline styles in a browser and via https://facebook.github.io/react-native/docs/direct-manipulation.html in React Native for performance reasons. I don't know. Just a question.

**Comment by rofrischmann** [comment]
Nice catch yeah. I am going to release a blog post about when to use CSS (CSS-in-JS) and Inline Style. Fela is intended to be used for dynamic "components" that have some static styles and a **definite** number of "variations". e.g. if you have a <Box> component that is used as a flexbox provider, you might have sth. like

const rule = props => ({
  display: 'flex',
  flexShrink: props.shrink || 0,
  flex: props.flex,
  alignSelf: 'stretch',
  justifyContent: props.justifyContent,
  alignItems: props.alignItems
})

Now every <Box> has the `display`, `flexShrink` and `alignSelf` by default, while `justifyContent`, `alignItems` and ofc `flex` are dynamic. Nevertheless you will have many use cases where e.g. flex is `1` or `1 0 auto`. So the class is shared and reused. This is extremely useful when doing layouts as you can use flexible styles, still reuse them with all the CSS benefits and yet do not have to define single CSS classes or have tons of bloated inline style strings.

Anytime your rule styles are dynamic in a way that each "variation" is only used once, you might do better using inline styles.

Also, everything that is dynamically animated with JS (not CSS Animations!) should be done via inline styles.

After all, it's the individuals decision on when to use which as I never had any issues even doing dynamic stuff with classes, but you won't get 60fps doing so. Anyways, Fela does not force you to nothing else :P

Well but its hard to write down here in few mins. Be sure to check out the blog post when its out :P
