### ISSUE TITLE
Incorrect redirection in packages/fela-stylesheet/index.js

### ISSUE THREAD

**Issue by venomfly** [rofrischmann/fela#122]
**Version**: 3.0.6-3.0.8
**Environment**: Both
**Type**: Bug

-------------------
#### Description
Index.js in packages/fela-stylesheet points to 'fela/lib/presets/web', causing runtime errors when trying to import 'fela-stylesheet' module. 

```
Uncaught TypeError: fela_stylesheet.create is not a function(…)
```

Works as expected when the mentioned line is changed from
```javascript
module.exports = require('fela/lib/presets/web')
```

to:
```javascript
module.exports = require('fela/lib/tools/StyleSheet')
```

Thank you.

**Comment by rofrischmann** [comment]
Oh. Thanks for mentioning! I forgot to change that when migrating the repository. Would you like to change that and add a pull request?
