### ISSUE TITLE
style isolation vs box-sizing: border-box;

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#126]
I like style isolation, but I also like default box-sizing being set to border-box.
What is the recommended pattern? 

```jsx
* {
  box-sizing: border-box !important;
}
```

or put box-sizing in every component?

**Comment by steida** [comment]
This is my renderStatic

```jsx
// Minimal global CSS for browsers.
  renderer.renderStatic(`
    * {
      ${/* Because box-sizing is not inherited. */''}
      box-sizing: border-box;
    }

    html {
      ${/* Tap highlight to be completely transparent in iOS. */''}
      -webkit-tap-highlight-color: rgba(0,0,0,0);
      ${/* Prevent adjustments of font size after orientation changes in IE and iOS. */''}
      -ms-text-size-adjust: 100%;
      -webkit-text-size-adjust: 100%;
    }

    body {
      ${/* Remove the margin in all browsers. */''}
      margin: 0;
    }
  `);
  return renderer;
```

**Comment by rofrischmann** [comment]
Hmm. I am not sure yet. Never really tried isolation in real world projects, but might test that. I am even using much more global styles e.g. flexbox presets and stuff, so I might not want to use isolation at all. <br>
`!important` always feels like a hack to me.

**Comment by steida** [comment]
Let's mark style isolation plugin as experimental.

**Comment by rofrischmann** [comment]
Seems legit. I'll do that as I got some neat badges to be added to docs for such use cases.

**Comment by steida** [comment]
I don't think it has a priority. Just maintain sensible web preset and don't bother developers with nasty details. We need happy day scenario, not webpack-like configuration PITA.
