### ISSUE TITLE
eslint airbnb

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#128]
I am using it for a long time and I believe it's the best thing. Really well designed. I believe most errors can be fixed automatically.

https://github.com/airbnb/javascript

**Comment by rofrischmann** [comment]
What's different to eslint-config-rackt? I am using my esformatter which is perfectly configured to match the eslint config used, would need to test if it works fine with airbnb's config as well

**Comment by steida** [comment]
It's pretty old and unsupported. It's easy to distract react-router guys ;)
airbnb is defacto standard, it's strict yet very powerful. I don't know what esformatter is, but I bet you don't need it since eslint can fixes almost everything automatically.

**Comment by rofrischmann** [comment]
Oh, esformatter is the tool I use to format my code :P I prefer it over js-beautifier because it has so many configuration options. But I am sure we can change the settings to support airbnb smoothly :)

**Comment by steida** [comment]
Forget about esformatter, maybe it works or not, I don't know, but you will have to run eslint before every commit anyway and eslint can fix (reformat etc.) almost everything autimatically.

**Comment by rofrischmann** [comment]
Oh didnt know it supports that many auto fixes. Well we might be able to use them together anyways, simply send the PR to use airbnb :P

**Comment by rofrischmann** [comment]
I am using this for some of my newer projects, but I see no advantage of switching and improving this right now. Gonna close it
