### ISSUE TITLE
flowtype

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#129]
Let's use flowtype. It's really easy to adopt it gradually. Just add flow-bin into package.json, and enable it in https://nuclide.io/.

Nothing will be broken.

Then, add `/* @flow weak */` in every visited file once edited. It will not sucks, just help. Later we can improve typing by removing `weak` etc.

It's really that good.

**Comment by rofrischmann** [comment]
Feel free to send a pull request to do so. I am really sceptical about typed javascript at all. If I'd like to use types I'd rather not choose JS at all^^

**Comment by steida** [comment]
"Never mind React, Flow is by far the best thing to have happened to JS in recent years."
https://twitter.com/bodil/status/770682312484851713

**Comment by steida** [comment]
I adopted flow in github.com/este/este recently. It makes code more readable, it provides useful autocomplete, it helps when refactoring, it detects errors, etc.

**Comment by rofrischmann** [comment]
Oh ok. So it seems Flow is much more than just type validation?
Feel free to add is then :) Happy to learn new tools gradually in own projects hehe :P

**Comment by steida** [comment]
FYI, I chose fela becuse it not blocks me and styles can be typed as well! Imagine huge app redesign without typed styles. A misery :-/

**Comment by rofrischmann** [comment]
Block in which context? How did other solutions block you?

**Comment by steida** [comment]
Take a loot at app typed model https://github.com/este/este/blob/master/src/common/types.js

**Comment by rofrischmann** [comment]
Ok, I will do that later on. We sure need to chat soon anyways :P 
Btw. I saw you first choose styled-components. If you like the style-to-component approach, you might like `createComponent` from `react-fela` :P

**Comment by steida** [comment]
> Block in which context? How did other solutions block you?

styled-components are no-go because having to pass `props: Props` in every CSS string line is super verbose.
glamor is no-go, because `let rule = style({` isn't pure props => style transformation, I can not use Style return type.

**Comment by steida** [comment]
https://github.com/styled-components/styled-components/issues/256

**Comment by steida** [comment]
As for flowtype, Nuclide is really nice https://github.com/este/este/wiki/Recommended-Atom.io-Settings

**Comment by steida** [comment]
Oh!, .match(/[-_a-zA-Z0-9]*/g) can returns null! Bug! In runtime!

**Comment by steida** [comment]
Btw, we really don't need this old shit with the flowtype.

![screen shot 2016-11-27 at 22 18 55](https://cloud.githubusercontent.com/assets/66249/20651922/8e1fe382-b4ef-11e6-8039-91f475e585af.png)

**Comment by steida** [comment]
Btw, the code formatting is inconsistent as shit but it will be fixed soon with airbnb eslint config ;)

**Comment by rofrischmann** [comment]
What exactly is inconsistent? It's consistent throughout the whole repo.
Also I don't get why we would not need code documentation with flowtype (except for the types ofc)

**Comment by steida** [comment]
> What exactly is inconsistent? It's consistent throughout the whole repo.
Sorry if it sounds hard. My eyes are just adjusted to super strict airbnb. I don't want to be rude. 

> Also I don't get why we would not need code documentation with flowtype (except for the types ofc)
Because everything from aforementioned syntax Fela uses (I know that syntax very well from Closure Compiler times) can be replaced with flowtype.org with less typing and checked during writing.

**Comment by rofrischmann** [comment]
Yeah I see. But only because it's not airbnb doesn't mean its broken. It's still consistent for the whole project using my prefered configuration.
If we can replace the doc stuff with flowtype.org its great. Hated the jsdocs syntax anyways.

**Comment by steida** [comment]
Do you generate docs from that?

**Comment by rofrischmann** [comment]
nop :D just did that for DX reasons to help ppl understand the code

**Comment by steida** [comment]
Done. Now I am going back to my stuff, will add Eslint later. It will require more refactoring, for example the super ling lines, no function expression, etc. But it's definitely worth.

**Comment by rofrischmann** [comment]
No function expression is a no-go. We'll have to ignore that rule. I understand the hype about using arrow functions everywhere, but they come at the cost of readability.

**Comment by steida** [comment]
Let's talk about it later. The most readable syntax is haskell like a -> b -> c which is impossible with function. I removed all functions from Este long time agou, feel free to check code. I believe it's much better but of course, human brain needs time for reality change.

**Comment by rofrischmann** [comment]
I love the arrow functions and use them frequently especially for map, filter, reduce, etc. But for top-level functions I prefer the function state as it's kind of an anchor for the eyes to see its a function (instead of perhaps just a long constant variable)

See https://medium.freecodecamp.com/constant-confusion-why-i-still-use-javascript-function-statements-984ece0b72fd#.f3nkpi99z It kind of shows the same reason as well

**Comment by steida** [comment]
That's what I wrote in the past https://twitter.com/estejs/status/672982441179676672?lang=en :-)

**Comment by steida** [comment]
I maintain pretty huge OSS project and teach people stuff etc., it wasn't easy for me to make a switch, but now I am there and would never go back ;)

**Comment by SpencerCDixon** [comment]
@steida do you have any recommendations on how to use Flow with the `connect` function in fela?  I'm stumped (due to lack of good flow knowledge) and was curious if you had any tips?
