### ISSUE TITLE
Diff static & dynamic style

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#140]
**Version**: 3.x
**Environment**: Both
**Type**: Feature

-------------------
#### Description
With #137 being merged soon, we removed the style diffing in favor of a more simple and universal API allowing nested props without proper checks.
Yet the diffing was and is an advanced feature that heavily reduces the size of the generated markup. The drawback are, of course, no nested props as it has to be able to execute the rule with an empty props object. We can opt in this mechanism using a plugin for advanced usage. 
**It should throw if nested props are passed.**

**Comment by Cavitt** [comment]
https://github.com/rofrischmann/fela/pull/143 should make this issue obsolete I believe.
Nested props are supported.

**Comment by rofrischmann** [comment]
Nested props have been supported with the other PR as well. This issue is exactly to achieve the opposite. Force flat props in favor of style diffing which we completely lost with the new mechanism.

**Comment by Cavitt** [comment]
I mean with the new PR we should be able to have both style diffing without forcing flat props.

**Comment by rofrischmann** [comment]
No. We sadly can not diff styles anymore. (By style diffing I mean separate static and dynamic style properties)

**Comment by Cavitt** [comment]
Archiving relevant gitter conversation:

Make renderRule accept a `defaultProps` argument defaulting to an empty object. Attempt to render with these defaultProps in a try/catch. If it throws, give a warning in development mode and do not split. That will optimize most by default and let users micro optimize rules.

defaultProps would be an object of known used properties, most of the time simply supplying the structure of a deeply nested object would be enough. `{a:{b:{c:{}}}}` One could also merge the default theme object.

`createElement` will need to accept `defaultProps` to pass down to it's renderRule call.

**Comment by Cavitt** [comment]
To clarify, `try/catch` with an empty object should handle most instances.

The defaultProps would be a useful to address the warning when renderRule throws.
