### ISSUE TITLE
naming and api thoughts

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#142]
Do we really need createComponent? As is, it encourages static declaration, but do we really need that? With the advent of functional stateless components, do we need factories like createFooBla? Isn't everything just a transformation? (loud thinking)

Is the `rule` a good naming? Do we need it? Why not style? combineStyles etc. (btw, I think R.compose is better approach, not sure yet).

**Comment by johanneslumpe** [comment]
The nice thing about `createComponent` is that you don't have to `connect` the layout component yourself plus you don't have to create a function for rendering. What exactly is it that you don't like about it?

**Comment by steida** [comment]
Sure, I agree. But it can be even better aka just a pure transformation. I will show an example soon.

**Comment by steida** [comment]
OK, I wrapped it so it's not relevant anymore.

**Comment by johanneslumpe** [comment]
@steida wanna post your solution? :)

**Comment by steida** [comment]
It's still under development, but finally things get shapes. https://github.com/este/este/tree/fela
