### ISSUE TITLE
strings magic free style objects

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#153]
In Este, I have almost 100% statically typed styles. The last problem is some rules, like ` '@media (min-height: 200px)': {`. Flow can't type that.

Flow can type ':hover' etc, but not strings with arbitrary values. This would help a lot:

```js
pseudo: {
  hover: {
    textDecoration: 'underline',
  }
},
media: {
  '(min-width: 700px), handheld and (orientation: landscape)': {
    display: 'none',
  }
},
children: {
  '> *': {
    margin: 20,
  }
}
```

With such design, Flow can check even deeply nested values. But we need strings constants as keys. This would be good enough. Ideally, we should remove any weird strings in favour of real typable JS objects, but the man can only dream.

**Comment by steida** [comment]
This https://github.com/este/este/blob/fb6930f15858aa7d7c0966bcab8c905bb4477da6/src/browser/app/themes/types.js#L138

**Comment by rofrischmann** [comment]
I see the issue, but I really don't like such verbose syntax. I am pretty happy with the style object API as is. Yet there's no problem to build a simple plugin that transforms your syntax into "valid" style objects. If that's something that would work for you, I might quickly create it.

**Comment by steida** [comment]
Agreed
