### ISSUE TITLE
Misconception on 1.3

### ISSUE THREAD

**Issue by Caseyyu2** [rofrischmann/fela#161]
**Version**: 4.1.x
**Environment**: DOM / Server / Both
**Type**: Docs

-------------------
#### Description
According to 1.3, it mentioned on the minimal markup size "this enables modular style reuse on declaration basis. In general, the more styles are rendered, the more duplicate declarations it contains". I prototyped with redux todo example. For both stateless and stateful components, if I have same render rule e.g.,

a  {
 color: 'pink',
 fontSize: 100
}

b {
 color: 'pink',
 fontSize: 150
}

I eventually ended up having 3 atomic classes, one for color, 2 for fontSize. Is this a misconception in the doc, should it be, the more similar styles you have, the less duplicate class you will have?

#### Steps to reproduce
1. First step
2. Second step

#### Expected Behavior
```javascript
// your code here
```

#### Actual Behavior
```javascript
// your code here
```

#### Proposal
Any information on how this might be achieved.

**Code Example**:
```javascript
// your proposal here
```

**Comment by johanneslumpe** [comment]
In your example, it renders the minimal amount of atomic classes required to style your components. You have 3 different props: one for the color and two for the font size.

Previously, the more styles you'd render, the more bloated your css would become.

If you had 5 element rules, all different functions, which all had a colors prop like `color: 'pink'`, you would have ended up with 5 classes. With the new design you will actually have 1 class shared between all of them. So the way things are explained in the docs are correct.

**Comment by rofrischmann** [comment]
@Caseyyu2 @johanneslumpe Guess your both right, just from a different perspective. It's true that it only applies to similar rules and that at at some point it's even possible to have "more" rules with atomic design. I will consider rewriting 1.3 with next update.
