### ISSUE TITLE
No prefix for the generated render rule

### ISSUE THREAD

**Issue by Caseyyu2** [rofrischmann/fela#162]
**Version**: 4.1.x
**Environment**: DOM 
**Type**: Bug / Feature / Infrastructure / Docs / General

-------------------
#### Description
After defining the rules, the output is somethint like .a, .b. Are we thinking about maybe adding a prefix like, fela_a. fela_b. to reduce the change of clashing with other generated css?

Also I have questions regarding binding. Maybe it's more a doc issue. I tried use react-fela, Provider. One with Provider tag wraps around redux Provider, one the other way around. With the Fela provider being the outermost layer, it generated non-duplicated atomic css class, but the other case, it generated duplicate class. Should this consider as a bug, or we need to enhance on the doc side?

#### Steps to reproduce
1. First step
2. Second step

#### Expected Behavior
```javascript
// your code here
```

#### Actual Behavior
```javascript
// your code here
```

#### Proposal
Any information on how this might be achieved.

**Code Example**:
```javascript
// your proposal here
```

**Comment by johanneslumpe** [comment]
I think prefixes should be optional. @rofrischmann what do you think about the ability to set a static prefix when creating the renderer, which defaults to an empty string or undefined?

That way people who do not want it, don't have to use it, but if there actually are clashes with other generated css, then those would be mitigated.

@Caseyyu2 I wonder though why you'd use two css generators. Or are you talking about bundled 3rd party css?

**Comment by Caseyyu2** [comment]
@johanneslumpe yeah, I'm thinking about with bundled 3rd party css, in case there's clash
