### ISSUE TITLE
Possible API improvements

### ISSUE THREAD

**Issue by treshugart** [rofrischmann/fela#164]
**Version**: 4.1.1
**Environment**: Both
**Type**: Feature

-------------------

#### Description

Bravo, Fela is pretty awesome! Wasn't hard to get up and running and I've been wanting to see something that supports dynamic styles based on props as part of its API for awhile now.

Thought the API is fairly straight forward, it left me wanting a more conventionalised API where I didn't have to worry about connecting the dots. Maybe this already exists, but I couldn't find it in the docs.

The idea is here http://www.webpackbin.com/41zPhfnXM. I felt it better to create a functioning example for it, as opposed to trying to do the same here in the issue.

**Comment by rofrischmann** [comment]
Seems legit to ship such an API for advanced usage. You might actually create that project yourself and promote it as a simple opinionated layer over Fela. I do not want to ship something preconfigured (e.g. your proposal uses a global renderer instance, which is not fine for everyone)

**Comment by treshugart** [comment]
Sounds reasonable. I wasn't thinking this would be the exact implementation that would be used, though. I'll close this for now unless you think you'd want to implement something similar. Cheers!
