### ISSUE TITLE
Case sensitive selectors clash in quirks mode

### ISSUE THREAD

**Issue by PhiLhoSoft** [rofrischmann/fela#167]
**Version**: fela@4.1.0
**Environment**: Server
**Type**: Doc

-------------------
#### Description
I generate a rather complex stylesheet in the context of the https://github.com/hellofresh/css-in-js-perf-tests so with server rendering.
Fela worked very well so far, but I stumbled upon a surprising issue. The layout was totally messed up, while all other libraries were good.
Upon inspection, I saw there was a clash between generated class names, like i and I.
![felamessup](https://cloud.githubusercontent.com/assets/1087902/21422215/079fe446-c837-11e6-92fc-8725e8056924.png)
It was supposed to be OK because according to http://stackoverflow.com/questions/12533926/are-class-names-in-css-selectors-case-sensitive class names are case sensitive. Except there is a small footnote: "*In [quirks mode](https://developer.mozilla.org/en-US/docs/Quirks_Mode_and_Standards_Mode) for all browsers, classes and IDs are case-insensitive*".
Okaaay, the project just generates the files without doctype... When I added it, Fela was as good as the others...

So, if that's not already in the [docs](http://fela.js.org/) (I admit I haven't read everything yet), maybe it is worth mentioning it somewhere, as a caveat.
Of course, a good new project will avoid the quirks mode, but I think it is still worth mentioning... 😄

**Comment by rofrischmann** [comment]
Wow. I am impressed now. Never though that still is a thing anywhere :D 
Thanks for mentioning! I will add it to the docs or eventually even remove uppercase letters. It will reduce the amount of classNames < 3 chars from 2700~ to 800~, but that's not a problem at all I guess.

**Comment by johanneslumpe** [comment]
@rofrischmann I guess if we have 800+ classes, we already have so much data that it most likely won't matter if we have a few 3 character class selectors in there.
