### ISSUE TITLE
Child selectors

### ISSUE THREAD

**Issue by PhiLhoSoft** [rofrischmann/fela#169]
**Version**: 4.1.0
**Environment**: Both
**Type**: General

-------------------
#### Description

I read the http://fela.js.org/docs/basics/Rules.html#5-child-selector section and it answers some of my needs, but I feel it leaves some parts out...

BTW, there is a broken link at this page: https://github.com/rofrischmann/fela-stylesheet should be https://github.com/rofrischmann/fela/tree/master/packages/fela-stylesheet (and I failed to understand that is the purpose of this tool).

Back on topic: the `>` notation allows to select an immediate child under a processed class, which is nice already. But it leaves out some cases that can be used to handle 3rd party styles.

For example, I need a [descendant selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_selectors) to attain a deeper child, at an unknown level, within perhaps divs without classes. I discovered at the above page that the `>>` selector can be used for this purpose, perhaps you can handle it?

Another case is adding an adjacent class that must keep its naming. Like `class="foo bar"` noted `.foo.bar` in CSS. `foo` name can be processed but `.bar` needs to remain as is. I don't think that combined rules can handle this. Other libs use the `&` notation for that: `&.bar` or `&bar` as selector name.

Last case, perhaps a bit controversial given the scope of Fela, is to style a child by its tag name. In CSS, that would be `.foo p` ie. any paragraph under a container class. `>> p` notation could work here.

Actually, the `&` operator can handle all these cases, if it means "stick to current class name, keep what follows (including space)". That's how JSS and Glamor handle these cases.

I don't know if these cases fit in the philosophy of Fela, but it started some support with child selectors, I hope it can go a bit further... 😄

**Comment by rofrischmann** [comment]
Haha, I've never seen the `>>` until now. Damn CSS Syntax. I thought you can use `>` to style **any** inner element? e.g. https://jsfiddle.net/foj2toqv/

Actually, I do not really see a use case for `.foo.bar`, could you perhaps show one? After all, I am happy to add the & if that helps, but to be consistent with e.g. SASS I would have to use the `&` for pseudo classes to right? e.g. `&:hover` => `.a:hover` while `:hover` then transforms to `.a :hover` which I do not really like. 

According to the last case: You can use `> p` to style child elements by tag name.

**Comment by PhiLhoSoft** [comment]
Yes, I discovered `>>` when I wrote this issue... 😄 
The `.foo.bar` case might be resolved in a more idiomatic way with Fela. I needed it in the https://github.com/hellofresh/css-in-js-perf-tests project, where we have one stylesheet declaration for all CSS-in-JS libraries, with minor adjustments for syntax. Note that's in the context of server-side rendering (no interaction).
In an example, I have a list of components, and I add a `special` class name on some of them (conditionally) to change its look (background color). This is supposed to reflect a state in the component's data.
So the case is to add a class name to alter the look. Which is not the Fela way to doing things, I suppose...

About your example: it doesn't reflect the usage of `>` because you used a property that is inherited. I changed it a bit to use non-inherited properties, like border or margin: https://jsfiddle.net/foj2toqv/1/
The innermost div doesn't get these properties, while it does if you remove the `>`.

About consistency: some libraries require `&` before `:hover`, while others consider that the `:` is enough to indicate it must stick to the parent class name. Kind of implicit `&`.

**Comment by rofrischmann** [comment]
@PhiLhoSoft 

> About consistency: some libraries require & before :hover, while others consider that the : is enough to indicate it must stick to the parent class name. Kind of implicit &.

The problem is, that these solutions yield different effects. 
`&:hover !== & :hover` The first one applies if the current className is hovered, the second one applies to all children if hovered. (see https://jsfiddle.net/jsjb3by0/)

I would want to have: `:hover` to apply to the current element while `&:hover` applies to its children, but then the `&` is not the best character here.

**Comment by rofrischmann** [comment]
@PhiLhoSoft this gets released in 20mins :P
