### ISSUE TITLE
Provide jsnext:main package for rollup builds

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#17]

**Comment by johanneslumpe** [comment]
@rofrischmann is this still something you actively want to do? It seems that it would be useful to add this, since we now can use tree-shaking with webpack 2.

**Comment by rofrischmann** [comment]
Yeah! I guess its pretty much straightforward to add it. Will do this with the next release.

**Comment by rofrischmann** [comment]
We need to transpile the code except for the import/export declaration. https://github.com/rollup/rollup/wiki/jsnext:main
