### ISSUE TITLE
let react-fela passThroughProps accept function

### ISSUE THREAD

**Issue by bkniffler** [rofrischmann/fela#174]
**Type**: Feature
#### Proposal
Add the ability to give passThroughProps a function instead of an array. This would greatly improve flexibility, especially if you want to pass all props except some.

**Code Example**:
```javascript
const Tab = createComponent(({ theme, active }) => ({
  fontWeight: active ? 'bold' : null,
}), SomeComponent, ({ active, ...rest }) => rest);
```

**Comment by rofrischmann** [comment]
This makes a lot of sense. I am welcoming a pull-request :P 
But it'd be cool to perhaps support both array and function.
