### ISSUE TITLE
warning "fela-native@4.1.2" has incorrect peer dependency "react-native@^0.30.0".

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#180]
Please don't close it. I will send pull request.

![screen shot 2017-01-22 at 07 13 10](https://cloud.githubusercontent.com/assets/66249/22180512/48989f76-e072-11e6-81cb-4fd86f5afb27.png)

**Comment by rofrischmann** [comment]
I don't get where the problem is. Which version do you use? I thought v30 would be quite "old" :P But I guess it would work with any version, so yeah, let's improve that.

**Comment by steida** [comment]
I am using 0.39, as is in Este.

**Comment by arjunpola** [comment]
Thank you for working on this issue @steida. I recently found Este and starting using it but could not add any new dependencies because I cannot upgrade react-native to 0.40.0.

**Comment by steida** [comment]
I checked it with NPM, the same warning.
"npm WARN fela-native@4.2.0 requires a peer of react-native@^0.30.0 but none was installed."

**Comment by steida** [comment]
Hmm, I am unable to find out why this warning is shown. No other RN dependency has this problem. I think we can safely remove this peer dependency.

**Comment by steida** [comment]
Or put there "react-native": "*"
https://github.com/react-community/react-navigation/blob/c5720cafb43a2c20cc6c02269860c1aa617d5448/package.json#L62
