### ISSUE TITLE
[react-fela]: Allow pass through props to travel through compositional tree

### ISSUE THREAD

**Issue by ctrlplusb** [rofrischmann/fela#188]
**Version**: 4.1.2
**Environment**: Both
**Type**: Bug / Feature

-------------------
# Description

It appears that `passThroughProps` isn't respected across composed Component boundaries.  

I am not sure if this qualifies as a bug or a feature request so I will just outline what I expect (or would like) to happen below.

It would be awesome if we could set `passThroughProps` on a _base_ Fela Component, or on one that composes ontop of a _base_.  Additionally, it would be great if any `passThroughProps` across a composed set were merged.

__Top Down:__

```js
const ResponsiveImage = createComponent(
  () => ({ width: '100%' }),
  'img'
)

const Logo = createComponent(
  () => ({ zIndex: theme.z.high }),
  ResponsiveImage,
  ['alt', 'src'],  // 👈
)

<Logo alt="foo" src"/bar.jpg" />
```

__Bottom Up:__

```js
const ResponsiveImage = createComponent(
  () => ({ width: '100%' }),
  'img',
  ['alt', 'src'],  // 👈
)

const Logo = createComponent(
  () => ({ zIndex: theme.z.high }),
  ResponsiveImage
)

<Logo alt="foo" src"/bar.jpg" />
```

__Merged:__

```js
const ResponsiveImage = createComponent(
  () => ({ width: '100%' }),
  'img',
  ['alt', 'src'],  // 👈
)

const ClickableLogo = createComponent(
  () => ({ zIndex: theme.z.high }),
  ResponsiveImage,
  ['role', 'onMouseDown'],  // 👈
)

<ClickableLogo alt="foo" src"/bar.jpg" role="link" onMouseDown={() => console.log('clicked')} />
```

**Comment by ctrlplusb** [comment]
Oh, currently none of the above work.  Composition can't be used with `passThroughProps` at the moment.

**Comment by rofrischmann** [comment]
Thanks for reporting. I thought I had tested merged passThroughProps, but it seems I missed something?

**Comment by rofrischmann** [comment]
Omg. I found the issue. There was an error when publishing the packages. react-fela was still 4.1.2. Fixed it.

**Comment by ctrlplusb** [comment]
Wow, that was some awesome turnaround time!
