### ISSUE TITLE
[Plugin] Conditional style extension

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#19]
A custom property that merges some styles based on a condition. It would be defined with an expression string such as: 
```javascript
const selector = props => {
  color: 'red',
  fontSize: '14px',
  'isActive=true': {
    color: 'blue',
    backgroundColor: 'red'
  }
}

render(selector, { isActive: true })  // => {font-size:14px;color:blue;background-color:red}
render(selector) // => {color:red;font-size:14px}
```

See https://github.com/rofrischmann/react-look/blob/develop/packages/react-look-core/modules/mixins/condition.js for an example implementation

**Comment by johanneslumpe** [comment]
Is this really the way to go?

Wouldn't it be possible to just do:

```js
const selector = ({ isActive }) => ({
  ...(isActive && {
    color: 'red',
  }),
})
```

**Comment by johanneslumpe** [comment]
Didn't test that, tying on phone - might need to use a ternary there instead of &&

**Comment by rofrischmann** [comment]
Yeah. You could do that. It's all about syntax sugar :P I just want to "support" most of react-look's features / mixins / plugins. There's no need to actually use this^^

**Comment by rofrischmann** [comment]
Can now be achieve using the `fela-plugin-extend` plugin. Closes this for now.
