### ISSUE TITLE
Error when build

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#191]
Not sure why, but compiled Este has this error:

![screen shot 2017-01-28 at 09 41 29](https://cloud.githubusercontent.com/assets/66249/22395409/0495c832-e53e-11e6-8c15-dcd6ebe6b39e.png)

**Comment by steida** [comment]
When `placeholderPrefixer()` is commented, it works.

**Comment by rofrischmann** [comment]
Looks like CSSStyleSheet does not allow `::-moz-placeholder`. We need to use `textContent` here I guess.

**Comment by steida** [comment]
Not only 
![screen shot 2017-01-29 at 05 46 35](https://cloud.githubusercontent.com/assets/66249/22401926/5aa80bce-e5e6-11e6-9ef9-0746f3fcc846.png)

**Comment by steida** [comment]
Hmm, we need to render everything on the server, and do try catch detection only on client.

**Comment by steida** [comment]
This is temp fix https://github.com/este/este/commit/f1d25590e363eb6b7822295ad3318e2a898ccba8#diff-708d62a603a169ef52169d279ec05623

**Comment by steida** [comment]
How you test dev Fela with real project? npm link? Can you use my diff to fix? It's pretty simple.

**Comment by steida** [comment]
@rofrischmann Can you open it please? This should really be fixed only for Chrome.

**Comment by steida** [comment]
Hmm, the fix I suggested breaks things.
![screen shot 2017-02-05 at 20 55 01](https://cloud.githubusercontent.com/assets/66249/22629409/c2cb37d0-ebe5-11e6-8bd5-cff7ce1d1383.png)

**Comment by abelaska** [comment]
@steida exactly.

Fela 4.2.1 with fela-plugin-placeholder-prefixer 4.2.1 works just fine for me. Your workaround este/este@f1d2559#diff-708d62a603a169ef52169d279ec05623 is no longer needed.

**Comment by steida** [comment]
@abelaska I know, it's removed in branch already. Fela fix was released after talk with Robin.

**Comment by abelaska** [comment]
@steida ok
