### ISSUE TITLE
Class conflicts (e.g. font-awesome "fa")

### ISSUE THREAD

**Issue by bkniffler** [rofrischmann/fela#192]
Hey, 
The name generation can clash with other classes, in my case there's been issues with font-awesome "fa", where elements where displayed `inline-block`.

Is there a way to avoid that?

**Comment by rofrischmann** [comment]
There's the option to add a `selectorPrefix` to your renderer. Check out this example: http://fela.js.org/docs/advanced/RendererConfiguration.html
But it feels kinda verbose. e.g. `_` so keep it small.

**Comment by bkniffler** [comment]
Ah, great! Thanks 👍
