### ISSUE TITLE
question(react-fela): Overriding nested Component styles

### ISSUE THREAD

**Issue by Craga89** [rofrischmann/fela#194]
Say we have two components, `ButtonGroup` and `Button`, both themed using the `connect()` decorator. `ButtonGroup` is simply a component that renders multiple `Button` components in, well, a group.

Now say, I want to control the styles of the nested `Button`(s) from the upper `ButtonGroup` component, for example to apply some additional styling based on it's presence inside the `ButtonGroup`. Here's a more concrete look at what I mean using regular old CSS:

```css
.btn {
   /* Button specific styles go here */
}

.btn-group .btn {
   /* Buttons within a ButtonGroup styles go here */
}
```

How would you model such a thing using `fela` and `react-fela`? I've tried a couple things, but neither seem like a good fit (or work!):

* Merge in additional `styles` from pass-through `props` within the `Button.mapStylesToProps` method
* Hard code a custom selector name in the `ButtonGroup` ruleset ('& .btn'), and pass it through as a `className` to the `Button`

## Merge in additional `styles` from pass-through `props`
My first approach was to utilise the `mapStylesToProps` method to merge in any additional `styles` keys passed through from the upper `ButtonGroup` to the `Button`

```js
// Button.js
class Button extends Component {}

const mapStylesToProps = (props) => (renderer) => ({
   btn: [
      props.styles.btn, // Pass-through from ButtonGroup
      renderer.renderRules(rules, props)
   ]
});

export default connect(mapStylesToProps)(Button);
```
```js
// ButtonGroup.js
class ButtonGroup {
   render() {
      // ...
      <Button styles={styles}
   }
}

const btnRules = (props) => ({
   color: 'red'
});

const mapStylesToProps = (props) => (renderer) => ({
   btn: renderer.renderRules(btnRules, props)
});

export default connect(mapStylesToProps)(ButtonGroup);
```
This works, but it's a britle and seems a little messy. Plus, it seems to strip some styling from the nested `Button`s in some scenarios... which I'm guessing means there's a conflict going on here with the generated class names. Studying the documentation it seems you'd actually need to use `combineRules`? So this is probably a no-go!

## Hard code a custom selector name in the `ButtonGroup` ruleset
By second approach was to simply use the `&` prefix to create a hard-coded selector name that is nested within the usual `rules` of the `ButtonGroup`. This class name is then passed to the child `Button`(s) as a `prop` and applied as an additional `className`

```js
// Button.js
render() {
   // additionalClassNames contains the hard-coded selector `btn`, see below
   const { additionalClassNames, styles } = this.props;
   const className = [ ...additionalClassNames, styles.btn ];
   return (<div className={className} />);
}
```
```js
// ButtonGroup.js
...
const rules = (props) => ({
   '& .btn': { // Hard-coded selector name, which we'll pass-through to `Button`, too.
      color: 'red'
   }
});
```
This works, but hard coding the class name is ugly, and defeats the purpose of the auto generated class names. It also doesn't take into account `selectorPrefix` etc. as it sits outside the renderer. Again, messy.

Hopefully this explains what I'm trying to achieve in some detail. Let me know if you need more information, and apologies if this isn't the right forum for this type of question, but it seems like a common use case that I didn't see covered.

**Comment by rofrischmann** [comment]
@Craga89 Sorry for the delay.

I will edit this message soon, to give you tips on how to achieve that. It's quite simple and there are different ways to do it, depending on personal preferences and your code structure, you might choose the one that fits best.

**Comment by rofrischmann** [comment]
So, I came up with the following solution:

1. ButtonGroup could wrap the <Buttons> inside a <ThemeProvider> to pass some explicit configurations to each <Button>. This is similar to your first example, but seems to be a bit more elegant I guess (as you do not have to explicitely pass something to the buttons, but rather consume the special "props" through (`props.theme`))

2. You do not really need to hardcode a selector, as you can just use sth. like `> button` right? I'd expect that a <ButtonGroup> does not contain any other Component than <Button> itself, so this would be safe as well.

Hope this helps! If not feel free to reopen. Also there might be more solutions, but I believe we do not have to overcomplicate the problem here!
