### ISSUE TITLE
Monolithic mode?

### ISSUE THREAD

**Issue by tiagojsalmeida** [rofrischmann/fela#195]
**Version**: 3.0.x
**Environment**: Both
**Type**: Feature

-------------------
#### Description
Atm you guys only support atomic classnames.
Would it be possible to implement an monolithic mode?

#### Proposal

**Code Example**:
```javascript
createRenderer({
   mode: 'monolithic'
})
```

**Comment by rofrischmann** [comment]
Not sure about that. I don't see any advantages actually. But it might be possible to just have an alternative renderer. The React Native renderer e.g. is also a totally different renderer.

**Comment by tiagojsalmeida** [comment]
@rofrischmann In our case it would be ideal to use the monotithic version on development as it's just easy to change styles.
On our implementation we made our own render method as we don't want to use `sheet.insertRule` for multiple reasons (specially because of third-party applications).

I would totally help. Could you point me on the right direction?

**Comment by rofrischmann** [comment]
You could basically take the existing renderer and simply replace renderRule. I may give you a list of "things" which you need to do in order to achieve correct classnames etc.

**Comment by rofrischmann** [comment]
Added with #200
