### ISSUE TITLE
react-fela pseudo selector

### ISSUE THREAD

**Issue by Orgil** [rofrischmann/fela#196]
How do i use pseudo selector like ::before, ::after? Nesting like pseudo classes doesn't work.

**Comment by rofrischmann** [comment]
What exactly doesn't work? Can you give me an example?

**Comment by Orgil** [comment]
```
  changed: {
    position: 'relative',
    ':before': {
      content: '',
      position: 'absolute',
      top: 0,
      right: 0,
      borderLeft: '5px solid transparent',
      borderTop: '5px solid #d22c00',
      zIndex: 1000
    }
  },
```
it doesn't add content to the before element.

**Comment by rofrischmann** [comment]
How does the changed resolve? Can you give the full example? And as I can see your content is empty right?

**Comment by Orgil** [comment]
yes. if i add content manually to the element on browser, it works. I'm using fela-stylesheet with style-connector. All my ':hover', ':last-child' etc are working.

**Comment by rofrischmann** [comment]
Could you please try using: `content: '""'`? I know it seems ridiculous, but as the value is a string by default, we actually need to have these nested-quotes here.

**Comment by Orgil** [comment]
That was it. Thanks.

**Comment by ivan-zakharchuk** [comment]
I have the same issue with the latest fela/react-fela and the mentioned trick doesn't help(as you can see on the screenshot below the content wasn't added and hence element is not rendered), were some changes made for ":before", ":after" nesting?
<img width="395" alt="screen shot 2018-09-01 at 9 34 19 am 1" src="https://user-images.githubusercontent.com/12155794/44943158-68ea8880-adca-11e8-8507-0a53db9bfe2f.png">

**Comment by rofrischmann** [comment]
@ivan-zakharchuk Can you send a short code example (simple repo showing that problem) so I can investigate?
Would also be useful to know which versions are used here.

**Comment by ivan-zakharchuk** [comment]
I'm sorry but it was an issue with build cache in my particular project hence issue might be closed
