### ISSUE TITLE
need reference on connected component

### ISSUE THREAD

**Issue by Orgil** [rofrischmann/fela#197]
connect wrapper component need to have reference to wrapped component, in case of access to wrapped component. I know it should be separated as dumb component but in my work i needed to access to wrapped one. @rofrischmann What do you think?

**Comment by rofrischmann** [comment]
Can you give me an example why you would need that? Isn't the reference to the styled component enough as it's truly the same, except for styling?

**Comment by Orgil** [comment]
in my case, i exposed some public functions so i need to call it from
outside. Since it is wrapped by HOC, its not possible to call it.

**Comment by rofrischmann** [comment]
Do you have a working code example? You could be able to call any method on connected component as well, or am I missing something?

**Comment by Orgil** [comment]
how do you call public functions from wrapped component? just create public function then call it through connected component. I don't think it would be callable without wrapped component reference. If i missed something point the right direction.

**Comment by rofrischmann** [comment]
Ah sorry, I misunderstood your intention. Anyways, I believe if you need to call a public function, then your Component design is not ideal. Components wrapped by `connect` or `createComponent` should not expose any functionality at all. They should only be used for styling. If you need styled components with functionality, simply wrap return the styled component from the Component with public functions.

Going to close this one for now. If you think this is wrong, please provide a real example which shows why you **can't** do the above mentioned pattern.
