### ISSUE TITLE
Rehydration?

### ISSUE THREAD

**Issue by tiagojsalmeida** [rofrischmann/fela#198]
**Version**: 4.2.1
**Environment**: Server
**Type**: Feature

-------------------
#### Description
A lot changed since version 3.0 where you guys tried to implement rehydration (https://github.com/rofrischmann/fela/issues/71).
At this point, would it be something in the roadmap?

#### Proposal

**Code Example**:
```javascript
renderer.rehydrate() // after client is bootstrapped.
```

**Comment by rofrischmann** [comment]
Not sure about this either. I removed it as it was useless in my eyes. I was abusing the ability to rehydrate rather than doing it "right" without. Would love to see your use case for rehydration though.

**Comment by tiagojsalmeida** [comment]
So, on server side render you create a new renderer, get all the current styles and print them inside a `style` tag.

But then javascript kicks in on the client side it, creates a new renderer, loads the remaining components that generate some of the same styles plus more styles. At this point the client doesn't have a way to know which styles are already injected from SSR.

When you rehydrate you will need to know which classnames/styles have been injected before somehow.

I was trying to achieve this on Fela but you can't re-generate styles from `renderer.cache` nor anything else.

**Comment by rofrischmann** [comment]
Oh I see. You don't need that. On the client, Fela will rerender the styles to add them to the cache again, but won't render anything to the client except it's new. (At least if you call `FelaDOM.render` the first time **after** componentDidMount - see the <Provider> for reference).

There is no advantage of actually "rehydrating" the CSS-string into the cache. It might be even slower than the shallow rerender (without a DOM update) I guess, because `renderRule` is **really fast**.

The previously implemented `renderer.rehydrate` was actually not "real" rehydration, but kind of reevaluated the rules using new constant props. (Therefore, it was quite a hack and for sure not best practise :P)

**Comment by tiagojsalmeida** [comment]
But how does Fela do it, when there's two separate Renderer's?
On react, you could just use the provider to get access to the SSR renderer and it's cache I guess

**Comment by rofrischmann** [comment]
Why would you use two separate renderer? That doesn't make sense. You want to have the same styles on server & client right?

**Comment by tiagojsalmeida** [comment]
Yes, the styles are the same. But on SSR we only have placeholder components, so we don't render all the styles.
Then on the client we create a new renderer + a stylesheet and append all these styles.
So, without the provider on react, how could you achieve that?

**Comment by rofrischmann** [comment]
What's the reason for not using the Provider? If you basically do everything different than "our" best practise, why would you even use Fela at all :P (Or do I misunderstand something?) 

You could basically use the `render` in your Root Component's `componentDidMount` to render the cached styles to the stylesheet for the first time. That would save you many DOM updates while still rendering the components. After the successful mounting, it will use the `render` subscription for every update as usual.

If your server-rendered markup is identical to the client-rendered (after the initial render) you do not have to update the DOM at all (which the current `render` already takes care of)

**Comment by rofrischmann** [comment]
Going to close this here. If you have more questions, please ping me on Gitter or reopen the issue.
