### ISSUE TITLE
Rework LVHA plugin

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#199]
As is, it breaks server-side rendering for any other than V8 engine, because object sorting is not specified in JavaScript. The better and faster solution could be not sorting anything at all, just pick LVHA props values, delete props, add them in the order.

**Comment by steida** [comment]
Thank you Robin!

**Comment by abelaska** [comment]
Hey,  I am still having trouble with order CSS class order. Any clue what may be causing different class order in styles rendered on server and browser (Chrome)?

Thanks!

### Browser
**.am{color:#343a40}**.an{margin-top:24px}.ao{padding-bottom:24px}.ap{padding-top:23px}.aq{border-top-width:1px}.ar{border-style:solid}.as{font-size:12px}.at{color:#228ae6}

### SSR
.am{margin-top:24px}.an{padding-bottom:24px}.ao{padding-top:23px}.ap{border-top-width:1px}.aq{border-style:solid}.ar{font-size:12px}**.as{color:#343a40}**.at{color:#228ae6}

**Comment by steida** [comment]
Try to isolate that bug. Comment out all fela plugins, then add them one by one.

**Comment by abelaska** [comment]
@steida thanks. I've tried and no luck. I am using react-apollo graphql higher-order-component. My app is based on latest este. SSR works ok with latest fela 4.2.2 but only without the graphql component. CSS classes order is always messed up every time I try to use the graphql component.

It should work, the graphql component just fetches data from server and stores them. In browser I always get: 

> Warning: React attempted to reuse markup in a container but the checksum was invalid.

I've been trying to solve this all day long. It most likely is react-apollo problem but I have no clue where to look next.

Any idea?

For example this works well:

```
export default compose(
  connect((state: State) => ({
    viewer: state.users.viewer,
  })),
)(MePage);
```

but this results in re-render in browser:

```
const CurrentUser = gql`
  query CurrentUser {
    currentUser {
      id
      displayName
      picture
      email
    }
  }
`;

export default compose(
  graphql(CurrentUser, { options: { ssr: true } }),
  connect((state: State) => ({
    viewer: state.users.viewer,
  })),
)(MePage);
```

Here's the entire page, classic este me page.

```
// @flow
import type { State, User } from '../../common/types';
import React from 'react';
import SignOut from '../auth/SignOut';
import getUserPhotoUrl from '../../common/users/getUserPhotoUrl';
import linksMessages from '../../common/app/linksMessages';
import { Box, Image, Text } from '../../common/components';
import { FormattedMessage } from 'react-intl';
import { Link, Title } from '../components';
import { Match, Redirect } from 'react-router';
import { connect } from 'react-redux';
import { compose } from 'ramda';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';

// Pages
import Profile from './ProfilePage';
import Settings from './SettingsPage';

const HeaderLink = ({ message, ...props }) => (
  <FormattedMessage {...message}>
    {message => (
      <Link paddingHorizontal={0.5} {...props}>
        {message}
      </Link>
    )}
  </FormattedMessage>
);

const Header = ({ pathname }) => (
  <Box flexDirection="row" marginBottom={1} marginHorizontal={-0.5}>
    <HeaderLink activeOnlyWhenExact to={pathname} message={linksMessages.me} />
    <HeaderLink to={`${pathname}/profile`} message={linksMessages.profile} />
    <HeaderLink to={`${pathname}/settings`} message={linksMessages.settings} />
  </Box>
);

type MePageProps = { pathname: string, viewer: User, data: object };

const MePage = ({ pathname, viewer, data }: MePageProps) => {
  return !viewer
    ? <Redirect to="/" />
    : <Box>
        <Title message={linksMessages.me} />
        <Header pathname={pathname} />
        <Match
          exactly
          pattern={pathname}
          render={() => (
            <Box>
              <Text>{viewer.displayName}</Text>
              <Box marginVertical={1}>
                <Image src={getUserPhotoUrl(viewer)} size={{ height: 100, width: 100 }} title={viewer.displayName} />
              </Box>
              <Box flexDirection="row">
                <SignOut />
              </Box>
            </Box>
          )}
        />
        <Match pattern={`${pathname}/profile`} component={Profile} />
        <Match pattern={`${pathname}/settings`} component={Settings} />
      </Box>;
};

const CurrentUser = gql`
  query CurrentUser {
    currentUser {
      id
      displayName
      picture
      email
    }
  }
`;

export default compose(
  graphql(CurrentUser, { options: { ssr: true } }),
  connect((state: State) => ({
    viewer: state.users.viewer,
  })),
)(MePage);
// export default connect((state: State) => ({ viewer: state.users.viewer }))(MePage);

```

**Comment by steida** [comment]
I don't know why QraphQL should mess up classNames. I would check server render, which will be replaced with found router soon btw. But honestly, I don't know.

**Comment by abelaska** [comment]
I'll try later with found router. 

Thanks anyway, keep it up @steida 👍

**Comment by ravikiran438** [comment]
#https://github.com/apollographql/react-apollo/issues/536
