### ISSUE TITLE
"jspm install npm:fela" does not work

### ISSUE THREAD

**Issue by PavelPZ** [rofrischmann/fela#208]
Thanks a lot for great fela - it is missing piece to REACT puzzle for me.

I am using JSPM package manager (ver. 0.19) but it does not work for fela. When I call
```jspm install npm:fela```
from command promt, only directory structure is build, without any file in subdirectories. It means, that JSPM does not understand fela NPM package well.

I am not expert for JSPM packaging but if I compare https://github.com/rofrischmann/fela/blob/master/package.json with e.g. https://github.com/JedWatson/classnames/blob/master/package.json it seems, that
```"main": "index.js"```
in package.json is missing.

**Comment by rofrischmann** [comment]
The package that gets installed as fela is the following: https://github.com/rofrischmann/fela/blob/master/packages/fela/package.json

Here you have the index.js and the lib-folder is also present on npm, so it should just work fine.

Compare: https://unpkg.com/fela@4.2.5/
I've not used jspm before, so I don't know how it works and why it'd fail here :/

**Comment by PavelPZ** [comment]
@rofrischmann ok, thank you. In the meantime I copied fela.js and fela-dom.js by hand.

**Comment by rofrischmann** [comment]
@PavelPZ Maybe this helps: https://github.com/jspm/jspm-cli/issues/1583 ? Got no idea how JSPM works actually :/

**Comment by PavelPZ** [comment]
Thanks, I will get back to it later.

**Comment by rofrischmann** [comment]
Any new findings here :P? @PavelPZ

**Comment by PavelPZ** [comment]
Not yet, sorry. I have a lot of work to make a correct decision about refactoring our e-Learning system from Bootstrap LESS to Fela. 
I am only user of JSPM, I have no idea how to make JSPM compatible npm package. But I can see this fragment in your https://github.com/rofrischmann/fela/blob/master/packages/fela/package.json:
```
"files": [
    "LICENSE",
    "README.md",
    "index.d.ts",
    "index.js",
    "/lib",
    "/dist"
  ]
```
Listed files are only files, which ```JSPM install npm:fela``` copied to my project. I plan to explore package.json from npm packages, which works well.

-----------
Btw, it will be nice to generate semantic class names (similar to Atomic CSS) as ```W(20px) Ta(c) C(gray) M(5px)``` instead of e.g. ```a b c d``` in Fela for:
```
{ 
  width: '20px',
  text-align: 'center',
  color:'gray';
  margin:'5px';
}
```

**Comment by PavelPZ** [comment]
Try pls this version of ```file``` section of https://github.com/rofrischmann/fela/blob/master/packages/fela/package.json:
```
"files": [
    "LICENSE",
    "README.md",
    "index.d.ts",
    "index.js",
    "dist/**"
  ]
```

I can see a similar approach in working package.

**Comment by rofrischmann** [comment]
Thanks for the message! Will try that!

**Comment by PavelPZ** [comment]
Working, thanks!

The same problem is with fela-dom, can you prepare similar fix?

**Comment by rofrischmann** [comment]
I will add it to every package, thanks :)
