### ISSUE TITLE
More detailed Typescript definition

### ISSUE THREAD

**Issue by PavelPZ** [rofrischmann/fela#209]
I prepared https://github.com/PavelPZ/fireb/blob/master/typings/fela.d.ts for my fela testing. It contains more detailed version of your index.d.ts. 

It is not tested yet (I need to install fela by JSPM first). Are you interested in such activity? After some testing I can prepare better (commented etc.) version.

**Comment by rofrischmann** [comment]
Sure, I am really happy with any contribution for TypeScript as I am not using it my own!

**Comment by PavelPZ** [comment]
Ok, great, see https://github.com/rofrischmann/fela/pull/210.

**Comment by rofrischmann** [comment]
merged

**Comment by PavelPZ** [comment]
I am sorry, I forgot correct ```string``` return value for following IRenderer methods:
```
    renderRule(rule: TRule, props: TRuleProps): string;
    renderKeyframe(keyFrame: TKeyFrame, props: TRuleProps): string;
```
I modified my https://github.com/PavelPZ/fela fork. Could you please merge once more?
