### ISSUE TITLE
Broken typescript typing in fela-4.2.6

### ISSUE THREAD

**Issue by eaglus** [rofrischmann/fela#216]
**Version**: 4.2.6
**Environment**: Both
**Type**: Bug

-------------------
#### Description
Typescript typing for IRenderer.renderRule broken in this commit: https://github.com/rofrischmann/fela/commit/566401158e092989b951e69bb655891872071a73#commitcomment-21166401

#### Steps to reproduce
Try to compile this typescript code:
```
import * as Fela from 'fela';
const renderer = Fela.createRenderer();
const clazz: string = renderer.renderRule(rule, props);
//return value of renderRule in 4.2.6 is void, not string
```

#### Expected Behavior
no compile errors in typescript

#### Actual Behavior
compile errors in typescript: Type 'void' is not assignable to type 'string'

**Comment by rofrischmann** [comment]
Feel free to send a PR to fix it

**Comment by PavelPZ** [comment]
I modified my https://github.com/PavelPZ/fela fork. 
Could you please merge once more? Or new PR is necessary?

**Comment by rofrischmann** [comment]
Oh, my bad. We already got it merged. Should be pushed next days.
