### ISSUE TITLE
fela-plugin-validator doesn't work for me

### ISSUE THREAD

**Issue by Cowboy-coder** [rofrischmann/fela#219]
**Version**: 4.2.6
**Environment**: Both
**Type**: Bug

-------------------
#### Description
It doesn't seem like `fela-plugin-validator` actually does anything. For me `type` is always undefined for me here https://github.com/rofrischmann/fela/blob/master/modules/plugins/validator.js#L77

#### Expected Behavior

I expect this to fail the validation:
```jsx
    const Test = createComponent(props => ({
      color: 'red',
      padding: '20px undefined 0px',
    }), 'h1');
```

#### Actual Behavior

It doesn't fail and if I add logs to the function mentioned above:

```js
console.log('style', style);
console.log('type', type);
console.log('options', options);
```

I get this:

```
style { color: 'red', padding: '20px undefined 0px' }
type undefined
options { logInvalid: true, deleteInvalid: true }
```

and since `type` is undefined it doesn't validate anything.

**Comment by rofrischmann** [comment]
I just found out that while refactoring some stuff, I accidently forgot to update the validator to the new rendering signature. Good catch! Will update as soon as possible.
