### ISSUE TITLE
Theme updates get blocked by redux shouldComponentUpdate

### ISSUE THREAD

**Issue by benoneal** [rofrischmann/fela#223]
**Version**: 4.2.6
**Environment**: DOM
**Type**: Bug 

-------------------
#### Description
Redux connected components that sit between themed components and the ThemeProvider implement `shouldComponentUpdate`, which will prevent theme changes propogating through that boundary if it returns false. 

#### Steps to reproduce
1. Build something like this: 
```
<StoreProvider store={store}>
  <ThemeProvider theme={theme}>
    <ConnectedComponent>
      <ThemedViewComponent>
```
2. Trigger a change in theme that doesn't change state for `ConnectedComponent`

#### Expected Behavior
`ThemedViewComponent` should update. 

#### Actual Behavior
`ThemedViewComponent` doesn't update. 

#### Suggestion
Use [React-Broadcast](https://www.npmjs.com/package/react-broadcast) to manage theming.

**Comment by rofrischmann** [comment]
Hmm I see. But I am not sure if this actually is a problem to the library itself. How would you suggest to solve it with react-broadcast? An example would be great.

**Comment by benoneal** [comment]
Sure. I implemented react-broadcast in my i18n lib [translated-components](https://github.com/benoneal/translated-components) for exaclty this same reason. You can see how it broadcasts langauge changes to children of the HoC [here in the source](https://github.com/benoneal/translated-components/blob/master/src/index.js). 

In pseudo-code, this might look like this: 
``` javascript
const renderer = createRenderer()

export const ThemeProvider = ({
  theme,
  children
}) => (
  <Broadcast channel={'fela-theme'} value={theme}>
    <div>{children}</div>
  </Broadcast>
)

const themed = (styles) => (Component) => (props) => (
  <Subscriber channel={'fela-theme'}>
    {(theme) => <Component {...props} styles={styles({...props, theme})(renderer)}/>}
  </Subscriber>
)

export default themed
```

**Comment by rofrischmann** [comment]
We could add that to the <ThemeProvider> API docs (packages/react-fela/docs/ThemeProvider.md), so ppl know there's this gotcha? Could also have a new FAQ entry. Im happy for any PR in that way :)

**Comment by steida** [comment]
@benoneal Try this https://github.com/este/este/blob/13c29357560df8dd866a52c60feda7417b3366a8/src/common/app/common.js#L19

**Comment by benoneal** [comment]
@steida sorry, but that still doesn't address the issue I'm having. 

In my use-case, the name of the theme doesn't change. I'm creating a white-label application with themable pages. Users can edit their brand colors inline and see them updated immediately. 

The only way key would work in this scenario would be to `JSON.stringify` the theme and use that as a key, but that's hacky. 

It really should be addressed as part of the core library. If the theme changes in any way, themed components should update with the new theme even when no other state has changed.

**Comment by benoneal** [comment]
[This PR should fix it.](https://github.com/rofrischmann/fela/pull/239)
