### ISSUE TITLE
Fela example with Vuejs?

### ISSUE THREAD

**Issue by rohmanhm** [rofrischmann/fela#225]
[VueJS](github.com/vuejs/vue) is one of the best javascript framework, Will you add fella code depends on VueJS to your example?

**Comment by rofrischmann** [comment]
I've not used Vue yet, so I've got no idea how to quickly implement an example. Would to like to help here? @rohmanhm

**Comment by dustin-H** [comment]
I'm going to try it this week. May I come up with some helpers and/or examples.

**Comment by terehov** [comment]
+1

**Comment by dustin-H** [comment]
Hi there,

I haven't got any lib or something, but here is a little Gist how to use fela in vue.

This works on the client as well as server rendered with nuxt.

https://gist.github.com/dustin-H/7f91815dd422f6d718e1f4e8dc8669c4

Hope this helps anyone for now.

With increasing vue experience I will probably update the gist or create a helper package.

**Comment by dustin-H** [comment]
Hey together,

I just wrote a vue-plugin for using fela with vue. It supports client- and server-rendering.

https://github.com/dustin-H/vue-fela

Would you mind to close this issue now? @rohmanhm 

@rofrischmann May you can add it somewhere in your docs.

Cheers
Dustin

**Comment by jon64digital** [comment]
Excellent work.  :clap::clap::clap:

**Comment by rhadoo200** [comment]
please reopen. i just added an issue about that plugin

**Comment by rofrischmann** [comment]
Well, that's not an issue here I guess. Should go to the vue-fela repo
