### ISSUE TITLE
Is it possible to always pass all properties to underlying component?

### ISSUE THREAD

**Issue by Cowboy-coder** [rofrischmann/fela#227]
**Version**: 4.2.6
**Environment**: Both
**Type**: Feature

-------------------
#### Proposal
I guess this question is very specific for react but I wonder if it's possible to somehow always specify that all props should automatically be passed to the underlying component? Personally I just find it annoying to have to give a list of which props are valid.

For something like this I guess it's fine.
```jsx
const LogoLink = createComponent(() => ({
  background: 'url(logo.png)',
}), Link, ['to']);
<LogoLink to="/home" />
```

But what if you want to do this? How would you even solve that in current system? where there can be an arbitrary amount of props like this:
```jsx
render() {
  const {
    to,
   ...rest,
  } = this.props;
  return (
    <LogoLink to={to} {...rest} />
  );
}
```

First of all maybe I don't really understand the reasoning why you want to be so explicit about props sent to the underlying component so I'm open for clarification on that matter.

But my suggestion (unfortunately breaking change) would be to by default pass all props to the underlying component but if you want to control which props can be sent you have to specify a list of props allowed, even if it means you have to send `[]` if you want to have todays default.

```jsx
// Everything is passed by default to underlying component
createComponent(() => ({}), Link);

// Explicit about not sending anything to the underlying component
createComponent(() => ({}), Link, []);

// Explicit about 'to' only being allowed as prop to underlying component
createComponent(() => ({}), Link, ['to']);
```

What's your opinion on this? :)

**Comment by MioQuispe** [comment]
I like this idea, it looks quite ugly when you gotta do something like this right now for some elements when you'd expect them to work like that out of the box.

`const Img = createComponent(
  props => ({
    maxWidth: `${100}%`,
    height: `${180}px`,
  }),
  'img',
  ['src', 'alt'],
);`

**Comment by rofrischmann** [comment]
In general, I'd love to do that, but you're missing something. Most styling props are not meant to be send to the DOM directly.
e.g.

```javascript
createComponent(props => ({ fontSize: props.fontSize }), 'div')
```

As you know, `fontSize` is not a valid DOM attribute of `div`, React throws the following (sth. like this):

"`fontSize` is not a valid property of `div`"
Not sure if it would cause any harm, but it's good to only have valid attributes anyways. So this is basically the only reason we're doing that.

Anyways, there's a short hack to achieve it:

`createComponent(rule, 'div', p => p)`

The `p => p (props => props)` passes all props to the underlying element. But I warned you! :P

**Comment by Cowboy-coder** [comment]
Aha, thanks for that explanation!

I am curious though if you're still up for discussing other ways to do this. Cause honestly I don't like `createComponent(rule, 'div', p => p)` part at all (sorry!) as that's not very explicit at all what it means.

I need to think more about what my new suggestion would be though :) After some googling my feeling based on https://twitter.com/dan_abramov/status/822526388557250560 and https://facebook.github.io/react/warnings/unknown-prop.html is that we need to figure out a way for `fela` to "consume" the correct props and send the rest of the props to the underlying component.

So in the example of
```jsx
const Title = createComponent(props => ({ fontSize: props.fontSize }), 'div')
<Title fontSize="12px">foo</Title>
```
preferably fela should consume `props.fontSize` and not send that to the underlying component.

However if you do
```jsx
const Title = createComponent(props => ({}), CustomComponent)
<Title fontSize="12px">foo</Title>
```
then preferably fela should pass `fontSize` to the underlying component as fela never "consumes" that property.

Not sure how to solve that though. I think I need to think a bit more about this... :)

**Comment by rofrischmann** [comment]
I had all those thoughts as well, but we can't do any of these as I find them very opinionated. What if you want to pass a prop **and** use it inside a rule? Also filtering (e.g. how styled-components does) is an anti-pattern and would bump the fela package size 2-3x. 

If you don't like the `p => p` why don't you just create your own createComponent abstraction and use that with auto `p => p`?
Without trying to be rude, I am pretty sure not going to change the behavior here.

**Comment by Cowboy-coder** [comment]
> I had all those thoughts as well, but we can't do any of these as I find them very opinionated. What if you want to pass a prop and use it inside a rule? 

True that. Didn't think about that case.

Yeah I'll have to discuss it in our team if we gonna do `p => p` or create an abstraction.

Thanks for the clarifications!
