### ISSUE TITLE
Current selector

### ISSUE THREAD

**Issue by bkniffler** [rofrischmann/fela#233]
Hey,
Coming from a less-css background, I'm used to using .class1 { &.class1 {} } selector resulting in `.class1.class2`, but fela would make it `.class1 .class2`. Is there any possibility to make the first case possible using fela?

**Comment by rofrischmann** [comment]
Do you have a valid use case for that? Don't see why sth. like these selectors should still be used anywhere :P

**Comment by bkniffler** [comment]
Sure, I'm currently trying to mess around with ReactCSSTransitionGroup, which picks up `.enter` and `.leave` classes. There sure are other use cases, but this seems like a common one. So my element has the random class name .` oo3t49f`, and will need a fade transition in / out defined on `.oo3t49f.enter` / `.oo3t49f.leave`. Something like this:

```jsx
const Fade = styled(() => ({
  '&.fade-enter': {
    opacity: 0,
    zIndex: 1,
  },
  '&.fade-enter.fade-enter-active': {
    opacity: 1,
    transition: 'opacity 250ms ease-in',
  },
}), p => (
  <ReactCSSTransitionGroup
    {...p}
    transitionName="fade"
    transitionEnterTimeout={1000}
    transitionLeaveTimeout={1000}/>
), p => p);
```

I don't care about using `&`-syntax. But allowing for something like this would be really cool for animations, especially since I believe defining very simple `ReactCSSTransitionGroup` wrappers that do specific animations (fade, slide-in, etc.) is a great use-case for fela!

**Comment by bkniffler** [comment]
Also

```
const Item = styled(() => ({
  '+:not(:first-child)': {
    borderTop: '1px solid black',
  },
}), 'div', p => p);
```

**Comment by rofrischmann** [comment]
Quite a delay :/ Will check that out tomorrow

**Comment by rofrischmann** [comment]
Still had to time to resolve that yet :( Any suggestions how to solve it without breaking existing APIs?

**Comment by bkniffler** [comment]
I'm sorry, didn't have the opportunity yet to dive into the code. Would my suggestion using a '+' character break existing APIs?

**Comment by rofrischmann** [comment]
I just checked that again and I found that it's not true:

```javascript
      const rule = () => ({
        color: 'red',
        '&.nested': { color: 'blue' }
      })

      const renderer = createRenderer()
      renderer.renderRule(rule)
```

renders the following: 
`.a{color:red}.a.nested{color:blue}`

Guess we can close this then? @bkniffler

**Comment by bkniffler** [comment]
Oh really? Could swearI tried this and of didn't work back then, but seems like I was wrong.. sorry about the fuzz

**Comment by tajo** [comment]
@rofrischmann @bkniffler This doesn't work for me. My output is:

```css
.a {
  color: red
}

.b.nested {
  color: blue
}
```

**Comment by rofrischmann** [comment]
Hmm, Interesting... will check that later

**Comment by rofrischmann** [comment]
Lol, wasn't really awake last time I guess. Of course we get `.b.nested` as we have atomic classes right? But that still works as it gets the `b` className added as well.
