### ISSUE TITLE
fela-monolithic can reuse the same className for different styles

### ISSUE THREAD

**Issue by AugustinLF** [rofrischmann/fela#240]
**Version**: 4.3.2 (tested on master)
**Environment**: Both
**Type**: Bug

-------------------
#### Description
When using [fela-monolithic](https://github.com/rofrischmann/fela/tree/master/packages/fela-monolithic), if you use the same className for two different sets of rules (that can easily happen if you set the className at the root of the style function when using [fela-plugin-extend](https://github.com/rofrischmann/fela/tree/master/packages/fela-plugin-extend)), fela will render the same className for each case, consequently ignoring the styles beyond the first call to the renderer.

While this might to some extent logical, the user should set different names for different styles, it's not mentioned in the doc, and I did spend quite some time to figure the cause of the issue :sweat_smile:

#### Expected Behavior
```javascript
    const rule1 = () => ({
      className: 'custom',
      color: 'red'
    })
    const rule2 = () => ({
      className: 'custom',
      color: 'green'
    })
    const renderer = createRenderer(options)
    const className1 = renderer.renderRule(rule1)
    const className2 = renderer.renderRule(rule2)
    // className1 !== className1
```

#### Actual Behavior
```javascript
    // className1 === className1
```

While this example is obviously a user's mistake (but still, should it fail silently?), this gets less straightforward when using conditions. For instance, this also happens when using extend:
```javascript
const rule = (prop) => ({
    className: 'custom',
    color: 'green',
    extend: {
        condition: prop.red === true,
        style: {color: 'red'},
     }
})
```
If two components depend on rule, they'll end up with the style of the first one created.

I opened a PR #241 with the failing test-case.

**Comment by rofrischmann** [comment]
I am just working on some stuff including this. Wouldn't it be better to throw a warning and go on? I don't think we should "handle" this, because the user explicitely wants `custom` to be the className right?

**Comment by AugustinLF** [comment]
Hmmm, I don't really know. A warning could indeed be sufficient. The confusing part was the error, it does make sense to prevent such thing.

However, what would then be the solution for people needing monolithic and relying on conditionals in their rules? For me it's ok, I wanted monolithic for a better debugging experience, so I just dropped it^^ Another solution would be to add a suffix to such classes.

**Comment by rofrischmann** [comment]
Well we could have sth. added to fela-tools for that. e.g. where the second parameter adds "variations", "options" however you want to call them^^

```javascript 
const rule = (props) => ({
    className: generateUniqueClassName('custom', props),
    color: 'green',
    extend: {
        condition: prop.red === true,
        style: {color: 'red'},
     }
})
```

But I don't see a benefit in adding a prefix or postfix or anything, because then it's not the className you wanted to use (`custom`) but sth. like `custom-sha3i` which is pretty much the same as using pure monolithic with a global selectorPrefix.

Or am I missing sth.?

**Comment by rofrischmann** [comment]
I thought the `className` was only used to apply/overwrite third-party rules? @tajo

**Comment by AugustinLF** [comment]
I confess that I'm not familiar enough with monolithic beyond improving the debugging experience (inspecting the DOM, or things like jest's snapshots). You might be right that for any other other use case, there might not be any solution, and perhaps letting the user handle the problem might be the most efficient.

**Comment by tajo** [comment]
So idea was to use this functionality as a base step allowing to  generate BEM like classNames. Having this custom className property is just a first step. 

## Example `my-input`

There is a script that will take the input component, its default props and runs `renderRule` with monolithic and custom className `.my-input`.

The same script now will loop through all possible variations of props (ofc there should be some exception for numerical props or non-enum props), runs `renderRule`, compares the output with the default props run and saves the diff into `.my-input--invalid` (invalid is the name of changed prop).

**Next iterations:**
```
.my-input--disabled
.my-input--small
.my-input--large
...
```

The script doesn't exist yet but I think it should work. Why to generate this BEM like output? Imagine you are building an UI library but there are some projects that don't use JavaScript and they would like to reuse the styles.

----
Note: I don't think that the current implementation actually prevents this use-case.

**Comment by AugustinLF** [comment]
@tajo That does sound ideal. How would you handle multiple prop changes? Working with the props changes (as you suggest) should work for most cases, and there could be a warning when simply two different components use the same className (which would likely be a user mistake), as suggested earlier by @rofrischmann.

**Comment by rofrischmann** [comment]
I have added a warning for now, that the className prop should not be used with different styles. Will be released with the new `prettySelectors` support soon. Also @tajo I think the prettySelectors implementation might be a good use to make Fela classNames BEM without some script :P
