### ISSUE TITLE
Pass props to keyframes?

### ISSUE THREAD

**Issue by cryptoquick** [rofrischmann/fela#243]
How would I go about passing props to keyframes? Like this?

```javascript
const frames = ({color}) => ({
  '0%': {
    background: color,
    transform: 'scale(1.0)'
  },
  '20%': {
    background: color,
    transform: 'scale(1.3)'
  },
  '35%': {
    background: color,
    transform: 'scale(1.0)'
  },
  '50%': {
    background: color,
    transform: 'scale(1.3)'
  },
  '100%': {
    background: color,
    transform: 'scale(1.0)'
  },
})
```

Versions:
Fela 4.3.2
Preact-Fela 4.3.2
Preact 8.1.0

Environment: DOM

**Comment by queckezz** [comment]
as per [docs](http://fela.js.org/docs/basics/Keyframes.html) this is the way to do it.

Here's a codepen with a short example:
  https://codepen.io/queckezz/pen/qmaamY

**Comment by rofrischmann** [comment]
Guess this one is solved? Reopen if there are still questions :)
