### ISSUE TITLE
Using fela to style components that conditionally apply classes

### ISSUE THREAD

**Issue by codepunkt** [rofrischmann/fela#244]
`react-router`'s &lt;Link&gt; component and `react-sticky`'s &lt;Sticky&gt; component - amongst others - accept additional classNames via separate properties and apply those classNames when the component is in a certain state - e.g. &lt;Link&gt; accepts `activeClassName` and &lt;Sticky&gt; accepts `stickyClassName`.

It would be great to have a way to style these using `fela`.

As a reference: The same discussion was held in a [styled-components issue](https://github.com/styled-components/styled-components/issues/184), which resulted in a few solutions and modules such as [styled-property](https://github.com/codepunkt/styled-property).

I have resolved this using a similar approach for fela:

```javascript
import { NavLink } from 'react-router-dom'
import { createComponent } from 'react-fela'

// hoc helper
const createConditionallyStyledComponent = (
  rule,
  Type,
  propertyName,
  passThroughProps
) => {
  return createComponent(
    rule,
    ({ className, ...props }) => {
      props[propertyName] = className
      return <Type {...props} />
    },
    passThroughProps
  )
}

// usage
const StyledNavLink = createConditionallyStyledComponent(
  () => ({
    color: '#f00',
  }),
  NavLink,
  'activeClassName',
  [ 'exact', 'to' ]
)
```

Is this already possible some other way?
If it's not, i could publish a small module that does this. Not sure about the naming though. Any thoughts?

**Comment by codepunkt** [comment]
I've discovered that this is not a good solution. Once combined with other styles, either by descendant selectors in parent components styles or styles that you want to have on the component regardless of the specified class being set or not, things break.

#### Example 1

Default styling and styling that is applied when the component sets the specified className. Link should not have a text decoration and be red when active:

```javascript
const StyledNavLink = createConditionallyStyledComponent(
  () => ({
    color: '#f00',
  }),
  createComponent(() => ({ textDecoration: 'none' }), NavLink, [ 'exact', 'to' ]),
  'activeClassName',
  [ 'exact', 'to' ]
)
```

#### Example 2

Descendant selector in parent component:

```javascript
const StyledNavLink = createConditionallyStyledComponent(
  () => ({
    color: '#f00',
  }),
  NavLink,
  'activeClassName',
  [ 'exact', 'to' ]
)

const MenuItem = createComponent(
  () => ({
    '> a': { textDecoration: 'none' },
  }),
  'li'
)

const MyComponent = () => (
  <ul>
    <MenuItem><StyledNavLink to="/" exact>Home</StyledNavLink ></MenuItem>
    <MenuItem><StyledNavLink to="/wat">Wat</StyledNavLink ></MenuItem>
  </ul>
)
```

Not sure how to handle this 😕

**Comment by tajo** [comment]
This could work in Fela too: https://github.com/styled-components/styled-components/issues/184#issuecomment-284300950

**Comment by rofrischmann** [comment]
Have you ever thought about using the `connect` API which react-fela provides? This seems quite a valid use case here. I am doing this myself with <Link> and other components from third-party libraries :P

**Comment by rofrischmann** [comment]
@codepunkt Sth. to be closed? We might open a follow-up issue to add sth. to the docs for third-party components. I highly appreciate PRs these days :)

**Comment by codepunkt** [comment]
@rofrischmann
Thanks! I didn't know about the `connect` API of react-fela. Putting it to good use, my use case is solved.

My solution seems a bit convoluted, though:

```javascript
// styleProp.js
import React from 'react'
import { connect } from 'react-fela'

export default (propName, rule) =>
  Component =>
    connect(props =>
      renderer => ({
        [propName]: renderer.renderRule(rule, props),
      }))(({ styles, ...rest }) => (
        <Component {...rest} {...{ [propName]: styles[propName] }} />
    ))
```

```javascript
// MyComponent.js
import React from 'react'
import { NavLink } from 'react-router-dom'
import styleProp from './styleProp'

const StyledLink = styleProp('activeClassName', props => ({
  color: '#bada55',
  ':hover': {
    color: props.color,
  },
}))(NavLink)

export default () => (
  <ul>
    <li>
      <StyledLink exact to='/' color='papayaWhip'>Home</StyledLink>
    </li>
  </ul>
)
```

What do you think?
