### ISSUE TITLE
How to use with Jest

### ISSUE THREAD

**Issue by blackxored** [rofrischmann/fela#247]
My apologies if this has been answered before, or I'm missing the obvious, or both. I've yet to find any reference to this in the docs, but I wonder how to use Jest snapshot testing with components that use Fela (i.e `createComponent(...)`. Wrapping the whole thing in a provider seems like a bad idea and might make tests too brittle IMHO, so I wonder which solutions are you guys aware of?

**Comment by tajo** [comment]
Why would that be brittle?

We do shallow render snapshots [here](https://github.com/cloudflare/cf-ui/blob/master/packages/cf-component-heading/test/Heading.js#L8) and full integration snapshots with JSDom [here](https://github.com/cloudflare/cf-ui/blob/master/packages/cf-style-provider/test/index.js#L17).

**Comment by rofrischmann** [comment]
Hope the answer helped, will close this for now. Feel free to reopen if there are still questions :)

**Comment by blackxored** [comment]
Thanks for the answer. So in the case we can't someone provide some magic
your example does work. I wonder if we can expose that felaTestContext as
part of react-fella?

—
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by derek-duncan** [comment]
For anyone looking for better shallow rendering with enzyme (or similar), you can pass a `context` option to enzyme's `shallow` render function. Just pass your renderer and theme there. That way, your shallow rendering is not polluted with the `<Provider>` and `<ThemeProvider>` wrappers.

Here's a sample wrapper around enzyme's `shallow`.

```
import { shallow }. from 'enzyme';
import { createRenderer } from 'fela';

const theme = {};
const renderer = createRenderer();

const felaShallow = (node, options = {}) => shallow(
  node,
  {
    context: {
      theme: theme,
      renderer: renderer,
    },
    ...options,
  }
);

export default felaShallow;
```

**Comment by rofrischmann** [comment]
Should add that to the docs somewhere, maybe a new item in advanced, "Testing Fela Components"

**Comment by tajo** [comment]
Btw, @steida has a great idea to create additional Jest snapshots out of `renderer.renderToString()`, no need to do full rendering with JSDom in order to see generated CSS

I'm going to definitely use it as well

**Comment by steida** [comment]
https://github.com/este/este/blob/next/test/components/box.test.js

**Comment by kang-chen** [comment]
can't seem to get this working with themed components.

Have tried passing through context with @derek-duncan 's example and also example in http://fela.js.org/docs/recipes/TestingFelaComponents.html

'theme' always seems to be undefined. Works fine with ThemeProvider wrapped although I prefer not to wrap all themed components.

**Comment by derek-duncan** [comment]
Here's the code I'm using for wrapping enzyme's `shallow` method:

```javascript
import * as PropTypes from 'prop-types';
import { shallow as enzymeShallow } from 'enzyme';
import { createRenderer } from 'fela';
import { createTheme } from 'fela-bindings';

const theme = {/* my theme here */};

const shallow = (node, options = {}) => {
  const renderer = createRenderer();
  const wrapper = enzymeMount(node, {
    childContextTypes: {
      renderer: PropTypes.object,
      theme: PropTypes.object,
    },
    context: {
      renderer: renderer,
      theme: createTheme(theme),
    },
    ...options,
  });

  return wrapper;
};

export default shallow;
```

**Comment by kang-chen** [comment]
@derek-duncan thanks for the snippet, I'll give it a go.

Also found this: https://github.com/styled-components/styled-components/issues/624 same issue in styled components. Basically concluding passing theme via props might be the most straight forward approach.
