### ISSUE TITLE
Simulate Option

### ISSUE THREAD

**Issue by limscoder** [rofrischmann/fela#261]
**Version**: 3.0.x
**Environment**: Both
**Type**: Feature

-------------------
#### Description
Option for pseudo selectors and media query debugging.

#### Proposal

Add simulate parameter for debugging pseudo selector and media selector styles.

Similar to glamor's `simulate`: https://github.com/threepointone/glamor/blob/master/docs/api.md#simulatepseudoclasses

**Code Example**:
```javascript
renderer.renderRule(rule, {}, {
  ':hover': true,
  '@media (min-height: 300px)': false
});
```

```javascript
const StyledDiv = createComponent(() => {});
const pseudoState = {
  ':hover': true,
  '@media (min-height: 300px)': false
};

<StyleDiv simulate={ pseudoState } />;
```

**Comment by rofrischmann** [comment]
This will fit perfectly as a plugin. I happily accept an PR and can also give some instructions on how to built it if you want to @limscoder

**Comment by limscoder** [comment]
Ok. My team is currently spiking react-fela vs glamorous. If we pick fela, we'll investigate writing a plugin.

**Comment by rofrischmann** [comment]
Ping me if you need any advice :)

**Comment by rofrischmann** [comment]
ships with #292
