### ISSUE TITLE
Improvement for combineRules (component displayName)

### ISSUE THREAD

**Issue by wcastand** [rofrischmann/fela#266]
**Version**:
- fela: 4.3.2
- fela-plugin-extend: 4.3.2
- fela-plugin-fallback-value: 4.3.2
- fela-plugin-lvha: 4.3.2
- fela-plugin-named-media-query: 4.3.2
- fela-plugin-prefixer: 4.3.2
- fela-plugin-unit: 4.3.2

**Environment**: Both
**Type**: Bug / Feature

-------------------
#### Description

I used combineRules for some of my components. When i try to use them on storybook with the plugin i created `storybook-addon-jsx` which display in a panel the JSX of the component, the component is named FelaComponent. I think it's because `combineRules` is an anonymous function so fela put displayName to 'FelaComponent'.
[line 15](https://github.com/rofrischmann/fela/blob/master/packages/fela/src/bindings/createComponentFactory.js)

It would be nice if we can use the const name as a name for the component.

```javascript
const BoxRow = combineRules(Box, Row)

export default createComponent(BoxRow, 'div') 
// displayName would be BoxRow instead of FelaComponent
```

**Comment by rofrischmann** [comment]
Would love to accept an PR here. I am not pretty sure how to do that without a babel-plugin or sth. equivalent. But I am more than happy to accept any PR's that improve DX.

btw. you could do the following right now:
```javascript
const Row = createComponent(() => ({...}))
const Box = createComponent(() => ({...}), Row)
```

**Comment by wcastand** [comment]
I was on gitter earlier and we discuss about the fact that it would be nice to find a way to avoid declaring variable for declaring propTypes or even being able to use combineRules without loosing name in components.

I'm not sure i know how to correct this problem. But i'm totaly up for the challenge and to discuss about a solution. I think a babel plugin could be the solution, but in that case, i think, it's not really related to fela ?

It would be nice anyway and could be suggested for people who needs a correct naming of their components.

If you think that's the best solution, i can look into it even if i'm not familiar with babel plugin :) (maybe the plugin exist already on npm :) )

**Comment by wcastand** [comment]
I don't know if that can work for all cases, but it worked on my project. I used this babel plugin : 
[babel-plugin-display-name-custom](https://www.npmjs.com/package/babel-plugin-display-name-custom)

with this config in my .babelrc : 
```
 [
            "display-name-custom",
            {
                "modules": {
                    "react-fela": {
                        "createComponent": true,
                        "combineRules": true
                    }
                }
            }
        ],
```

**Comment by rofrischmann** [comment]
The problem is, that combineRules does not return a component, but a rule itself which can't be assigned a displayName properly. Would I thought about is adding a options parameter to createComponent, but I feel like that gets too verbose. Maybe we need a clean wrapper e.g.

```javascript
export default displayName('Column')(createComponent(() => ({ ...})))
```

**Comment by wcastand** [comment]
Yeah, i thought about this problem for combineRules.

The wrapper could be a good thing, but i find it too verbose.
A combination of the babel transform for createComponent and a third parameter for combineRules wouldn't be a possibility ?

**Comment by rofrischmann** [comment]
combineRules accepts infinite arguments (rules) to combine. Also I don't see why it should be in the scope of combineRules as it's a React/displayName issue and has nothing todo with combineRules at all. I'm not even sure if it's even possible in every browser. guess the displayName HoC would be the best way for now...

**Comment by rofrischmann** [comment]
We should have another doc update and add some info about the react-with-display-name package that helps here. if you'd want to do that, I'll happily merge your PR - otherwise I'll do that some day :P
