### ISSUE TITLE
wrong css order

### ISSUE THREAD

**Issue by tuchk4** [rofrischmann/fela#270]
https://tuchk4.github.io/css-in-js-app/#/react-fela

click "Render different components"

There are should not be components with black border

![image](https://cloud.githubusercontent.com/assets/5140611/26532423/f72cd9d6-4408-11e7-9234-2f88a146b7fc.png)

Source here:
- https://github.com/tuchk4/css-in-js-app/blob/master/src/scenes/Fela/DifferentBlocks.js
- https://github.com/tuchk4/css-in-js-app/blob/master/src/scenes/Fela/Block.js

**Comment by rofrischmann** [comment]
Hey @tuchk4, check out http://fela.js.org/docs/introduction/Drawbacks.html (2.) With atomic CSS you're should not mix shorthand and longhand properties. Try to use `borderStyle`, `borderWidth` and `borderColor` instead of `border` and `borderColor` and it should work :)

**Comment by tuchk4** [comment]
@rofrischmann Thank! Will fix style and re-deploy app
