### ISSUE TITLE
Docs: Useful displayNames with HoC

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#275]
This is the follow-up issue for https://github.com/rofrischmann/fela/issues/266

**Comment by wcastand** [comment]
Where do you want to put that ?
In FAQ or in combineRules docs ?
it would be good in combineRules docs but the docs would apply to createComponent too.

**Comment by rofrischmann** [comment]
Again, it has nothing to do with combineRules :P But we could have a side-link to that maybe. also the createComponent should reference somehow, but In general I thought about putting it here: http://fela.js.org/docs/advanced/DeveloperExperience.html or add it as a new Recipe here: http://fela.js.org/docs/Recipes.html

**Comment by rofrischmann** [comment]
Actually we could remove the DX page completely and create 2 separate recipes. I guess recipes is a great section to put any useful patterns

**Comment by wcastand** [comment]
Make recipes and remove Dx seems like a good idea :)

**Comment by rofrischmann** [comment]
We might also want to point to: https://github.com/acdlite/recompose/blob/master/docs/API.md#setdisplayname since recompose is a very well known utility toolset :)
