### ISSUE TITLE
Animations in 5.x

### ISSUE THREAD

**Issue by kompot** [rofrischmann/fela#289]
**Version**: 5.0.0
**Environment**: Dom
**Type**: Docs / General

-------------------
#### Description
In preact example
https://github.com/rofrischmann/fela/blob/master/packages/example-preact/components/Header.js
I see animation example that uses `mapStyleToProps` that had been deprecated in 5.x.
Could you please provide an example how to use animation with `rules` object instead of `mapStyleToProps` function. Could not get it running (leaving `mapStyleToProps` for now).

**Comment by rofrischmann** [comment]
There are basically 2 ways to achieve that. Maybe we will have to point to that somehow within a recipe or sth. 

1. using fela-plugin-embedded

You can now embed your keyframes definition within your rules using this plugin. The `animationName` property will be transformed to a keyframe automatically. This also works with `fontFamily`: { FONTFACE } btw.
```javascript
// if not using props, you can even leave your keyframe a simple object and just pass it as `animationName` value.
const keyframe = () = ({
    from: { color: 'red' },
    to: { color: 'blue' }
})

connect({
  rule: (props) => ({
    color: 'red',
    animationName: keyframe(props),
    animationDuration: ...
  })
})(Comp)
```

2. using the 2. parameter of rules
> Yeah, I know - this is still undocumented, but truely powerful.

```javascript
const keyframe = () = ({
    from: { color: 'red' },
    to: { color: 'blue' }
})

const rule = (props, renderer) => ({
  color: 'red',
  animationName: renderer.renderKeyframe(keyframe),
  ...
})
```

**Comment by kompot** [comment]
Great, thanks for support, new API looks really neat.
