### ISSUE TITLE
Leverage iamstarkov/theming for Component Theming

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#302]
https://github.com/iamstarkov/theming

Right now, this would only work for React, but we might get it to work with Preact and Inferno shortly after.

**Comment by iamstarkov** [comment]
let me know if you need any help, (besides bindings, lets discuss it in relevant https://github.com/iamstarkov/theming/issues/11)

**Comment by rofrischmann** [comment]
This is marked as blocked. @iamstarkov Do you ever plan to extract abstract bindings? If not, Ill probably close this and simply continue using the current implementation

**Comment by iamstarkov** [comment]
@rofrischmann i'd like to abstract it, once i have time and will gain expertise how to do that. Can you help me with pull-request?

**Comment by rofrischmann** [comment]
Sure I can help with that! We might connect via Gitter? Otherwise it'd take some time as I am pretty busy atm.

**Comment by iamstarkov** [comment]
@rofrischmann sure, i would like to chat. can you ping me on gitter?

**Comment by veeramarni** [comment]
How it is going with it, looks interesting to me.
