### ISSUE TITLE
Move Inferno to peerDependencies

### ISSUE THREAD

**Issue by oleksiibilous** [rofrischmann/fela#309]
**Version**: latest
**Environment**: Both
**Type**: Infrastructure

-------------------
#### Description
Hi. Can you move `inferno`, `inferno-component` & `inferno-create-element` to `peerDependencies` please? Thanks

**Comment by rofrischmann** [comment]
Feel free to send a PR, got no time atm. 
If you want to add em as peerDeps, make sure to also add them as devDeps or our lerna build will fail, thanks.
