### ISSUE TITLE
Class name: blank space when rule has an empty value

### ISSUE THREAD

**Issue by eliseumds** [rofrischmann/fela#311]
**Version**: 5.0.2
**Environment**: Both
**Type**: Bug

-------------------
#### Description

White spaces are appended to the class names string when values are empty.

#### Steps to reproduce
1. Create a ruleset and pass some empty values (`'' | null | undefined`):

```js
{
  color: props.someInexistingProp,
  backgroundColor: 'red'
}
```

#### Expected Behavior
```html
<div class="b">Test</div>
```

#### Actual Behavior
```html
<div class=" b">Test</div>
```

#### Proposal

There renderer could bypass the *classNames* concatenation when no class name is generated at https://github.com/rofrischmann/fela/blob/master/packages/fela/src/createRenderer.js#L267:

```javascript
if (renderer.cache[declarationReference]) {
  classNames += ' ' + renderer.cache[declarationReference];
}
```

**Comment by rofrischmann** [comment]
Yeah, it's actually not a problem, but to minimize markup, we could probably check that. Thanks :)
