### ISSUE TITLE
Original component's static methods are not available when using connect

### ISSUE THREAD

**Issue by Lepozepo** [rofrischmann/fela#312]
**Version**: 5.0.0
**Environment**: DOM
**Type**: Bug

-------------------
#### Description
As a developer I need access to the original component's static methods

#### Steps to reproduce
1. Make a component with `propTypes`
2. Wrap it in `connect`
3. `console.log` your connected component's `propTypes`

#### Expected Behavior
A connected component should have all original static methods assigned

#### Actual Behavior
A connected component does not have all original static methods assigned

## NOTES
I already fixed it, I'll send the PR in a bit for review

**Comment by rofrischmann** [comment]
not really relevant I guess. should not style comps with statics anyways
