### ISSUE TITLE
inferno-fela: Uncaught TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by oleksiibilous** [rofrischmann/fela#315]
**Version**: 5.0.2
**Environment**: DOM 
**Type**: Bug 

#### Description

I'm getting the error while trying to reproduce  [Composition](http://fela.js.org/docs/guides/UsageWithReact.html) example  with the latest `inferno` and `fela` versions

```
index.js:347 Uncaught TypeError: Cannot read property 'bind' of undefined
    at createReactCompositeComponent (index.js:347)
    at updateReactComponent (index.js:250)
    at createReactCompositeComponent (index.js:341)
    at updateReactComponent (index.js:250)
    at Object.componentAdded (index.js:163)
    at inferno.options.afterMount (index.js:468)
    at eval (index.js:2171)
    at Lifecycle.trigger (index.js:84)
    at Object.render (index.js:1128)
    at render (index.js:75)
``` 

`component.js`

```
import { createComponent } from 'inferno-fela'

const a = () => ({ backgroundColor: 'black' })

const b = () => ({ color: 'white' })

const A = createComponent(a)
const B = createComponent(b, A)

const MODULE = () => <B>{'test'}</B>

export default MODULE
```

`index.js`

```
const render = (container) => {
  Inferno.render(
    <Redux store={store}>
      <Fela renderer={styler}>
        <PageHome/>
      </Fela>
    </Redux>,
    document.getElementById('app')
  )
}
```

**Comment by oleksiibilous** [comment]
@tajo

> My original reason for the fork was to prevent createComponent(createComponent(...)) since I believe it's an anti-pattern (there are much better ways how to combine styles if necessary)

Can that be the reason? Then what is the better way to combine styles?

**Comment by tajo** [comment]
^ Looks like a bug to me. I'll look into it later.

> Can that be the reason?

I don't think that's the reason.

> Then what is the better way to combine styles?

http://fela.js.org/docs/api/fela/combineRules.html

**Comment by oleksiibilous** [comment]
Probably relative to this issue. I get this error on HMR

```
index.js:16 Uncaught (in promise) TypeError: Cannot read property 'prototype' of undefined
    at isStatefulComponent (index.js:16)
    at createVNode (index.js:2410)
    at eval (index.js:93)
    at eval (index.js:94)
    at Object.hotApply [as apply] (index.js:567)
    at cb (process-update.js:52)
    at eval (process-update.js:68)
    at <anonymous>
```

I've started to get it after migrating from `styled-components` to `fela`

**Comment by rofrischmann** [comment]
Hmm. I am sadly not really familiar with Inferno's internal Component structure. Thought it'd mimic the React way and therefore just work as expected. Not sure where this issue comes from. Any help/suggestions are really appreciated.

**Comment by rofrischmann** [comment]
@oleksiibilous Does this only happen if you use createComponent with another "createComponent"-component?

**Comment by rofrischmann** [comment]
Could you provide a simple debugable example somehow? I basically got no time to set one up, but would like to hack it a bit.

**Comment by oleksiibilous** [comment]
Sure, will do later today

**Comment by oleksiibilous** [comment]
You know what? I cannot reproduce it anymore. It was a kind of blocker for me, so I switched to `inferno-compat` & `react-fela`. There where several `inferno` releases after. Probably one of them fixed the problem. However, I reproduced the issue with the HMR. It is rather annoying than critical. Maybe you can suggest what is wrong

Here is the code: https://github.com/oleksiibilous/example-fela-hmr

1. After running `yarn && yarn serve` open `localhost:8000` in your browser
2. Open console logs and you will see no errors
3. Go to `src/components/home.js` and change any rule
4. Go to the browser and wait before the page will be automatically updated
5. Then you should see the error

Let me know if you couldn't reproduce it. I'll make a screencast for you

**Comment by rofrischmann** [comment]
Hmm. I tried to reproduce that last one as well, but I can't. Seems to work just fine for me?
