### ISSUE TITLE
[Question] use fela with redux

### ISSUE THREAD

**Issue by saeedjalali1** [rofrischmann/fela#318]
**Version**: 5.0.2
**Environment**: Both
**Type**:Docs / General

-------------------
#### Description

First thanks for awesome packages. I want to using your packages for dynamically change the app style. On the other hand we need Redux for manage the state of the app. in Redux for the root component use `Provider`. Also in your packages I see `Provider` for the root of application. Is there a way to use your packages with Redux?

#### Expected Behavior
```javascript
// your code here
```

#### Actual Behavior
```javascript
// your code here
```

#### Proposal

**Code Example**:
```javascript
// redux example
    import React from 'react'
    import { render } from 'react-dom'
    import { Provider } from 'react-redux'
    import { createStore } from 'redux'
    import todoApp from './reducers'
    import App from './components/App'

    let store = createStore(todoApp)

    render(
       <Provider store={store}>
           <App />
       </Provider>,
       document.getElementById('root')
    )
```

**Comment by AugustinLF** [comment]
With ES2015 imports, you can rename your imports, so you can do something like that:
```javascript
   import React from 'react'
    import { render } from 'react-dom'
    import { Provider as ReduxProvider } from 'react-redux'
    import { Provider as FelaProvider } from 'react-fela'
    import { createStore } from 'redux'
    import todoApp from './reducers'
    import App from './components/App'

    let store = createStore(todoApp)

    render(
       <ReduxProvider store={store}>
           <FelaProvider>
               <App />
           </FelaProvider>
       </ReduxProvider>,
       document.getElementById('root')
    )
```

**Comment by HugoGiraudel** [comment]
That is indeed the way to go.

**Comment by Enalmada** [comment]
Redux is common enough that it might be a good idea to update the examples with this to avoid any chance of confusion.  As a new user, I put renderer={renderer} right into my react-redux provider feeling like I was following the example.
