### ISSUE TITLE
createComponent should pass defaultProps

### ISSUE THREAD

**Issue by wyuenho** [rofrischmann/fela#321]
**Version**: 5.0.x
**Environment**: DOM
**Type**: Bug / Feature

-------------------
#### Description
It seems that `createComponent` doesn't pass thru default props, even when whitelisted in its `passThrough` argument.

#### Steps to reproduce
```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import PropTypes from 'prop-types';
import { createRenderer } from 'fela';
import { render } from 'fela-dom';
import { createComponent, Provider as RendererProvider, ThemeProvider } from 'react-fela';

const styles = (props) => {
  console.log(props); // nothing but theme
  return {
    // results in a yellow background
    backgroundColor: props.valueWithDefault ? props.theme.backgroundColor : 'yellow'
  };
};

class Container extends React.Component {
  render() {
    return (
      <div className={this.props.className}>
        {this.props.valueWithDefault}
        <br />
        {this.props.value}
      </div>
    );
  }
}

Container.propTypes = {
  valueWithDefault: PropTypes.string,
  value: PropTypes.string
};

Container.defaultProps = {
  valueWithDefault: 'default'
};

// declare that all the props of the Container is to be passed thru
const StyledContainer = createComponent(styles, Container, Object.keys(Container.propTypes));

const renderer = createRenderer();

const theme = {
  backgroundColor: 'red'
};

const App = () => (
  <RendererProvider renderer={renderer}>
    <ThemeProvider theme={theme}>
      <StyledContainer /> // should set default props and pass down to style function, but doesn't
    </ThemeProvider>
  </RendererProvider>
);

ReactDOM.render(<App />, document.body);
```

#### Expected Behavior
The default prop values are passed down to the style function

#### Actual Behavior
They don't.

#### Proposal
`createComponentFactory` does not appear to have any logic to handle default props other than relying on `createElement` to handle default props. So the style functions do not get any default value passed down. Some logic to handle that must be added.

https://github.com/rofrischmann/fela/blob/master/packages/fela/src/bindings/createComponentFactory.js

**Comment by rofrischmann** [comment]
I am actually not sure if this is something we should add to the bindings. Not that it's not a missing feature, but I feel like there're more cases we're missing here. Will investigate on that later. For now a good fix would be to switch to a Function component that defines the default props using the default parameters. e.g. 

```javascript
const Container = ({ 
  className, 
  valueWithDefault = 'default', 
  value 
}) => (
  <div className={className}>
    {valueWithDefault}
    <br />
    {value}
  </div>
)
```

**Comment by wyuenho** [comment]
But the problem is the style function doesn't get the default props, not the component itself?
