### ISSUE TITLE
react-fela missing TS definition for 'connect'

### ISSUE THREAD

**Issue by AnotherHermit** [rofrischmann/fela#325]
react-fela
**Version**: 5.1.1
**Environment**: Both
**Type**: Bug

-------------------
#### Description
Typescript definition for "connect" seems to be missing. 
My reason for using connect is to access the fela renderer for animations. Code works as expected but it would be great if I could get rid of the error message.

#### Steps to reproduce
1. `import { connect } from 'react-fela'`
2. compilation reports error TS2305: Module '"react-fela"' has no exported member 'connect'.

**Comment by rofrischmann** [comment]
Hey there.
Feel free to send a PR. I am not using TS and therefore do not need this specifically. Btw. You do not need to use the connect API to render animations.

You can either use the fela-plugin-embedded to directly embed animations in style objects or use the second parameter of rule to render it inside a rule e.g.

`const rule = (props, renderer) => ({ animationName: renderer.renderKeyframe(...) })`

**Comment by AnotherHermit** [comment]
Thank you for your reply. I just started using TS so I am not confident I could send a PR just yet, but I will try your other suggestions!

**Comment by rofrischmann** [comment]
Ok. I will close this one. Feel free to add it any time later :)
