### ISSUE TITLE
Multiple keyframe animations on same element?

### ISSUE THREAD

**Issue by lucasmotta** [rofrischmann/fela#327]
**Version**: 5.0.x
**Environment**: Both
**Type**: Bug

-------------------
#### Description
When trying to create multiple keyframe animations on the same element, it does not work as expected:

```js
const color = () => ({
  "0%": { color: "red" },
  "100%": { color: "blue" }
});

const bg = () => ({
  "0%": { backgroundColor: "yellow" },
  "100%": { backgroundColor: "red" }
});

const Title = createComponent(() => ({
  fontSize: "48px",
  animationDuration: "1s",
  animationIterationCount: "infinite",
  animationDirection: "alternate",
  animationName: color()
  /* the following does not work */
  // animationName: `${color()}, ${bg()}`
  // animationName: [color(), bg()]
}));
```

You can also have a look at [live preview of this example](https://codesandbox.io/s/5WK5ZwDv)

I would expect that using multiple animations would work, either by using the string interpolation or an array of animations. Is there any way to achieve this that I am not aware of?

**Comment by rofrischmann** [comment]
Thanks for the issue! That's something we must enable inside `fela-plugin-embedded`. I can take a look at it soon, but I am currently pretty busy.
