### ISSUE TITLE
Add support for '@supports'

### ISSUE THREAD

**Issue by TxHawks** [rofrischmann/fela#328]
**Version**: Irrelevant
**Environment**: Both
**Type**: Feature

-------------------
#### Description
Great work on this. I'm very excited about Fela.

While using Fela, I found myself wishing for support of the `@supports` at-rule several times, probably through the `fela-plugin-fallback-value` plugin. It can be very useful for progressive enhancement scenarios, especially with things like css-grid-layout, where you often need to reset values that are not themselves unsupported by the browser. `@supports` doesn't increase specificity, so order is important.

#### Proposal
 
I'd suggest something like the following api:

**Code Example**:
Input:
```javascript
{
  // The next line is okay, will fallback to `flexbox` if `grid` isn't supported, 
  //and than to `block` if `flexbox` isn't supported.
  display: ['block', 'flexbox', 'grid'] ,
  gridTemplateColumns: '1fr minmax(auto, 80em) 1fr',
  // The order here is crucial, since the '@supports (display: grid)' ruleset must 
  // appear after the 'width: 800' rule in the cascade.
  width: ['800px', { '@supports (display: grid)': { width: 'auto' }}],
}
```

**Comment by rofrischmann** [comment]
Is it a solid feature such as `@media` so we can simply "allow" the syntax and pure CSS does its job? Because that would be pretty straight-forward.
(I've never used and will never use fallback-stuff like that, so I don't know really that feature)

**Comment by TxHawks** [comment]
It is. See [@supports on MDN](https://developer.mozilla.org/en/docs/Web/CSS/@supports)

**Comment by lucasmotta** [comment]
Yeah we've been using `@supports` to check for the `position: sticky` support. At the moment, we have been using JavaScript `CSS.supports()` to check if it supports sticky, but obviously on the server-side this won't work.

So it would be nice to 'support' `@supports` just like `@media`, with no magic happening behind the scenes.

**Comment by TxHawks** [comment]
Well, like I indicated in the original, some "magic" is needed, because order is important. Unlike with `position: sticky`, you sometimes have to override properties that are actually supported by the browser because another feature is supported (e.g., in the case of `display: grid`), so order is important.
So the only "magic" needed is ensuring order through `fela-plugin-fallback-value`.

**Comment by rofrischmann** [comment]
Am going to add that asap. The order stuff is something the dev should correctly handle I guess.

**Comment by TxHawks** [comment]
Thanks! Much appreciated.

I do have to ask, since order cannot be guaranteed, how *can* the dev ensure order in the use case I provided?

**Comment by lucasmotta** [comment]
@TxHawks I would say mainly by moving the `supports` to be rendered last? Most of the usage for `@supports` is for enhancement, so very likely you would want your normal styles first, then your "enhancement" after. How does that sound?

**Comment by TxHawks** [comment]
@lucasmotta -
I guess having the `@support` blocks rendered at the end is okay for most use cases, but would not cater to some edge cases, say when you want to enhance for browsers supporting `flexbox` and then for browsers supporting `grid`. Order would then be important between the two `support` blocks.

That's not so.ething I can see myself doing, but have seen css like that before.

At any rate, keeping `@support` blocks at the end of the stylesheet is not something the developer can do, Delay would have to take care of it being the scenes

**Comment by rofrischmann** [comment]
Of course, Fela will render `@support` rules after basic & pseudo styles. The same applies for styles within media queries.
But we cannot enforce order for different `@support` rules. Taking your example, you as the dev would have to use the flexbox check before the grid check.
Will try to make a simple PR soon.

**Comment by TxHawks** [comment]
@rofrischmann 
Do you have any estimation in regards to when this will be implemented? I understand there are lots of other things going on, so not trying to be rude or demanding in any way, just figure out where this is at.

Thanks for all your great work

**Comment by rofrischmann** [comment]
Heyhey,

I've tried to add a simple one already, but it's not as simple as I thought if you want to make it "right".
But we could go with a simpler version first (CSS output would not be perfect, but it'd work for now)

**Comment by TxHawks** [comment]
Just out of pure curiosity, what do you mean by "right" and I what sense will CSS output not be perfect?

**Comment by rofrischmann** [comment]
We could have single @support ... rules pretty easy, but the same support-rule could be used quite often e.g.

```
@supports (display: grid) {
  .a { display: grid }
}

@supports (display: grid) {
  .b { color: red }
}

@supports (display: grid) {
  .c { font-size: 12px }
}
```

But the more efficient way (smaller output etc.) would ofc be:
```
@supports (display: grid) {
  .a { display: grid }
  .b { color: red }
  .c { font-size: 12px }
}
```

Actually thats not as easy as it sounds like, as Fela is build with performance and size in mind and has some "ugly" abstraction for media queries / pseudo classes. Adding @supports will be possible with some refactoring if we still want to stay performant at any time.

The first example could just be added to the current model :P

**Comment by TxHawks** [comment]
There is also the complexity of mixed `@media` and `@supports`, or would that be handled by the existing pseudo and media  abstractions handle it?

**Comment by rofrischmann** [comment]
Yeah that would be handled as well (like the first example though). Guess it's ok for now, but well have to improve that later on. But I rarely find some free time atm. Will try to check back later this week.

**Comment by TxHawks** [comment]
Thanks!
I totally get being short of time. I'd offer to try and contribute a pull request if I didn't have my own hands so full at the moment.

**Comment by rofrischmann** [comment]
Ok. Now that #363 is done, adding support for `@support` got much easier.

**Comment by TxHawks** [comment]
I guess that should really be answered from a performance point of view. Benchmarking is probably in order
