### ISSUE TITLE
innerRef shouldn't be passed down with createComponentProxy

### ISSUE THREAD

**Issue by wcastand** [rofrischmann/fela#331]
**Version**: 5.x.x
**Environment**: Both
**Type**: Bug

-------------------
#### Description

Right now, `createComponentWithProxy` pass all the props not used in the rules. But the props innerRef shouldn't be passed down to the children because it's used to create a reference in fela.

If your okay with that statement, i can make a PR to filter the innerRef props from the props passed down to the children with `createComponentWithProxy.

We should use that opportunity to be sure they aren't others props that needs to be filtered like innerRef.

#### Steps to reproduce
1. create a Component with createComponentWithProxy
2. pass an innerRef to the component

#### Expected Behavior
```javascript
<MyFelaComponent innerRef="item" title="test" />
// pass down title but not innerRef (because it's used by fela to create ref)

```

#### Actual Behavior
```javascript
<MyFelaComponent innerRef="item" title="test" />
// pass down title and innerRef (which create a warning in React because innerRef is not a valid prop

```

**Comment by ragurney** [comment]
What would be the solution now if I actually want to pass `innerRef` to the child?
