### ISSUE TITLE
Future / My Vision

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#338]
This will be the master issue to collect all my visions and future plans for Fela.

## ~~Precompilation & Preprocessing~~
> done.

With the soon available babel-plugin-fela, we will gain the ability to perform any actions with the style objects. We will be able to preprocess and precompile the styles with plugins and run QA tools and what ever.

## ~~Static Style Extraction~~
> done.

With the new babel-plugin-fela, we will also be able to finally split static and dynamic styles with ease. We can extract all the static styles and prerender them. We can even go one step further and directly extract the static styles into single CSS files per component. With tools like Webpack, those files can then be merged and shipped. Having separate CSS files will come with many benefits which can be found [here](https://github.com/rofrischmann/fela/issues/305#issuecomment-318359063).

## ~~Minimal Runtime~~
> canceled.

~~Combining the 2 ideas above, we would be able to ship a very minimal runtime that focuses on performance, file size and primarily renders dynamic rules. All the other renderer features would basically be obsolete on runtime as we already preprocessed and extracted all the static style stuff.
(Not sure if this will actually have any benefits, but I'd like to experiment with that)~~

> This somehow does not bring any real benefit. Making fela any smaller is almost impossible.

## Progressive Rendering
Another interesting approach is progressive rendering. We could improve progressive rendering with Fela by adding a new `<style>`-element for every component, that only includes the declarations that are not already rendered else where.

## Tooling / DX
Currently I am working on another project that focuses on QA and style optimisations. More information soon.

**Comment by TxHawks** [comment]
Updated the Progressive Rendering proposal in #337

**Comment by steida** [comment]
Hmm, does it mean that style props are a dead end from the performance point of view? Is having everything dynamic measurable slow? How `<P size={5}>` or `<Text color="primary"` could be optimized or should be optimized at all? Just food for thoughts.

**Comment by rofrischmann** [comment]
Well, it's static information as well => we can somehow improve that as well. Just focusing on the simple cases first. I am pretty sure there's a lot of stuff we can do later on.

**Comment by rofrischmann** [comment]
Closing this as there is a separate issue for progressive rendering. DX stuff will be released by the end of 2017
