### ISSUE TITLE
Use insertRule for production

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#34]
**Version**: 1.0.0
**Environment**: DOM / Server
**Type**: General

-------------------
#### Description
As pointed out in https://github.com/rofrischmann/fela/issues/3 we should prefer using CSSOM's `insertRule` instead of mutating `textContent`. The performance difference can be huge.

#### Why only for production?
@nathanmarks found out that using `insertRule` will kill the Chrome DevTools which are very important for debugging though. Using `textContent` on the other hand does not interrupt the DevTools.

**Comment by rofrischmann** [comment]
In further discussion we found out that it is a difference of 1ms per 100 render cycles which is well, nothing. For some information check this (updated) [benchmark](https://gist.github.com/rofrischmann/15073c4297e0bbd6e0732e4903655d7c).

**Comment by thejameskyle** [comment]
> @nathanmarks found out that using `insertRule` will kill the Chrome DevTools 

Can you explain how? I'm trying to replicate that here: http://jsbin.com/yeyalef/edit?js,output

**Comment by rtsao** [comment]
FWIW I've never encountered any problems with `insertRule` and Chrome DevTools other than https://bugs.chromium.org/p/chromium/issues/detail?id=387952

**Comment by rofrischmann** [comment]
@thejameskyle @rtsao same here. I'm always using Safari anyways, so I really just added this because other libs do it as well. Also, using `textContent` instead of `insertRule` makes debugging the generated CSS much easier in development.

**Comment by thejameskyle** [comment]
Just trying to figure out if there's still a problem so we can get the browser devtools fixed
