### ISSUE TITLE
Missing "Advanced > Developer Experience" Documentation

### ISSUE THREAD

**Issue by dhurlburtusa** [rofrischmann/fela#340]
There is a link to "Developer Experience" in http://fela.js.org/docs/Advanced.html but it 404s. No `DeveloperExperience.md` file exist in the `docs/advanced` directory.

Am I blind? How do I tag this as a Docs issue?

**Comment by rofrischmann** [comment]
hmm seems like we forgot to remove it. We split that file into several recipes some time ago. Thanks for reporting!
