### ISSUE TITLE
RTL styling with Fela

### ISSUE THREAD

**Issue by ivan-zakharchuk** [rofrischmann/fela#344]
**Version**: 3.0.x
**Environment**: DOM
**Type**: Docs / General

-------------------
#### Description
It's more a question. I would like to know what is the best approach to support proper styling for the RTL language direction. E.g. to identify current direction I have dir="rtl" as an attr on the body tag and I assume that I can use it somehow in the fela style like a "parent": `[dir="rtl"] my-elem {}`. Please give me a hint how you see the best approach for that case. Thanks in advance for any reply.

**Comment by rofrischmann** [comment]
You can use this package to automatically "transform" your styles based on your rtl setting. We could also add a plugin that automatically does that.

I am not a huge expert with rtl actually. Maybe @kentcdodds could help a bit.

**Comment by kentcdodds** [comment]
If you've got a plugin system with fela, you could do what I do for [glamor here](https://github.com/threepointone/glamor/issues/241). Using [rtl-css-js](https://github.com/kentcdodds/rtl-css-js) :+1:

**Comment by rofrischmann** [comment]
@kentcdodds Yeah, thought about that as well. How do I know if I need the rtl or not? Especially when doing server-side rendering.

**Comment by kentcdodds** [comment]
That's domain-specific. For us, we determine directionality based on the locale and only apply the plugin when the locale is LTR. You can get the locale from request headers for SSR.

**Comment by TxHawks** [comment]
Sorry to jump in on this issue late, but just now noticed it.

I do a lot of RTL (Hebrew and Arabic), and automatic canversion of `left`
to `right` in properties can be very confusing, especially if your main
layout is RTL and your secondary is LTR. It basically forces you to always
write in LTR.

I think a better model is using `start` and `end` instead, like is done in,
e.g., `justify-content`, and have the plugin only alter such value, and not
explicit ones.

Something like:
```js
const isRtl = true;
{
  Start: 0, // -> Converted to right: 0;
  Left: 0, // -> Stays left: 0;
  Padding-start: 0, // -> Converted to padding-right: 0;
}
```

**Comment by kentcdodds** [comment]
I would love nothing more than for someone to come in and write something better than `rtl-css-js` be my guest :smile:
