### ISSUE TITLE
passThroughProps seems overkill

### ISSUE THREAD

**Issue by lostpebble** [rofrischmann/fela#350]
**Version**: 5.1.0
**Environment**: DOM / Server
**Type**: Feature / General

-------------------
#### Description

Hi there. Just starting out with your library this past week and I'm really enjoying it so far.

But one thing that I find a bit too verbose and I think might become a headache in the future is the passing down of props to my components, especially those props such as `onClick` and other regular DOM element props.

Right now, it seems the only way to achieve this behaviour is like this:

on `createComponent()` :
```
const ClickableList = createComponent(props => ({
  backgroundColor: "purple",
  color: "orange",
  fontFamily: "Roboto",
  fontWeight: "500",
  padding: "2em",
  userSelect: "none",
  cursor: "pointer",
}), "ul", ["onClick"]);
```
Or directly on the component itself:
```
<ClickableList passThrough={["onClick"]} onClick={this.flyMap}>
   {links}
</ClickableList>
```

Having to do this on every single component I would like to directly interact with seems overkill. If it is absolutely necessary that you don't have a white list that includes these kinds of props, then I propose a solution:

#### Proposal
Perhaps a global place to set your white list?

**Code Example**:
```
// Either at the creation in the config (probably best):

renderer = createRenderer( { ... , passThroughProps: ["onClick"]} );

// or on the actual renderer...

renderer.passThroughProps = ["onClick"]
```

Because I can see a lot of props that I *know* I will never use as style props. This would make working with Fela a bit more natural.

**Comment by AugustinLF** [comment]
Hey, [createComponentWithProxy](https://github.com/rofrischmann/fela/blob/master/packages/react-fela/docs/createComponentWithProxy.md) might work for you, it passes everything that you don't use in the rule function :)

**Comment by lostpebble** [comment]
Ah okay great. That seems to be what I'd like, thanks :)

Is there any reason this isn't the default ? Such as performance etc. ? I want to keep things as lean and performant as possible, so if that's the case I might still go the regular route.

**Comment by rofrischmann** [comment]
It's not the default behaviour as we do not really know much about proxies and there possible issues. One would be performance, although we found out it's not really slowing anything. Just like ~5ms or sth.
You should be with the the proxy version :)
