### ISSUE TITLE
Default Props

### ISSUE THREAD

**Issue by mmintel** [rofrischmann/fela#355]
**Version**: 5.1.1
**Environment**: DOM
**Type**: Bug

-------------------
#### Description

Hi,

i am trying to use props that have a default value, e.g. a function to calculate a font size. I want to pass this function as props so it's possible to change the way a font size is calculated per project.

The problem is that a console.log on props within a fela class doesn't show the default props, only props that are really passed to the component.

I tried to assign it via reacts defaultProps and also via ES6 default argument values, both ways show same results.

Here is my example:
```JS
import PropTypes from 'prop-types';
import React from 'react';
import classnames from 'classnames';
import { connect } from 'react-fela';
import ms from 'modularscale-js';

const Headline = ({
  tag = 'h2',
  styles,
  style,
  size,
  calculateSize = n => ms(n),
  className,
  children,
  ...props
}) => {
  const Tag = tag;
  return (
    <Tag
      style={{ fontSize: calculateSize(size) }}
      className={classnames(styles.headline, className)}
      {...props}
    >
      {children}
    </Tag>
  );
};

Headline.propTypes = {
  children: PropTypes.oneOfType([PropTypes.node, PropTypes.string, PropTypes.func]),
  tag: PropTypes.oneOfType([PropTypes.string, PropTypes.element, PropTypes.func]),
  className: PropTypes.string,
  size: PropTypes.number,
  calculateSize: PropTypes.func,
  styles: PropTypes.object,
  style: PropTypes.object,
};

const headline = props => {
  console.log(props)
  return {
    display: 'block',
    fontSize: props.calculateSize(props.size), //throws error, calculateSize is undefined
    ...props.styles,
  }
}

export default connect({
  headline,
})(Headline);
```

And I call it like this here for example `<Headline size={2}>Test</Headline>`.

The console log in `headline` shows something like this:

```
{
   children: "Test",
   size: 2
   //calculateSize should be here as well?
}
```

**Comment by rofrischmann** [comment]
True story. We've added defaultProps injection to `createComponent` but somehow missed that for `connect`. If you feel able to send a PR (taking examples from createComponent) I'd be very happy (would provide as much help as possible). Otherwise it'll take some time..

**Comment by TxHawks** [comment]
@rofrischmann - point me in the right direction, I'll try and see how complicated this is and if I manage to find time to implement this

**Comment by rofrischmann** [comment]
Basically all we have to do is to add the defaultProps here:
https://github.com/rofrischmann/fela/blob/master/packages/fela/src/bindings/connectFactory.js#L14

```javascript
static defaultProps = component.defaultProps || {}
```

it should then automatically use those
