### ISSUE TITLE
`fela-plugin-extend` doesn't dedupe values from `fela-plugin-fallback-value`

### ISSUE THREAD

**Issue by TxHawks** [rofrischmann/fela#356]
**Version**: 5.0.x
**Environment**: Both
**Type**: Bug

-------------------
#### Description
When using both the `fela-plugin-extend` and `fela-plugin-fallback-value`,  fallback values aren't deduped. The order is correct, so end result of the UI is still as expected, but extra styles are written.

#### Steps to reproduce
With the following code:
```js
import { createRenderer } from 'fela';
import { render } from 'fela-dom';
import extend from 'fela-plugin-extend';
import fallbackValue from 'fela-plugin-fallback-value';

const rule = props => ({
  fontSize: ['10px', '1rem'],
  extend: { fontSize: ['10px', '20vw'], },
});

const renderer = createRenderer({
  plugins: [ extend(), fallbackValue() ]
});

renderer.renderRule(rule);

render(renderer);
```

#### Expected Behavior
```html
<style data-fela-type="RULE" type="text/css">.a{font-size:10px;font-size:20vw}</style>
```

#### Actual Behavior
```html
<style data-fela-type="RULE" type="text/css">.a{font-size:10px;font-size:1rem;font-size:10px;font-size:20vw}</style>
```

See a (slightly more elaborate) live example  [here](https://www.webpackbin.com/bins/-KsZbEfo-7lA5gsG0-Zj)

**Comment by rofrischmann** [comment]
oh I see. Do you think it's an extend or a fallback issue? I'd rather say extend, but in general there could be more plugins adding multiple values to arrays, but not sure how to handle them then. I guess we should add an array-merging algorithm to the extend plugin. Would you mind giving it a try? could help to point the right lines out.

**Comment by TxHawks** [comment]
Have my hands pretty full at the moment, but since it's not a super urgent
issue (code does work as expected), I can give it a try. No promises though.

I agree that this should best be resolved in `extend` plugin with an array
merging algorithm, so behavior is predictable for other plugins.

Where should I look?

**Comment by rofrischmann** [comment]
Actually the correct place is not the fela repo itself hehe :D 
You'll have to check this one: https://github.com/rofrischmann/css-in-js-utils/blob/master/modules/assignStyle.js#L11

Both: 
- `base[property] = [...baseValue, ...value]`
- `base[property] = [...baseValue, value]`

should filter out recurring values where the last one always wins.

**Comment by TxHawks** [comment]
You mean something like: 
```js
const filteredBaseValue = baseValue
  
base[property] = [...baseValue.filter(baseValueItem => !value.includes(baseValueItem)), ...value]
```
right?

I think it should probably just be `base[property] = value`.

My original example wasn't so great, but I think that 
```js
const rule = props => ({
  fontSize: ['10px', '1rem'],
  extend: { fontSize: ['2em', '20vw'], },
});
```
should  produce:
```html
<style data-fela-type="RULE" type="text/css">.a{font-size:2em;font-size:20vw}</style>
```
rather than
```html
<style data-fela-type="RULE" type="text/css">.a{font-size:10px;font-size:1rem;font-size:2em;font-size:20vw}</style>
```

Let me know what you think though, and I'll implement. Already have tests written so shouldn't take more than a few minutes

**Comment by rofrischmann** [comment]
Don't you think they should merge? Feels like the right behaviour for me. (They won't be used anyways, but e.g. for fallback stuff that merges like display values it might be good to merge it to be safe)

**Comment by TxHawks** [comment]
The behavior I'd expect is overwrite, because I'd expect every time I use fallback to be independent of the times I've used it before. Same as when we do 
```js
const rule = props => ({
  fontSize: '10px',
  extend: { fontSize: '2em' }
});
```

I'd expect the output to be `.a{font-size:2em}` not `.a{font-size:10px;font-size:2em;}`

One more benefit of overwriting instead of merging is that it dramatically reduces the amount of code in `assignStyle` from some 30 to 20 LOC

But again, I don't think this is really critical either way, so just let me know how you want it and I'll push a PR

**Comment by rofrischmann** [comment]
Hmm well, yeah. Now as you say it... makes sense! Go for it.
