### ISSUE TITLE
Consider avoiding generating `.ad` class name by default

### ISSUE THREAD

**Issue by alanhogan** [rofrischmann/fela#357]
**Version**: 5.1.1
**Environment**:  Both
**Type**: Feature

-------------------
#### Description

This sits somewhere between a bug report and a feature request, but it’s more of the latter, I think.

What happened: I just spent 2 hours debugging what seemed like an obscure Safari bug that was causing some of my text to straight-up _not render_ in Mobile Safari (only), and no other browsers I use.

Eventually, I connected my iPhone to Safari's web inspector and immediately realized that a content blocker was to blame. You see, the text looked like this:

```html
<span class="x y z ab ac ad">pronoun, adjective, adverb</span>
```

and my content blocker is searching for a whole bunch of selectors and suppressing them — maybe too many, admittedly — but one of them is, quite reasonably, `.ad`.

Maybe we could avoid generating that selector? Surely this must be causing some problems for some Fela users’ users!

FEATURE REQUEST ONLY
====================

#### Proposal

Skip `ad` (and `ads`) when generating class names.

**Comment by alanhogan** [comment]
When I discovered the cause of the problem, I looked up `renderer` configuration and immediately saw 

```js
{
  filterClassName: className => className !== 'ad'
}
```

as well as `selectorPrefix`, both of which can help with this problem (and did solve it for me). I’m glad these options exist! But it would be better if this problem were solved by default, too, so no one wastes as much time as I just did. Yes, I feel kind of sheepish! But surely I won’t be the only one.

**Comment by TxHawks** [comment]
👍 
I see no reason for this not to be the default

**Comment by rofrischmann** [comment]
Funny thing: I talked to Hugo Giraudel

**Comment by alanhogan** [comment]
![love you blink 2](https://user-images.githubusercontent.com/6808/29805963-9205d482-8c41-11e7-964c-58c6bf2e9a4e.gif)

Amazing — super glad to hear it. You rock
