### ISSUE TITLE
Add `browserList` configuration option to fela-plugin-prefixer

### ISSUE THREAD

**Issue by TxHawks** [rofrischmann/fela#358]
**Version**: 5.0.x
**Environment**: Both
**Type**: Feature

-------------------
#### Description
It would be  dry useful to be able to specify a `browserList` object to configure the prefixing target range of `fela-plugin-prefixer`

#### Proposal
Add a `config` param to `fela-plugin-prefixer` that takes a `browserList` object

**Code Example**:
```javascript
import { createRenderer } from 'fela'
import prefixer from 'fela-plugin-prefixer'

const renderer = createRenderer({
  plugins: [ prefixer({
     browserList: {
      chrome: 46,
      android: 4,
      firefox: 40,
      ios_saf: 8,
      safari: 8,
      ie: 9,  // <-- This isn't the default
      ie_mob: 11,
      edge: 12,
      opera: 16,
      op_mini: 12,
      and_uc: 9,
      and_chr: 46
     }
  }) ]
})
```
Converting:

```js
{
  transform: 'translateX(50%)'
}
```
To
```js
{
 -ms-transform: 'translateX(50%)',  // <-- This would not have been generated with the default settings
 -webkit-transform: 'translateX(50%)',
 transform: 'translateX(50%)'
}
```

**Comment by rofrischmann** [comment]
This won't actually be possible. You would need to create your very own prefixer => your own prefixer plugin. This can be done combining the plugins documentation with the prefixer documentation, but won't be part of fela very soon I guess.
