### ISSUE TITLE
Here, have a logo?

### ISSUE THREAD

**Issue by alanhogan** [rofrischmann/fela#359]
![fela](https://user-images.githubusercontent.com/6808/29848376-fe53fe50-8cd4-11e7-92d1-046314c7af47.png)

I think you need a logo to be competitive — Fela is great but doesn’t have a logo yet. I took a little inspiration from the idea of sculpting (given the origin of the name Fela) for this possible logo. I guess it also kind of looks like a tombstone. that wasn't intentional, but you can make it work if you read it as css-in-js killing stylesheets.

I’m not saying it’s great, or even good, but if you want to use it… please do (and I can provide more versions & a source file). If not, no worries, just close the issue!

**Comment by rofrischmann** [comment]
Hey @alanhogan Thanks for your logo approach! Actually we're already working on a full lib branding and are pretty much done as of today. But we will try to consider your ideas and maybe take the idea of sculpturing into consideration. Thank you! (hope you're not sad now)

**Comment by alanhogan** [comment]
Oh hey, cool, I see the new logo up on your website :) very nice. No sadness — it's much nicer than I could do!
