### ISSUE TITLE
Consider using objects in favor of Map/Set

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#36]
**Type**: General

-------------------
#### Description
We should consider replacing all ECMAScript 2015 Set/Map with plain objects. Map and Set are both great new features, but yet not supported by every major browser (especially older versions which will logically never get native support).

##### Pro
* Less overhead as you would need to add polyfills for both
* Less pain setting up the environment
* Browser compatibility by default

##### Contra
* Might negatively affect performance? (Research)
* Reduces code semantics / (readiblity)

**Comment by johanneslumpe** [comment]
Im in favor of getting rid of both. Would love to see a benchmark regarding Set vs normal array but I think the result will show that it won't really matter for a real world application. The polyfill for Set is like 20kb if I remember correctly.

**Comment by rofrischmann** [comment]
Good point with the package size. That's what I dislike the most about those.
