### ISSUE TITLE
createComponentWithProxy does not support nested theme object

### ISSUE THREAD

**Issue by stream7** [rofrischmann/fela#376]
**Version**: 5.3.0
**Environment**: DOM
**Type**: Bug

-------------------
#### Description
It seems that createComponentWithProxy doesn't fully support `ThemeProvider`

#### Steps to reproduce
1. Visit https://www.webpackbin.com/bins/-Ku0MV82LrddhnGP6wAR for an example.

#### Expected Behavior
it shouldn't throw an error, it should pass the theme through.

#### Actual Behavior
it throws an error, it doesn't pass the theme through.

**Comment by rofrischmann** [comment]
I believe this might get fixed with the new Theming mechanism, but I'll make sure to add a test case. Thank you!
