### ISSUE TITLE
[TypeScript] 'combineRules' ignores rule props

### ISSUE THREAD

**Issue by jrf0110** [rofrischmann/fela#377]
**Version**: 5.2.0
**Environment**: DOM / Server / Both
**Type**: Bug

-------------------
#### Description

The current definition for combineRules ignores rule parameter types and therefore the compiler will miss a lot of potential errors

#### Steps to reproduce

1. Create rules with props:

```typescript
import { createRenderer, combineRules } from 'fela'

const renderer = createRenderer()

const rule = (props: { fontSize: number }) => ({
  fontSize: props.fontSize,
  color: 'red'
})

const anotherRule = () => ({
  color: 'blue'
})

const superRule = combineRules(rule, anotherRule)
```

2. Render the combined rule with an incorrect parameter

```typescript
renderer.renderRule(superRule, { fontSize: '12px', foo: 'bar' })
```

#### Expected Behavior

I'd expect the definitions to be defined with generics such that you could call the following and get the compiler error

```typescript
renderer.renderRule(superRule, { fontSize: '12px', foo: 'bar' })
                                                   ^^^^^^^^^^
                                              is not a property of the params
```

#### Actual Behavior

The actual behavior is no warning at all. This manifests itself in react-fela as components being passed props that aren't defined on the component (and thus a compiler error).

**Comment by jrf0110** [comment]
I'm happy to contribute to the definition file to fix this issue so TypeScript users of Fela get proper type inference on their rules

**Comment by rofrischmann** [comment]
We highly appreciate a contribution. I am not using TypeScript myself, so can't really help here.

**Comment by RafalFilipek** [comment]
@jrf0110 any idea how to start :) ? I trying with Partials, Records etc but no luck.

**Comment by jrf0110** [comment]
@RafalFilipek I've got working definitions for my project that go something like this:

```typescript
export type TRule<T> = (attrs?: T) => React.CSSProperties
export function combineRules<A, B>(a: TRule<A>, b: TRule<B>): TRule<A & B>
// This doesn't support dynamic arguments, so it's easiest to just
// explicitly define a few more of these with more args
export function combineRules<A, B, C>(a: TRule<A>, b: TRule<B>, c: TRule<C>): TRule<A & B & C>
// .. Add more as needed (I personally only ever call with 2 args anyway)
```

Pretty sure it will require refactoring of some other types within Fela, to get those merged

**Comment by rofrischmann** [comment]
any progress here guys?

**Comment by jrf0110** [comment]
Thanks for the ping @rofrischmann let me see if I can knock this out real quick

**Comment by rofrischmann** [comment]
Any update on this? (Just asking, no worries)

**Comment by jrf0110** [comment]
The update: It was a little harder than expected and I haven't tried again since early October. From what I remember, `TRule` currently isn't a generic type, but more like `any` (or rather a function whose argument is an object with unknown shape that returns CSSProps). Changing it to be generic affects _a lot_ of the existing types.

I'll put some time on my calendar this week to take another stab
