### ISSUE TITLE
Plugin for flow-relative style authoring

### ISSUE THREAD

**Issue by TxHawks** [rofrischmann/fela#379]
Following the short discussion in [#344 (comment)](https://github.com/rofrischmann/fela/issues/344#issuecomment-3234515140) I published a [library](/txhawks/bidi-css-js) which is based on `rtl-css-js`'s core logic, but enables authoring direction-independent, flow-relative styles. I am planning to publish a fela-plugin wrapping its functionality and was wondering if you'd like it as part of this repository or should I publish it independently.

**Comment by rofrischmann** [comment]
If you want to contribute directly, I'd love to have it added here. You benefit from the build/test/release environment and get auto updates if fela changes :)

Apart from that it sounds awesome what you've done there! Id love to review if required!

**Comment by TxHawks** [comment]
Cool. Heading to bed now, but will make sure to send a pull request tomorrow
