### ISSUE TITLE
`is` keyword exists in Custom Elements spec as valid attribute.

### ISSUE THREAD

**Issue by RafalFilipek** [rofrischmann/fela#384]
**Version**: 5.3.0
**Environment**: Both
**Type**: Bug / General

Hi!

The `is` keyword is part of the W3C Draft spec for creating custom HTML elements with custom behavior. For example http://w3c.github.io/webcomponents/spec/custom/#type-extension-example

Should we rename it in 6.0? 

Thank you!

**Comment by rofrischmann** [comment]
Go for it! “as” should be fine :)
