### ISSUE TITLE
Proposal: do not pass through the innerRef prop

### ISSUE THREAD

**Issue by vlad-zhukov** [rofrischmann/fela#385]
**Version**: 5.0.x
**Environment**: Both
**Type**: General

-------------------
#### Description

Thanks for a great library! I am using it with React and have got a question/proposal. Why does `fela` &ndash; or more accurately `createComponentFactory` &ndash; passes down `innerRef`? Am I able to use it? (I assume not because it's already used as a `ref`)

My proposal is to ignore it a similar way `theme` is ignored. WDYT?

**Comment by rofrischmann** [comment]
Does it pass the innerRef prop to the wrapped component? That must have been missing, it should be used as the ref and removed ofc. Will try to ship that with next major release today/tomorrow.

**Comment by vlad-zhukov** [comment]
Well, it doesn't pass it to the wrapped component directly. It passed it to the `passThroughProps` in [`createComponent`](https://github.com/rofrischmann/fela/blob/master/packages/react-fela/docs/createComponent.md), however `theme` prop is not passed.

**Comment by rofrischmann** [comment]
Yeah I see, but that causes it to be passed down right?

**Comment by vlad-zhukov** [comment]
I am able to pass it down like this:

```js
createComponent(() => {/* rules */}, 'div', () => ['innerRef']) 
// most likely a plain array will work too but I haven't tested
```
But I have no access to `theme` prop there. I understand that `theme` and `innerRef` work differently, that's why I am asking is it intended or not. If it's not I feel it shouldn't be passed.

**Comment by rofrischmann** [comment]
added for the next release :)

**Comment by derek-duncan** [comment]
@rofrischmann I think I'm seeing a bug in 6.x since `innerRef` is not passed down any more. For instance...

```javascript
const SomeFelaComponent = withTheme(props => (
  <AnotherFelaComponent {...props} />
))
```

In this example, `SomeFelaComponent` is passing all props through to `AnotherFelaComponent`. However, since `innerRef` is not passed through, it will return a `ref` for the instance of `AnotherFelaComponent`, which is the fela wrapper, not the actual React element.

**Comment by vlad-zhukov** [comment]
@derek-duncan that's what `innerRef` is supposed to do, isn't it? If you need to get a `ref` from a deep-nested component you can pass your own prop and use it there.

**Comment by rofrischmann** [comment]
Actually we do not even filter innerRef yet, must be part of the new withTheme-HoC actually, ill check this

**Comment by derek-duncan** [comment]
@vlad-zhukov Maybe you're right... it just makes working with Fela-wrapped components pretty cumbersome. I don't think I've ever had a use-case where I would want to get the ref on the actual Fela wrapper.

@rofrischmann ah gotcha. thanks! 👍
