### ISSUE TITLE
UMD build does not contain renderer

### ISSUE THREAD

**Issue by johanneslumpe** [rofrischmann/fela#39]
Looks like a bug to me:

```js
var fela = {
  Selector: Selector,
  enhanceWithPlugins: enhanceWithPlugins
};
```

**Comment by rofrischmann** [comment]
hmm which UMD build are you testing with?

**Comment by johanneslumpe** [comment]
Yeah never mind :D I used the url reference from the README - which obviously is an outdated build ;)
