### ISSUE TITLE
fela-plugin-extend doesn't process nested style components

### ISSUE THREAD

**Issue by mbme** [rofrischmann/fela#392]
**Version**: 5.2.0+
**Environment**: DOM
**Type**: Bug

-------------------
#### Description
`fela-plugin-extend` doesn't process extended React style components:

#### Steps to reproduce
```jsx
import { createComponent } from 'react-fela'

const X = createComponent(() => ({
  backgroundColor: 'red',
  extend: [
    {
      condition: true,
      style: {
        backgroundColor: 'yellow',
      },
    },
  ],
}), 'button')

const X1 = createComponent(() => ({
  extend: {
    width: '100px',
  },
}), X)

// render <X1 />
```

#### Expected Behavior
`X1` should have yellow background

#### Actual Behavior
`X1` has red background

**Comment by rofrischmann** [comment]
Does <X> yield a yellow backgroundColor? If yes, this is quite interesting.

**Comment by mbme** [comment]
just to clarify: in this example I expect to see yellow background in `X1` component but I see red background instead. From the other side, when I render `X` component, I see yellow background as expected.

(I use `fela-preset-web`)

**Comment by rofrischmann** [comment]
Woops, looks like I forgot some words :D but yeah I see what you’re talking about. Interesting..

**Comment by rofrischmann** [comment]
Yeah thank you. Kinda figured it out now. It's how we assign arrays now, but actually the current way is the natural way and the extend merging is rather a special case, so I guess we'll create something for this specific use case.

**Comment by rofrischmann** [comment]
Check out fela-combine-arrays.

There's an example how you can explicitly combine extend values :)

**Comment by TxHawks** [comment]
I'm on a phone, so hard to read all the code, but I think this should probably be internally used by fela-plugin-extend by default, or in the very least be mentioned in its readme very clearly.

Do fallback values still work as expected inside extend blocks with this?

**Comment by rofrischmann** [comment]
Everything should work as expected. We can add a documentation hint at the plugin-extend docs, but we technically **can't** auto enable that through the plugin, as the plugins only execute on actual render, but we need to overwrite the merging method at initialisation.

**Comment by mbme** [comment]
cool! it works, thanks!
