### ISSUE TITLE
Bug: Theme prop is passed without use of ThemeProvider component

### ISSUE THREAD

**Issue by aaronschubert0** [rofrischmann/fela#394]
**Version**: 6.0.0
**Environment**:  Both
**Type**: Bug
-------------------
#### Description
Upgraded to fela 6.0.0 on our project (`fela`,`react-fela`,`fela-dom`). After upgrading these packages, a new prop `theme: {}` is present when connecting a component using `connect`. From reading the docs, it is my understanding that this should only occur when a [Theme Provider](https://github.com/rofrischmann/fela/blob/master/packages/react-fela/docs/ThemeProvider.md) is used. This did not occur prior to 6.0.0. If this is an intended change, then this isn't noted in the changelog.

#### Steps to reproduce
1. Have existing code that spreads remaining props over div
2. Upgrade to 6.0.0
3. Observe `Unknown prop  theme on <div> tag. Remove this prop from the element.` error

#### Expected Behavior
To not have the the theme prop present

#### Actual Behavior
The theme prop is present

**Comment by rofrischmann** [comment]
This is actually just a bug. The theme should not passed down, but an empty theme is present everywhere :P

**Comment by aaronschubert0** [comment]
@rofrischmann Ah, awesome, thanks for confirming that. Is it a straightforward fix?

**Comment by rofrischmann** [comment]
Yeah, will be able to fix that pretty soon. You may just go on and ignore the warning for now.

**Comment by TxHawks** [comment]
Want to point me in the right direction? I may have time to take a stab at it tomorrow

**Comment by timswalling** [comment]
@rofrischmann would this explain why React components/HTML elements are now wrapped in two Fela components? Or is that by design?

For example:
```javascript
<rule color="red">
  <rule color="red" theme={}>
    <div className="a">This is an example</div>
  </rule>
</rule>
```

**Comment by rofrischmann** [comment]
that's basically because we now have another HoC added to fetch the theme from context to props, so should not be a problem
