### ISSUE TITLE
Simplify a way to work with the project

### ISSUE THREAD

**Issue by vlad-zhukov** [rofrischmann/fela#396]
**Version**: 6.0.x
**Type**: Infrastructure

-------------------
#### Description
For me it's unclear how to work with the project. I wasn't able to properly install it locally and make tests pass.

What I did:
* Installed deps with `yarn`.
* `yarn setup`, it took quite some time to do the job and threw some weird error in the end, I had to finish it with Ctrl+C.
* `yarn build` (no idea why it's needed, probably not, but `yarn setup` has this step).
* Tried running `yarn test` and a lot of tests failing because they can't import functions from some packages. It turned out the root `node_modules` has outdated versions of `fela-dom`, `fela-utils` and others.

Proposals:
* Add a 'Contributing' paragraph to README with explanation how install, test and develop separate packages, commit changes and do pull requests.
* Move non-packages out of the `packages/` folder, especially examples. They bring a lot of unnecessary dependencies, take time to install and have conflicts with deps from other packages.
* Consider using `yarn` for everything.
* Consider using [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/).

**Comment by rofrischmann** [comment]
What about using this file: https://github.com/rofrischmann/fela/blob/master/.github/CONTRIBUTING.md :P?

**Comment by vlad-zhukov** [comment]
@rofrischmann sorry, haven't noticed it. 😄 

However it doesn't help me, it says the same things that I've already tried and unfortunately they don't work for me. Also what about other proposals?

**Comment by rofrischmann** [comment]
a clean setup with `npm run setup` should work. If setup fails, everything else will fail as well, but it works for me. What versions do you use?

**Comment by vlad-zhukov** [comment]
Everything latest: Node 8.5.0, npm 5.4.2, yarn 1.1.0.
Should I try Node v6?

**Comment by rofrischmann** [comment]
hmm not really. I'm running Node 8, npm 5.4 and it works just fine...
Have you tried a clean setup again?

**Comment by vlad-zhukov** [comment]
A clean install with npm works, not sure why you've got `yarn.lock` then.

**Comment by vlad-zhukov** [comment]
Alright, I finally managed to install it with `yarn`. 2 previous time I got weird cryptic errors during installation, not sure what it was. Sorry for bothering you with this 

There is still a problem that bootstrapping takes forever and makes my IDE lag a bit. Are you fine with this?

**Comment by rofrischmann** [comment]
Yeah Ive been using yarn a lot but recently I use npm again a lot just because we can’t use yarn at work yet which makes me kinda used to npm again

Fine that it worked now :)
Yeah initial bootstrapping takes quite a bit once. Not sure if there’s a way to improve that... after all we got a pretty amount of packages to setup :p
