### ISSUE TITLE
5.x -> 6.0.0 Upgrade Guide

### ISSUE THREAD

**Issue by levithomason** [rofrischmann/fela#400]
**Version**: 5.x
**Environment**: DOM
**Type**: Docs / General

-------------------
#### Description

Hi there, looking for an upgrade guide from 5.x to 6.x.  I've searched the docs, issues, and the blog post but apologies if I've overlooked it somewhere.

Sidenote, I'm the author of [Semantic UI React](https://github.com/Semantic-Org/Semantic-UI-React) and have been trialing `fela` in some side projects.  Love it so far.  It seems breaking changes are fairly frequent still, any feel as to when it may stabilize?

**Comment by rofrischmann** [comment]
Heyhey,

Yeah there is no migration guide for 5 to 6. Actually you should not need one. We did a major update to ensure nothing breaks as lots of internal implementations got refactored/improved, but the public API should remain the same :)

E.g. I was able to just upgrade the versions at work where we use it for a huge project atm.

Btw: semantic UI looks great! Planning to try Fela with it?

**Comment by rofrischmann** [comment]
(Going to close this, feel free to chat on Gitter!)

**Comment by levithomason** [comment]
>We did a major update ... but the public API should remain the same :)

Interesting, does `fela` have plans to follow standard [semver.org](https://semver.org) at some point?

>Btw: semantic UI looks great! Planning to try Fela with it?

I hope so!  Theming via JS is easily one of the most common requests and one of the biggest hangups for folks.

I wrote a short novel on the topic for SUIR in https://github.com/Semantic-Org/Semantic-UI-React/issues/1009.   The interop with RN and ability to generate conventional CSS stylesheets is a big win for we'd need.

**Comment by rofrischmann** [comment]
Yeah, we actually do that since 4.x, but I as I was changing a lot internally, I wanted to ensure nothing breaks (even though if no breaking changes have been added).

According your goals: If you need any advice, feel free to check the Gitter chat. We'd love to collaborate and help here :)

**Comment by Redmega** [comment]
`is` has become `as` in `createComponent`. There are other issues which have popped up as well. It's not quite as clean a transition as you'd think. Anyone else having these issues?

**Comment by christophediprima** [comment]
I am also having issues with undefined theme when moving to version 6 of react-fela.
