### ISSUE TITLE
[fela-plugin-named-media-query] errors

### ISSUE THREAD

**Issue by lostpebble** [rofrischmann/fela#401]
**Version**: 6.0.0 and 5.0.0
**Environment**: Both
**Type**: ~~Bug~~ Docs

-------------------
#### Description
I've been trying to use `fela-plugin-named-media-query` with my app but it appears that I'm always getting a certain error message, even though it does appear to be working behind the scenes:

```
Invalid nested property. Only use nested media queries, pseudo classes, child selectors or &-combinators.
              Maybe you forgot to add a plugin that resolves "bigScreenOnly". {property: "bigScreenOnly", value: {…}}
```

(This error appears multiple times, once for each of the media queries I've create)

I've set it up correctly as far as I can tell:

```
const mediaQueries = {
  bigScreenOnly: `@media (min-width: ${EMediaDimensions.BigScreenStart}px)`,
  tabletOnly: `@media (min-width: ${EMediaDimensions.TabletStart}px) and (max-width: ${EMediaDimensions.BigScreenStart - 1}px)`,
  mobileOnly: `@media (max-width: ${EMediaDimensions.TabletStart - 1}px)`,
  smallMobileOnly: `@media (max-width: ${EMediaDimensions.MobileSmallEnd}px)`,
  tabletUpwards: `@media (min-width: ${EMediaDimensions.TabletStart}px)`,
  tabletDownwards: `@media (max-width: ${EMediaDimensions.BigScreenStart - 1}px)`,
};

const namedMediaQueryPlugin = namedMediaQuery(mediaQueries);

renderer = createRenderer({
      plugins: [
        extend(),
        fallbackValue(),
        unitPlugin,
        validatorPlugin,
        namedMediaQueryPlugin
      ]
    });
```
**Oops... Upon writing this issue I tried to change the order of the plugins and it appears that the error message is gone now. I guess the order is important. Perhaps `fela-plugin-validator` should always come last? What my renderer looks like now:**

```
renderer = createRenderer({
      plugins: [
        namedMediaQueryPlugin,
        extend(),
        fallbackValue(),
        unitPlugin,
        validatorPlugin
      ]
    });
```

From the docs on plugins I see that it says "Order Matters", but there isn't really an indication while using various plugins of what that order should be.

**Comment by rofrischmann** [comment]
Oh, yeah the validator should be the last one - always.
Maybe we have to update the docs here, seems a bit out-dated. 
Would you mind sending a PR?

I might also come up with a best practice complete order tomorrow.
It could be categorized I guess.

**Comment by lostpebble** [comment]
Cool, will make a PR quick for the validator plugin's README.md.

A best practice for ordering would be great.
