### ISSUE TITLE
ThemeProviderFactory should only update theme when changed

### ISSUE THREAD

**Issue by namjul** [rofrischmann/fela#404]
**Version**: 6.0.0
**Environment**: DOM
**Type**: Bug

-------------------
#### Description
ThemeProvider always updates theme pub/sub-store when rendered.
https://github.com/rofrischmann/fela/blob/master/packages/fela-bindings/src/ThemeProviderFactory.js#L23
There should be a check if theme has actually changed.

#### Expected Behavior
```javascript
    componentWillReceiveProps(nextProps: Object): void {
      if (this.props.theme !== nextProps.theme) {
        this.theme.update(nextProps.theme)
      }
    }
```

#### Actual Behavior
```javascript
    componentWillReceiveProps(nextProps: Object): void {
      this.theme.update(nextProps.theme)
    }
```

**Comment by rofrischmann** [comment]
Wanna add a PR? Looks fine to me!
But the check above might be false-positive if you pass a theme object directly.

I'd rather implement `shouldComponentUpdate` (you need to add `recompose` to `fela-bindings`).
```javascript
import { shallowEqual } from 'recompose'

...
  shouldComponentUpdate(nextProps) {
    return !shallowEqual(this.props.theme, nextProps.theme)
  }
...
```

**Comment by namjul** [comment]
Sure, will open a PR tomorrow.

**Comment by namjul** [comment]
The problem is that `componentWillReceiveProps` will still be called even when `shouldComponentUpdate` returns false. So it would still send an update to the theme pub/sub object.

**Comment by rofrischmann** [comment]
Oh, does it? Was not aware of that, never used willReceiveProps before. Looks like your proposal is right then!

**Comment by namjul** [comment]
Yes, you can even check it with this nice lifecycle simulator https://reactarmory.com/guides/lifecycle-simulators ;)
