### ISSUE TITLE
Nested selectors result in wrong classnames during hot reload and results in duplicate styles in the sheet

### ISSUE THREAD

**Issue by aga5tya** [rofrischmann/fela#412]
**Version**: 6.0
**Environment**: DOM
**Type**: Bug / Clarification

-------------------
#### Description
When latest 6.0 version is used with styleguidist, the initial load has proper classnames with nested selectors, but on hot reload, rules shared from the nested rule will result in irregular class name being appended. Further the latter style generations will result in duplicate styles.

#### Steps to reproduce (No SSR Involved)
Detailed in the comments of source
https://github.com/aga5tya/fela/blob/bump-fela-styleguide/packages/example-with-styleguidist/src/components/AComponent/AComponent.js#L26

Commits for Repro:
https://github.com/aga5tya/fela/commit/2d3a6b3021af46018476852dad3d49c91537b69b
https://github.com/aga5tya/fela/commit/1aa2803ed486482d8e42e3f2bdec77d34bd5c5c3
https://github.com/aga5tya/fela/commit/ab9485a2692cfb3a974e168a69ba6d1eb1a1083c

#### Expected Behavior
Class Names has to be substitued properly as when initial load and duplicate styles should not appear in the injected stylesheet.

#### Actual Behavior
![screen shot 2017-09-30 at 4 15 38 pm](https://user-images.githubusercontent.com/17351163/31045155-bdb79fc0-a5fa-11e7-9ebc-434e66bc6c5e.png)
![screen shot 2017-09-30 at 4 16 02 pm](https://user-images.githubusercontent.com/17351163/31045156-c202b10a-a5fa-11e7-9d89-9a7f69ed3300.png)

**Comment by aga5tya** [comment]
@rofrischmann Got a chance to look into the repro ?

**Comment by rofrischmann** [comment]
Not yet actually. I'm in Amsterdam right now at the Fronteers Conference. Will dig into it later this weekend maybe.

**Comment by rofrischmann** [comment]
Would you mind updating to 6.0.1 and check if the error persists? If yes, I will dig deeper for sure!

**Comment by aga5tya** [comment]
@rofrischmann,, Nested selectors seem to work fine and cannot reproduce it now 🎉  But duplicate styles as shown in the last image still exists,, its present even on first load and then becomes more on hot reload.

**Comment by rofrischmann** [comment]
Found the issue. Not sure if it's an "issue" yet, but I might think about it later. Definitely feels like a wrong behaviour right now.

**Comment by aga5tya** [comment]
@rofrischmann Didn't get time earlier, tested now. Works like a charm, Thank you so much 🎉  Publishing anytime soon ?

**Comment by rofrischmann** [comment]
Later today :)
