### ISSUE TITLE
The prop `styles` is marked as required, but its value is `undefined`.

### ISSUE THREAD

**Issue by simonsmith** [rofrischmann/fela#421]
**Version**: 6.0.0
**Environment**: DOM
**Type**: Bug

#### Description
When expecting `styles` as a required prop I'm getting the following error in the console:

```
The prop `styles` is marked as required in `FelaTest`, but its value is `undefined`.
```

What is odd is that if I log out `styles` from within the `render` method I never see an `undefined` value, just the styles object so it doesn't appear that `undefined` is actually passed in.

#### Steps to reproduce

**Test.js**

This component is rendered within a `Provider` with a renderer passed in.

```js
import React from 'react';
import {connect} from 'react-fela';
import PropTypes from 'prop-types';

function Test({styles}) {
  console.log(styles);
  return (
    <div>test</div>
  )
}

Test.propTypes = {
  styles: PropTypes.object.isRequired,
};

const styles = {
  hello: () => ({
    color: 'red',
  }),
};

export default connect(styles)(Test);
```
#### Expected Behavior
The styles object should appear in the console

#### Actual Behavior
The styles object is logged, but before that happens the following warning appears

```
proxyConsole.js:54 Warning: Failed prop type: The prop `styles` is marked as required in `FelaTest`, but its value is `undefined`.
    in FelaTest (at App.js:14)
    in App (at index.js:12)
    in Provider (at index.js:11)
```

**Comment by rofrischmann** [comment]
Oh well this is odd. Not sure if it is an actual Fela error if the styles always get passed down.

**Comment by simonsmith** [comment]
@rofrischmann Still seeing the error after updating to `6.0.1`. Having a quick look at the transpiled `hoistStatics.js` in my `node_modules` doesn't show the changes you've made in that commit.

**Comment by rofrischmann** [comment]
Oh that's strange :o I will check that. you updated react-fela?

**Comment by rofrischmann** [comment]
🙈😂 no worries
