### ISSUE TITLE
fela-plugin-extend: _mergeStyle is not a function

### ISSUE THREAD

**Issue by talkhot** [rofrischmann/fela#426]
**Version**: 5.0.10
**Environment**: / Client
**Type**: Bug

-------------------
#### Description
Having all at the fela packiges at the lasted version gives the following error below, when using fela-plugin-extendin the rendererConfig. Downgrading fela-plugin-extend from 5.0.10 back to 5.0.9 removes the error.

```
 renderer._mergeStyle is not a function at extendStyle (/.../node_modules/fela-plugin-extend/lib/index.js:13:16)
```

**Comment by rofrischmann** [comment]
Oh, seems like we made a mistake updating the versions. You can install and use the fela-combine-arrays enhancer to get a quick fix.
