### ISSUE TITLE
Storybook: Hot Module Replacement

### ISSUE THREAD

**Issue by SpencerCDixon** [rofrischmann/fela#427]
Running latest versions of everything.  Just curious if someone has gotten hot module reloading working and could point to docs of how to integrate with Fela

**Comment by rofrischmann** [comment]
Can you provide a working example repository?
I use storybook and it works just as expected.
If you run the React example locally, is works as well.

**Comment by SpencerCDixon** [comment]
Hmm yeah I must be doing somethinggg funky that is breaking things.  Let me get you a better example!

**Comment by ernestofreyreg** [comment]
@rofrischmann While using Storybook, deleting css props doesn't work. Only new props and modified props are updated on hot module reload.
