### ISSUE TITLE
Upgrade from V5 to V6 breaks SSR rehydration

### ISSUE THREAD

**Issue by talkhot** [rofrischmann/fela#431]
**Version**: 6.0.2
**Environment**: Both
**Type**: Bug

-------------------
#### Description
I've upgrade from V5 to V6 and all works fine expect that the rehydration from Server to Client fails.
It seems to happen when styles like `'& .stro-right'` are used (in createComponent).

styles that seem causing the error:
```
'& > *': {
    ':after': {
      content:  "' • '",
    },
    ':last-child:after': {
      content: 'none'
    }
 }

  '& .stro-right': {
    display: showContent ?  '' : 'none'
  }
```

error
```
Warning: Prop `className` did not match. Server: "_s _t _u _v" Client: "_s _t _cd > * _v"
```

**Comment by rofrischmann** [comment]
I am currently improving the rehydration, thanks for the issue! For now it’s fine to do <Provider rehydrate={false} />

**Comment by newsiberian** [comment]
Hi, after migration I also faced with problems with hydration. In my case rules naming are repeats. I tried `react` 15.6.1 and 16 and behavior the same in both cases. All `fela` packages are latest. With `<Provider rehydrate={false} />` all seems works fine.
![cryptit_179](https://user-images.githubusercontent.com/11130487/32410055-dc9fb3b2-c1ea-11e7-91dd-8de556299710.png)

**Comment by bkniffler** [comment]
Is anyone else having problems with safari? Not sure if its due to the latest version or since transitioning from 5 to 6 since I don't use safari, but currently my website with SSR and rehydration throws an error. Chrome/IE works fine. 

Message (rehydration.js):
TypeError: null is not an object (evaluating 'e.sheet.cssRules')

Demo: https://5ba10f98b13fb109d225c95c--kniffler-ortho.netlify.com/

If I set rehydration=false, I'm getting some visual issues (https://5ba110771f12b70e47d80dc4--kniffler-ortho.netlify.com/) across all browsers.

**Comment by bkniffler** [comment]
Here is my config: https://github.com/orgilla/filou/blob/next/packages/core/create-renderer.es6

**Comment by rofrischmann** [comment]
Can u hit me up on Gitter or Twitter? Don't think fela 6 is the issue, but rather the newer fela-dom version.

**Comment by isymchych** [comment]
@rofrischmann just hit same issue like @bkniffler 

For me it happens on Safari 12
`sheet` [here](https://github.com/rofrischmann/fela/blob/master/packages/fela-dom/src/dom/rehydrate.js#L52) is `null` when rule has ie-specific media query (so rule doesn't apply to Safari)

According to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/HTMLStyleElement) `null` is a legal value for `sheet`, but looks like it breaks [`createNode`'s logic ](https://github.com/rofrischmann/fela/blob/master/packages/fela-dom/src/dom/connection/createNode.js)

Snippet:
```js
const id = `random-id-${Math.floor(Math.random() * 1000)}`;
const node = document.createElement('style');
node.id = id;
node.type = 'text/css';
node.media = 'all and (-ms-high-contrast: none), (-ms-high-contrast: active)';
document.head.appendChild(node);
console.log(!!document.getElementById(id).sheet);
```

**Comment by rofrischmann** [comment]
Oh wow. Wasn't aware of ie-specific media queries either.
Can you both confirm that rehydration works fine if you do sth. like `node.sheet ? node.sheet.cssRules : []`
Not sure how to actually test this as it only occurs in Safari?

**Comment by isymchych** [comment]
yep, [this](https://github.com/isymchych/fela/commit/6ed245545b742571dd837538495c5f711dbf9ea1) fixes the issue with rehydration for me :fireworks:
