### ISSUE TITLE
React 16 returning array/multiple elements breaks the SSR rehydration

### ISSUE THREAD

**Issue by talkhot** [rofrischmann/fela#438]
**Version**: 6.0.0
**Environment**: Both
**Type**: Bug

-------------------
#### Description
When using the new React 16 feature of returning a array of components it breaks the SSR rehydration.

for example:
```
return [
   <MyComponent key={1} />,
   <MyComponent key={2} />
]
```

**Comment by rofrischmann** [comment]
What has rehydration to do with returning arrays?

**Comment by talkhot** [comment]
I don't know. But removing a element container from a list and returning a array of elements, breaks ssr.

example to break ssr:
```
return [
   <MyComponent key={1} />,
   <MyComponent key={2} />
]
```

works as expected without rehydration error.
```
return (
   <span>
      <MyComponent />
      <MyComponent />
   </span>
)
```

**Comment by rofrischmann** [comment]
I will close this. React 16 is not officially supported anyways, but this should be fixed with upcoming versions.
