### ISSUE TITLE
[TypeScript] fela-dom misses 'renderToMarkup' typings

### ISSUE THREAD

**Issue by veeramarni** [rofrischmann/fela#443]
**Version**: 6.0.3
**Environment**: DOM / Server / Both
**Type**: TS2305: Module '"fela-dom"' has no exported member 'renderToMarkup'.

-------------------
#### Description
When using `renderToMarkup`, getting the following type error. 

```
TS2305: Module '"fela-dom"' has no exported member 'renderToMarkup'.
```

**Code Example**:
```javascript
import { createRenderer, IRenderer } from 'fela';
import prefixer from 'fela-plugin-prefixer';
import fallbackValue from 'fela-plugin-fallback-value';
import unit from 'fela-plugin-unit';
import lvha from 'fela-plugin-lvha';
import validator from 'fela-plugin-validator';
import logger from 'fela-plugin-logger';
import  {renderToMarkup}  from 'fela-dom';
import perf from 'fela-perf';
import beautifier from 'fela-beautifier';
import fontRenderer from 'fela-font-renderer';

export default (fontNode) => {
    const renderer = createRenderer({
        plugins: [prefixer(), fallbackValue(), unit(), lvha(), validator({})],
        enhancers: [/*perf(),*/ beautifier(), fontRenderer(fontNode)],
    });
    if ( __SERVER__) {
        return renderToMarkup(renderer);
    }
    return renderer;
};
```

**Comment by rofrischmann** [comment]
Looks like a TypeScript warning right? Feel free to send a PR fixing this. I'm not using TypeScript and don't update these definitions as well.

**Comment by IgorBabkin** [comment]
@rofrischmann I didn't find export of createStyleTagMarkup function in fela-utils. This is not typescript warning only.

**Comment by rofrischmann** [comment]
There'll be a fela-dom patch later today which fixes this export. Sorry about that.

**Comment by IgorBabkin** [comment]
I used version 5.0.8. Sorry, seems like 6.0.3 has no problems
