### ISSUE TITLE
Import CSS file to renderer as static styles

### ISSUE THREAD

**Issue by lostpebble** [rofrischmann/fela#444]
#### Proposal

I would very much like a way to be able to dynamically import third party styles into my fela renderer as static styles.

I'm not sure if this is already possible, but from reading the `renderStatic` docs it seems perhaps not:

"It accepts either a valid CSS string or a basic style object with a custom selector to be rendered into."

I see you can pass a css string, but this could be problematic if you rely on third party styles which change from time to time, for example a library might require you to import the styles so the component renders correctly:

`import 'react-aspect-ratio/aspect-ratio.css'`

But if we statically add the string from that file into fela, upon update of that library those styles will be stale.

Is there any current recommended way to deal with this use case?

**Comment by vlad-zhukov** [comment]
It's super easy to do in webpack, that's actually what `css-loader` does by default &ndash; bundles css files into js files and provides a simple wrapper. To get a css source string there a method `toString()`, you can use it like this:

```js
import styles from 'react-aspect-ratio/aspect-ratio.css';

// ...

renderer.renderStatic(styles.toString())
```

**Comment by rofrischmann** [comment]
Let's go and add this to the docs somewhere :) Sounds like a great recipe again.

**Comment by aga5tya** [comment]
@vlad-zhukov, @rofrischmann, doesn't renderStatic override the previous styles injected as static ?

**Comment by rofrischmann** [comment]
@aga5tya Nop it doesn't! Should it? No I guess right?

**Comment by lostpebble** [comment]
@rofrischmann I think it logically should not. So it's fine as it is now. Generally static styles are added at the beginning of renderer creation.

I could see an issue arising if you dynamically insert static styles. For example, a dynamic import similar to the one I used above:

```
const styles = await import('react-aspect-ratio/aspect-ratio.css');
renderer.renderStatic(styles.toString());
```

What would happen if this ran in a `componentDidMount()` of a component which is mounted multiple times? The import will be imported once and cached, but I'm guessing the styles be added multiple times to the renderer? Potentially bloating the CSS?

Perhaps this is outside of the scope of fela though.

**Comment by aga5tya** [comment]
> @aga5tya Nop it doesn't! Should it? No I guess right?

@rofrischmann My bad,, It was something wrong with my set up that caused the renderer to override static. Works as expected now.

**Comment by rofrischmann** [comment]
@lostpebble if it’s the same CSS string it will only be added once and cached 👌 you can add as many static styles as possible
