### ISSUE TITLE
[fela-combine-arrays] Plugin seems to break nested selectors output with latest versions.

### ISSUE THREAD

**Issue by aga5tya** [rofrischmann/fela#445]
**Version**: 6.0.3
**Environment**: DOM / Server / Both
**Type**: Bug

Repro commit:
https://github.com/aga5tya/fela/commit/65ef29e88bb6ef2911254a6921391e268ee331a1

![screen shot 2017-10-23 at 12 30 48 am](https://user-images.githubusercontent.com/17351163/31865253-8325ae9c-b789-11e7-97da-c88ff559e7c3.png)

Removing the plugin everything works fine. cc/ @rofrischmann

**Comment by rofrischmann** [comment]
I will check this out soon. No idea why it could happen actually.
