### ISSUE TITLE
Separate @supports and basic rules

### ISSUE THREAD

**Issue by lucasmotta** [rofrischmann/fela#450]
**Version**: 6.0.x
**Environment**: Both
**Type**: Bug

-------------------
#### Description
Hey there,

So after fela added support to `@supports`, we started using in a few places in our application. But we have been experiencing some issues with the order that the `@supports` is added to the page.

Take a look at the example below, it's just a simple demo:
https://codesandbox.io/s/8zmoom681l

And here is the CSS generated:

```css
@supports (display: flex) {
  .e {
    border-bottom: 4px solid red;
  }
}

.f {
  border-bottom: 4px solid black;
}
```

That means that, when those classes are used on the same element, the `.f` will always win (because it is declared after), even thou the desired output was to have the `red` border instead.

#### Proposal
My suggestion would be to always render `@supports` after all the other rules - in most cases, that's the expected behavior. Maybe we could have extra `style` tag on the page, that would handle only the `@supports`:

```html
<style data-fela-type="RULE" type="text/css">
@supports (display: flex) {
.f {
  border-bottom: 4px solid black;
}
</style>
<style data-fela-type="SUPPORTS" type="text/css">
@supports (display: flex) {
  .e {
    border-bottom: 4px solid red;
  }
}
</style>
```

I understand it can get quite complicated, but our application is relatively large and it's very hard for the developer to try to avoid this issue with the order that the rule is added.

**Comment by rofrischmann** [comment]
Ah I see. Was wondering if this would cause a problem actually. It might be a good idea to have separate style sheets actually. would even make rehydration more explicit.
Just don't like the fact that we'd have to add a stylesheet for every media query + supports as well, but I guess it's ok.
