### ISSUE TITLE
background-image path

### ISSUE THREAD

**Issue by lyudad** [rofrischmann/fela#457]
if I set `url("../../media/files.svg") no-repeat 50% 50%`, fela will start path from public folder, not from current folder

**Comment by rofrischmann** [comment]
Could you please try to at least fill out the issue template that's provided? From what I can tell, this is not Fela's issue but default behaviour in CSS. Might be caused by your bundling system or whatever.

**Comment by lyudad** [comment]
when I add to css everything fine. but if you say it not fela - ok, will look for other solution

**Comment by rofrischmann** [comment]
I think it depends on where your path is defined and how the bundler resolves those paths/where the bundler entry point is. I am 100% sure if you add an absolute path, it works as well => not an issue with Fela itself. You could check to which path the plain CSS URL resolves to and just copy that.
