### ISSUE TITLE
fela-plugin-fallback-value@^5.0.13 not found by fela-plugin-prefixer

### ISSUE THREAD

**Issue by bkniffler** [rofrischmann/fela#458]
Tried deploying an update today, got this:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for fela-plugin-fallback-value@^5.0.13
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'fela-plugin-prefixer'
npm ERR! notarget
```

**Comment by rofrischmann** [comment]
Oh wow. Some `npm publish`s seem to have failed without warning :o

**Comment by jglapa** [comment]
when can we expect to re-publish this? I'm not able to run `npm install` right now

**Comment by aga5tya** [comment]
Until published,, you could lock in the version in your package.json dependency and builds go through.
```
"fela-plugin-prefixer": "5.0.12",
```

**Comment by rofrischmann** [comment]
Done.
No idea why and what happened, but 40% of the packages haven't been successfully published, the rest did.

**Comment by aga5tya** [comment]
@rofrischmann: http://registry.npmjs.org/fela-plugin-embedded is still a version older

**Comment by rofrischmann** [comment]
Updated, if anything else, please reach asap.
