### ISSUE TITLE
Support React 16's renderToNodeStream

### ISSUE THREAD

**Issue by Cavitt** [rofrischmann/fela#459]
**Version**: 5.0.x
**Environment**: Server
**Type**: Feature

-------------------
#### Description
Stream styles to the client in a similar fashion to [ReactDOMServer.renderToNodeStream](https://reactjs.org/docs/react-dom-server.html#rendertonodestream).

#### Proposal
Figure out some way to hook into the chunk being streamed to the client and generate a style tag containing only rules that are needed for the components in the chunk.
Assuming atomic rules are being used, do not render duplicate rules if they have been streamed in a previous style tag.

This will allow a huge SSR performance increase, eliminate the FOUC problem, and automatically render the least amount of CSS needed.

**Comment by TxHawks** [comment]
Isn't that pretty much what #337 will do?

Albeit without `renderToNodeStream`, but hard for me to see how that's something Fela should or could be in charge of.

**Comment by Cavitt** [comment]
@TxHawks yes, I did not see that issue. This can be considered a duplicate.

The only difference between your and my proposal was rendering a style tag per chunk of components VS per component.

**Comment by rofrischmann** [comment]
Heyhey. I am already testing stuff with the renderToNodeStream and its in fact related to #337, but I need some time to finish it :P
