### ISSUE TITLE
Dep package version without `^`

### ISSUE THREAD

**Issue by kompot** [rofrischmann/fela#467]
Saw that at least in one place
https://github.com/rofrischmann/fela/blob/master/packages/react-fela/package.json#L31
version is set as `"prop-types": "15.5.8"` which leads to package duplication in `node_modules` tree of user's project that uses `react-fela`.

Would not it be better to always use `^` for direct dependencies so that we have cleaner `yarn.lock`s and smaller bundles?

**Comment by rofrischmann** [comment]
Yeah, I removed the ^ after we had several semver issues (damn, managing a monorepo is hard).
I’d love to get a PR that adds those back if you want to! Got the semver problem fixed pretty soon with a new tool :p

**Comment by kompot** [comment]
Will be happy to do PR, but could not quite grasp the right way to upgrade dependency though.

As far as I understand `fela` uses `lerna` but not using yarn workspaces.

Running `yarn add prop-types@^15.5.8` in `packages/react-fela` leads to adding lots of `fela-*` packages to `packages/react-fela/yarn.lock`. Could you please point to the proper way of upgrading packages?

**Comment by rofrischmann** [comment]
hmm. I was actually doing it manually :/ just adding the ^ to all external deps.

We have an open PR to use yarn workspaces soon, but I'm not deeply into that at all.

**Comment by kompot** [comment]
Well, I guess we should leave this issue opened until workspaces PR is hopefully merged and then upgrade all the deps.
