### ISSUE TITLE
IE 11 Support (extractUsedProps using Proxy)

### ISSUE THREAD

**Issue by odiseo42** [rofrischmann/fela#468]
**Type**: Question

**Versions**:  fela     | 6.0.x   

#### Description
Is Fela striving to support IE11? 

I started using Fela in my project, but found out that is not working on IE11 due its use of `Proxy` in [extractUsedProps.js](https://github.com/rofrischmann/fela/blob/master/packages/fela-utils/src/extractUsedProps.js), which unfortunately is a feature that [is not possible to polyfill](https://stackoverflow.com/questions/45285992/es6-proxy-polyfill-for-ie11).

If IE11 is not supported, can somebody suggest a possible workaround?

**Comment by rofrischmann** [comment]
In general, if you're not using createComponentWithProxy it should be needed, I can add a feature check so your browser doesn't throw.

**Comment by brianespinosa** [comment]
@rofrischmann I love the feature flag check idea.

Additionally, I think it would be good to have a browser support table with a full/partial/none flag. Specifically for `createComponentWithProxy` I think it would be good to have notes on this in docs.

**Comment by odiseo42** [comment]
If that's the case then I guess I can just use `createComponent` and explicitly pass down the props 😁 But for stability I guess a browser check would be nice.
