### ISSUE TITLE
Provider rehydrate true breaks server-side rendering

### ISSUE THREAD

**Issue by tajo** [rofrischmann/fela#469]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela-dom     | 6.0.5   |

-------------------
#### Description
Provider with `rehydrate` prop set to `true` possibly breaks server-side rendering. Needs probably more investigation, details, minimal example.

```
ERROR in TypeError: document.querySelectorAll is not a function
```

**Comment by TxHawks** [comment]
What's the `rehydrate` prop? Can't find any documentation on it

**Comment by rofrischmann** [comment]
It's auto-enabled and won't be required at all soon (rehydration now knows if styles can be rehydrated or not).

Also trying with the latest example-react, I can't reproduce this as we have a `hasDOM()` check to prevent rehydration calls on the server.

**Comment by tajo** [comment]
> Also trying with the latest example-react, I can't reproduce this as we have a hasDOM() check to prevent rehydration calls on the server.

In my project, I am actually doing some mocks in SSR (*facepalm*):

```js
globals: {
  document: {},
  window: { location: { hash: { substr: () => '' } } }
}
```

which actually passes `hasDom` test. How about more robust check:

```js
const hasDom = !!(
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement
);
```

**Comment by rofrischmann** [comment]
Oh thats it! Feel free to send a PR!
