### ISSUE TITLE
Native-base and theme key in context

### ISSUE THREAD

**Issue by wcastand** [rofrischmann/fela#474]
**Type**: Bug / Question

We are using native-base for our react-native app alongside fela and we have a problem with the ThemeProvider.

ThemeProvider uses the key `theme` in the context but since it's not scope with something like `fela_theme`. it gets mixed with the theme key from native-base.

I inform native-base team of the problem since neither fela or native-base provide a way to change this keyName.

Fela is at the "root" of styling, so scoping the key in the context seems a good way to avoid further conflicts with libraries. Do you think it could be done or it will bring a lot of problem to fela ?

the issue on native-base : https://github.com/GeekyAnts/NativeBase/issues/678

**Comment by rofrischmann** [comment]
I guess @HugoGiraudel was proposing a customizable key name anyways! Sounds like a fair way to solve it.

**Comment by wcastand** [comment]
I don't mind a customizable key, just like a lot more work than just scoping the key in a first time :)

**Comment by wcastand** [comment]
fixe din #475
