### ISSUE TITLE
Integrating Elodin/Bredon

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#484]
**Type**: Feature

| Packages | Version |
| -------- | ------- |
| fela | 6.0.x |
| babel-plugin-fela | 1.x.x |

-------------------
#### Description
For further precompilation optimisations, preprocessing, style minification and style linting/validation, I am working on [bredon](https://github.com/rofrischmann/bredon). To further simplify the usage of Bredon, I created [elodin](https://github.com/rofrischmann/elodin) with primary support for style objects. 

#### Proposal
It would be great to have a way to integrate bredon/elodin into fela. The simplest way would be a plugin. This could then also be used for precompilation. (Using bredon/elodin on runtime is not really recommended as it's not built for performance even though it's quite small).

**Comment by TxHawks** [comment]
May be a stupid question, by why a plugin and not integrate it as part of the existing Babel plugin?

And a clarification, question - when you say `plugin` in this case, do you mean another Babel plugin, or an actual Fela plugin?

**Comment by rofrischmann** [comment]
Oh, I might be unclear here. I am talking about a Fela plugin, not another Babel plugin.
The Babel plugin is able to precompile using all Fela plugins, so we don't really need to integrate directly into babel-plugin-fela.

Might also be cool for dev to have the plugin running in the client as well.

**Comment by TxHawks** [comment]
My worry about it being an actual Fela plugin is that it's another thing to remember (and thus, forget) to strip away from the production bundel

**Comment by rofrischmann** [comment]
What if it does nothing in prod and thus gets removed by the bundler by default?

**Comment by TxHawks** [comment]
Tree shaking is hard and works a little different in every bundler. Relying on it to work as expected is not as safe as one would want it to be. The lodash babel plugin exists for a reason

**Comment by rofrischmann** [comment]
Closing this for now. I got 0 time to work on bredon and/or elodin atm and I also more and more feel like JS is simply too dynamic to do compile-time optimisations of that type...
