### ISSUE TITLE
Prevent ever-growing stylesheet

### ISSUE THREAD

**Issue by johanneslumpe** [rofrischmann/fela#49]
At the moment our stylesheet will keep growing the more selectors we render. We should investigate if this becomes an issue and if so, how we can prevent this and maybe update selectors in-place instead of just adding new ones.

**Comment by steida** [comment]
Why not leverage componentWillMount and componentWillUnmount methods?

**Comment by rofrischmann** [comment]
@steida First of all, this is a general "issue" (not really an issue though) so we're not only talking about the React world.

Also we would have to track the number of rendered components to safely remove classes only if the last instance gets unmount. A component that shares the same Fela rule might be rendered multiple times. But if you remove the class (especially the static one) if the first gets unmount, the others would loose there style.

It might not be a problem to track instances at all, but I don't see any advantage as well. I had no problem with growing stylesheets in any of my projects.

**Comment by steida** [comment]
I see, can you explain please when exactly to stylesheets grows? For example, wrong usage in animation?

**Comment by rofrischmann** [comment]
@steida Yeah exactly. e.g.
```javascript
const rule = props => ({
  position: 'absolute',
  // assuming it passes the scrollTop on every 'scroll' event
  top: props.scrollTop
})
```

Another one would be: Having sth. like a parallax page with 10000 elements and a lot of dynamic rendering on run-time. You might get thousands of classes though only 100 are used at the same time.
This is nothing that only happens to Fela, but is even more problematic with static CSS files. 

We might want to have some options for the user to decide when to terminate styles, but yet I do not see any advantage yet. :P

**Comment by steida** [comment]
> Also we would have to track the number of rendered components to safely remove classes only if the last instance gets unmount.

That's what we need to do I suppose.

**Comment by rofrischmann** [comment]
I guess we need to check if this is performant at all, compared to just keep the styles.

**Comment by steida** [comment]
I think it's the right behaviour anyway. When any component is removed, its style should be removed as well.

**Comment by rofrischmann** [comment]
You cannot treat CSS classes same as components. As every component instance is 1-1 relation while CSS classes are 1-many. So we can only safely remove the class if the last component instance using that class is unmount. (Though I guess that's what you meant anyways)
