### ISSUE TITLE
Deterministic Atomic Classes

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#493]
**Type**: Improvement

| Packages | Version |
| -------- | ------- |
| fela     | 6.0.x   |

----- 

#### Proposal
Right now, Fela generates really small atomic class names by simple incrementing a single counter. This leads to insane class name generation and minimal markup size. Yet it is not deterministic and might collide if multiple Fela renderer are used which is far from perfect.

We might consider using a fast hashing algorithm, to generate uniques hash values for a given class reference. This would make style rendering pure and rehydration much simpler and more stable.
One downside might be a performance impact due to the cost of hashing as well as much more bloated class names.

We could also think about having both ways using enhancers and encapsulating the class name generation into a single renderer method which can be replaced (as we already do it with the monolithic renderer)

**Comment by TxHawks** [comment]
I think it's worth benchmarking, but if it's a big performance hit it doesn't seem to be worth it to me

**Comment by rofrischmann** [comment]
I just did some really small benchs and it's about 3.5x slower than the default one, and like 10x slower if I "beautify" the className using `.toString(36)` to make it shorter.

This sounds like a lot, but actually it's only about the generation, excluding cache checks and actual DOM rendering etc. We're speaking about 800,000 operations vs. 3,500,000 operations per second.
In real world applications this wouldn't affect performance at all, especially because ~80% of the cached  classNames can be reused anyways, so in most cases the generation is not even triggered.

Will later test both implementations with a real world example to test actual performance differences.

**Comment by jacobrask** [comment]
Could you describe the difficulties that led to you abandoning this? Is there some work in the closed PR's that we could resume?

If I understand the current implementation correctly I think it will be difficult to get it to work with React concurrent mode which can pause and resume rendering of the tree.

I have done some experiments with progressive rehydration but the current incremental class name generation approach makes it difficult for the same reason.

The monolithic enhancer should work for both use cases though, but it has other drawbacks of course.
