### ISSUE TITLE
Reuse markup from server rendering in client

### ISSUE THREAD

**Issue by dustin-H** [rofrischmann/fela#50]
Actually when rendering fela styles on the server, the new created fela renderer overwrites the styles which are already in DOM.

This causes the browser to rerender all styles which leads to a slight flash of the hole window, because the styles disappear and appear again.
This is quiet annoying.

So in my opinion a solution would be to create two methods in `renderer` which can export/import the renderer state.

Cheers
Dustin

**Comment by johanneslumpe** [comment]
@dustin-H You are right! A way to hydrate the client-side renderer is already on the todo list :)

**Comment by dustin-H** [comment]
Thanks @johanneslumpe, I will try to implement this tomorrow morning.

**Comment by rofrischmann** [comment]
@dustin-H and I found out we actually do not have to reuse those styles for SSR as the renderer can just rehydrate and (only if styles changed) update on componentDidMount.
