### ISSUE TITLE
how to integrate with gatsby

### ISSUE THREAD

**Issue by mmintel** [rofrischmann/fela#505]
Hey,

I'd like to integrate fela with gatsby. There is an officially supported JSS plugin for gatbsy that seems pretty simple, see here: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-jss/src.

Only two files to add `gatsby-browser.js` and `gatsby-ssr.js`. Although I think fela works a little bit different than JSS? But setup should be pretty similar.

My `gatsby-browser.js` looks like this:
```JS
import { Provider, ThemeProvider } from 'react-fela'
import React from 'react'
import { Router } from 'react-router-dom'
import { createRenderer } from 'fela'
import theme from './theme';

const renderer = createRenderer()

exports.replaceRouterComponent = ({ history }) => {
  const ConnectedRouterWrapper = ({ children }) => (
    <Provider renderer={renderer}>
      <ThemeProvider theme={theme}>
        <Router history={history}>{children}</Router>
      </ThemeProvider>
    </Provider>
  )

  return ConnectedRouterWrapper
}
```

And my `gatsby-ssr.js` looks like that:
```JS
import React from "react"
import { renderToString } from "react-dom/server"
import { createRenderer } from 'fela'
import { renderToMarkup } from 'fela-dom'

exports.replaceRenderer = ({
  bodyComponent,
  replaceBodyHTMLString,
  setHeadComponents,
}) => {
  const renderer = createRenderer()
  const bodyHTML = renderToString(bodyComponent);
  const styleMarkup = renderToMarkup(renderer)
  replaceBodyHTMLString(bodyHTML)
  setHeadComponents([styleMarkup])
}
```

It's working fine with `gatsby develop` (although HMR is not working when changing fela styles), but I am getting an error on `gatsby build`: `Cannot read property 'renderRule' of undefined`.

I think a gatsby plugin could really improve the popularity of fela, so might be worth a look :) I'd take care of that if someone could help me out. Maybe someone is already using fela with gatsby?

**Comment by rofrischmann** [comment]
Heyhey. I haven't checked Gatsby for a while, but I was using Fela with an older Gatsby version where Glamor was kind of build in.

I try to find that and give you some advice, but I guess I need to check the Gatsby APIs first. Maybe @KyleAMathews got an idea here?

**Comment by mmintel** [comment]
Yes in the example you provide in the fela docs for SSR you pass the renderer as a property into the app component, but I am not sure how to do that with gatsby. I think it's possible via `setBodyProps` method from gatsby, will try that later.

**Comment by rofrischmann** [comment]
Oh yeah, that example is pretty straight forward. You should definitely use the `<Provider>` component to pass the renderer via context. I guess that's somehow the problem here. If you'd be able to create a simple example repo with the exact problem, it would help a lot to debug.

**Comment by mmintel** [comment]
Created an example repo over here: https://github.com/mmintel/example-gatsby-fela

**Comment by mmintel** [comment]
@rofrischmann I think I've got it and updated the example repo! :) Maybe you could have a look at it before I will release a gatsby plugin with that code.

**Comment by mmintel** [comment]
@rofrischmann already published the plugin here: https://www.npmjs.com/package/gatsby-plugin-fela

Should close this here now and open issues on the plugin repository instead.

**Comment by rofrischmann** [comment]
Yeah nice, would you mind adding it to the Ecosystem and README page here?
