### ISSUE TITLE
fela-plugin-extend converts null values to empty objects

### ISSUE THREAD

**Issue by wagerfield** [rofrischmann/fela#525]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela | 6.1.4 |
| fela-plugin-extend | 6.0.3 |

-------------------
#### Description

I have created a repo to demo the issue:

https://github.com/wagerfield/fela-extend-issue

The `extend` plugin will convert any `null` value to an empty object `{}`.

#### Steps to reproduce

```js
import { createRenderer } from 'fela'
import logger from 'fela-plugin-logger'
import extend from 'fela-plugin-extend'

const renderer = createRenderer({
  plugins: [
    extend(),
    logger()
  ]
})

const rule = ({ setColor, setBlock }) => ({
  color: setColor ? 'red' : null
  extend: {
    display: setBlock ? 'block' : null
  }
})

renderer.renderRule(rule, {
  setColor: true
  setBlock: true
}) // RULE { color: 'red', display: 'block' }

renderer.renderRule(rule, {
  setColor: false
  setBlock: false
}) // RULE { color: null, display: {} }
```

#### Expected Behavior

For the second renderRule call above I would expect the style to be:

```javascript
renderer.renderRule(rule, {
  setColor: false
  setBlock: false
}) // RULE { color: null, display: null }
```

**Comment by rofrischmann** [comment]
Oh, interesting! Never happened to see that before. What happens if you use `undefined` instead of `null`?

Another quick fix would be to do `color: setColor && 'red'` as undefined values get filtered out automatically, or do you explicitly want to have the `null`?

**Comment by wagerfield** [comment]
If you set the value to `undefined` rather than `null` it works as expected: values within `expect` blocks get properly set to `undefined` and then automatically removed by Fela.

Your solution above using `&&` will work when the passed prop is undefined, but there are many cases where you might want to perform the logic of optionally setting a property based on a prop that isn't undefined like:

```js
const rule = ({ type }) => ({
  block: type === 'awesome' ? 'block' : null
})
```

In the example above, `type` could be any arbitrary value, but could have a value that isn't `undefined` yet fails the ternary condition.

Though I can use `undefined` within these ternaries, I would rather use `null` since `null` is an actual value whereas `undefined` is not. Having the `extend` plugin convert `null` to an empty object is a bug IMO since it is unexpected behaviour.

I would really like this fixed so that `null` values remain `null` so I can use a plugin like the one in the repo I shared above to remove `null` values in the same way that Fela automatically does with `undefined` values.

**Comment by rofrischmann** [comment]
Yeah I get your point. Apart from that, of course it's a bug. If you'd be open to fix it (I can help out ofc), it'd be great. Otherwise it might take some time.

Btw. do you think Fela should remove `null` just like it removes `undefined` values?

**Comment by wagerfield** [comment]
Since there are no `null` CSS values (that I know of) I think that removing them in same way that Fela does with `undefined` values is probably the right thing to do. I will first take a look at fixing the extend plugin and then have a look at automatically pruning `null` values in Fela's core (I assume that's where it is). If you could point me to the relevant file(s) where `undefined` values are automatically removed, that would be helpful. Assuming I can fix the extend plugin bug, I will put in a PR shortly.

**Comment by rofrischmann** [comment]
Here we go: https://github.com/rofrischmann/fela/blob/master/packages/fela-utils/src/isUndefinedValue.js

As soon as the extend plugin is fixed, this should do the job, but I guess the problem is: https://github.com/rofrischmann/fela/blob/master/packages/fela-plugin-extend/src/index.js#L9 
`isPlainObject` returns `true` for `null` as `null` has an `'object'` type... Should use sth. like

```javascript
function isPlainObject(obj: any): boolean {
  return obj !== null && typeof obj === 'object' && !Array.isArray(obj)
}
```

We could even go further and replace all `isPlainObject` helper (using them in a lot of packages), with [isobject](https://github.com/jonschlinkert/isobject) (not to be confused with [is-object](https://github.com/ljharb/is-object)), but that requires adding it to all using packages etc.

**Comment by TxHawks** [comment]
Why not just 

```js
function isPlainObject(obj: any): boolean {
  return obj && typeof obj === 'object' && !Array.isArray(obj)
}
```

**Comment by rofrischmann** [comment]
Oh yeah its fine to commit that, I copy the README to the packages/fela directory in order to have it on npm as well.

**Comment by rofrischmann** [comment]
I just fixed this while porting all the isPlainObject, hope you didn't already do that as well :/ https://github.com/rofrischmann/fela/pull/530

**Comment by wagerfield** [comment]
Awesome—thanks for fixing that!

...and nope—didn't get round to having a go myself, so no time wasted on my end :)

I just looked over the commit and commented on what I believe to be an error in the `isUndefinedValue` util function in `fela-utils`.

Looks like you accidentally wrapped `null` in quotation marks (`'null'`) where it should just be be `null`. Pretty sure this is an error.

Also I think that `isUndefinedValue` should perhaps be renamed to `isNilValue` since it is checking for more than just `undefined`—but that's just my opinion :)

**Comment by rofrischmann** [comment]
Yeah the naming could be changed, the stringified null has already been fixed though ;)

**Comment by wagerfield** [comment]
Thanks again for fixing this!

I'll say it again—Fela is freaking awesome man—deserves 10x the GH stars it currently has. Really enjoying using it and have been singing its praises to every dev I know.

Any idea when these updates will be finding their way onto NPM?

**Comment by rofrischmann** [comment]
Hahaha, thanks man! I appreciate any help promoting it ;) 
But I don't really care about the stars too much. Most important is that it helps ppl to build maintainable software with joy and happiness :)
