### ISSUE TITLE
react-fela: Initial render missing CSSRules because of `componentDidMount`

### ISSUE THREAD

**Issue by hkjorgensen** [rofrischmann/fela#532]
**Type**: Bug / ~Feature~ / ~Infrastructure~ / ~Docs~ / ~Question~

| Packages | Version |
| -------- | ------- |
| fela     | 6.1.4   |
| react-fela | 6.2.4 |

-------------------
#### Description
react-fela offers a provider to wrap around a react render tree. [The provider relies on the hook `componentDidMount`](https://github.com/rofrischmann/fela/blob/master/packages/fela-bindings/src/ProviderFactory.js#L28-L32). Relying on the `componentDidMount` has some drawbacks. The initial rendered HTML has all the Fela generated class names - but the stylesheet is missing. I imagine this could lead weird rendering flashes for some people. I didn't notice this until debugging the following issue.

Imaging the following application tree:
```jsx
const App = () => (
  <Provider>
    <MyComponent />
  </Provider>
)
```

MyComponent:
```jsx
const Title = createComponent(() => ({ padding: '10px' }), h1)

class MyComponent extends Component {
  componentDidMount() {
     // perform operation that relies on measuring the rendered HTML.
  }
  render() {
     return <Title>Hello world</Title>
  }
}
```

There is a problem because of the order `componentDidMount` is called with React. Childrens `componentDidMount` is called before parents. This is the order:
1. `<MyComponent />` -> `componentDidMount`
2. `<Provider />` -> `componentDidMount`

At the time `<MyComponent />` -> `componentDidMount` is called there are no Fela CSSRules available in the DOM and any measuring is likely to be invalid. In this case, `<MyComponent />` should wait for the `<Provider />` to invoke the `componentDidMount` that will do the initial render and add CSSRules to the DOM. That would be another Fela specific hook and not ideal.

React components depending on `componentDidMount` for measuring rendered HTML are common for animations and tools like [react-textarea-autosize](https://github.com/andreypopp/react-textarea-autosize/blob/master/src/calculateNodeHeight.js)

Any rule changes after the first/initial render are o.k. because the `<style />` has been inserted into the DOM and Fela renders happens immediately.

#### Proposal
A potential solution is moving the first render call to either the `constructor` or to the [`componentWillMount`](https://reactjs.org/docs/react-component.html#componentwillmount). According to the React Docs, componentWillMount might not be the right solution. I don't see any downside to do the initial render before mounting.

❤️ Thanks to @rofrischmann and everyone else who contributed - I love Fela and Fela's approach styling!

**Comment by rofrischmann** [comment]
So you're not using SSR, am I right? As it would rehydrate the style.
componentWillMount is possible if you're only on the client, but using it on the server would throw as `render(renderer)` from `fela-dom` requires an actual DOM. We could add the same check to willMount as well, so if you're only rendering on the client, is injects the style on willMount, but if you're rendering on the server it won't throw.

Doing it in the `constructor` would have one downside. Every rule would be injected separately, while onDidMount (and willMount) we can inject all styles at once.

**Comment by hkjorgensen** [comment]
@rofrischmann 
> So you're not using SSR, am I right? As it would rehydrate the style.

Correct, the current project is not using SSR.
Correct, if using SSR the issue mentioned above wouldn't happen :-)

My proposal would be to 

ProviderFactory.js
```patch
- componentDidMount(): void {
+ componentWillMount(): void {
    if (this.props.renderToDOM && hasDOM(this.props.renderer)) {
      render(this.props.renderer)
    }
  }
```

The [`hasDOM()`](https://github.com/rofrischmann/fela/blob/master/packages/fela-bindings/src/ProviderFactory.js#L5-L12) helper would guard it against trying to render server-sider. How does that sound @rofrischmann ?

I use on all projects, most notably at Zendesk where we use it in the main product. I'll add it to the list!
