### ISSUE TITLE
createComponent wrapping createComponentWithProxy passes through unwanted props

### ISSUE THREAD

**Issue by dlee** [rofrischmann/fela#538]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 6.0.x   |

-------------------
#### Description
Wrapping a component created by `createComponentWithProxy` with `createComponent` bleeds all properties into the DOM element, regardless of the `passThroughProps` declared in `createComponent`

#### Steps to reproduce
```javascript
const BorderlessButton = createComponentWithProxy(() => ({
  border: 'none'
}), 'button');

const ColoredButton = createComponent(({color}) => ({
  color
}), BorderlessButton);

render(
  <ColoredButton color="red" />
);
```

#### Expected Behavior
```html
<button class="a b"></button>
```

#### Actual Behavior
```html
<button color="red" class="a b"></button>
```

**Comment by rofrischmann** [comment]
Alright, these HoCs are driving me mad 😅
I'm experimenting with some major changes that will reduce the complexity and issues with those by simply replacing all HoCs entirely (providing a codemod of course).

**Comment by kserjey** [comment]
When you plan to release that?

**Comment by rofrischmann** [comment]
Alright, so we decided to not fix this one as it creates issues with other use cases.
We recommend not wrapping both HoCs together at all or using FelaComponent.

We will release improved APIs sometime in November.
