### ISSUE TITLE
Feature request: Switch between `node.textContent` and `insertRule` using flag

### ISSUE THREAD

**Issue by jmike** [rofrischmann/fela#544]
Hey guys, this might sound weird, but here goes...

I am using fela-dom in production. My client wants to use an analytics tool called HotJar (https://www.hotjar.com), which provides heatmaps and usage recordings. Unfortunately hotjar doesn't support `CSSStyleSheet.insertRule`, resulting to garbage data.

That said, I'd be great if we could switch between `node.textContent` and `insertRule` with a simple flag instead of the `NODE_ENV` environmental variable. I realise this is sheer stupidity, but sometimes you want to consciously hamstrung performance in favour of something else (in my case: valuable analytics).

Here's how this could look like...

**Code Example**:
```javascript
const felaRenderer = createRenderer({
  plugins: [
    ...
  ],
  dev: true
});
```

**Comment by jmike** [comment]
btw here's a related issue with styled-components: https://github.com/styled-components/styled-components/issues/1603

**Comment by jaggli** [comment]
Struggling with hotjar, since a while now. This is so much needed.

**Comment by jmike** [comment]
Here's hotjar's official response to this issue...

```
Hi Dimitris,

Thanks for your patience!

I just had a word with our engineers and they let me know that fela.js is indeed the reason why your recordings are not displaying correctly. 

Because this has to do with the way we handle the insertRule() API, they let me know that you could get this to work by running fela.js in Development mode on your site as we will capture the CSS then, since it doesn’t use insertRule(). See: http://fela.js.org/docs/advanced/DOMRendering.html

Hope that cleared things up! 
```

**Comment by jaggli** [comment]
For those who can not wait, I made an ugly but working hack. After some intense trial and error, I ended up by just synchronising the grabbed styles into the beginning of the <head> tag, so the following 'real' ones still can override everything. Synchronization is done twice per second by using getAnimationFrame(), so this might result in a style-update delay in Hotjar recordings of max 500ms, which we are ok with.

Check out the first file in [this gist](https://gist.github.com/jaggli/5b2141c60cef3095a51661bac96de183#file-1_hotjarfix-js)

**Comment by rofrischmann** [comment]
We'd be happy to accept an PR that adds this functionality.
It's not a general issue with Fela, so I can't allocate time for it right now.

**Comment by stephenpitchford** [comment]
This shouldn't be a problem with the Hotjar tracking anymore. A change was released that allows the script to deal with styles added using insertRule.

**Comment by TxHawks** [comment]
@stephenpitchford Any chance you can share a link to the changelog or relevant announcement?

Thanks

**Comment by stephenpitchford** [comment]
@TxHawks Unfortunately there isn't any official changelog or announcement with this change noted in it.

**Comment by TxHawks** [comment]
@stephenpitchford so how did you find out about it?

**Comment by rofrischmann** [comment]
@stephenpitchford Thanks for reaching out! Seems like we can close this one then. I'd like to reduce options and complexity as much as possible =)
