### ISSUE TITLE
Fonts are reloading with each styles update

### ISSUE THREAD

**Issue by dustin-H** [rofrischmann/fela#55]
When using custom fonts, Chrome tries to reload them each time the mountNode gets updated.

This happens for example when using a custom font in a React Component A. When another component gets mounted with new styles, the renderer triggers an update of the mountNode. This replaces all css and forces the browser to refetch the fonts and rerender all text on the website. The user can see this as slight flash of the hole screen (when some Text is on the page).

Maybe fonts should get rendered in a different way.

**Comment by rofrischmann** [comment]
I added the issue to the troubleshooting section of the documentation as I am not sure how to handle this properly right now. Thanks!
