### ISSUE TITLE
Will Fela adhere to ISTF spec?

### ISSUE THREAD

**Issue by rayronvictor** [rofrischmann/fela#557]
**Type**: Question

-------------------
#### Description
Is there any plan to adhere to the [ISTF spec](https://github.com/cssinjs/istf-spec)?

**Comment by rofrischmann** [comment]
Probably as soon as the work's done building a compiler and so on. Right now, I don't plan to add any of that to Fela's core directly.

(Not because I don't like the idea, but because it'd be a lot of work and I simply don't have any time anyways)
