### ISSUE TITLE
FelaComponent does not concatenate the passed className

### ISSUE THREAD

**Issue by kitce** [rofrischmann/fela#558]
**Type**: Feature

| Packages | Version |
| -------- | ------- |
| fela     | 6.1.7   |
| react-fela | 7.2.0 |

-------------------
#### Description
By using `FelaComponent` as an alternative of `createComponent`, I found that `FelaComponent` does not concatenate the `className` prop given by parent element.

#### Proposal
Make `FelaComponent` to accept `className` so that the parent element can pass extra styles to `FelaComponent`.

**Code Example**:
```javascript
const borderedText = (props) => {
  return {
    color : props.color || 'blue',
    borderStyle : 'solid',
    borderWidth : 2
  };
};

// the `createComponent` way:
const BorderedText = createComponent(borderedText);
<BorderedText className="custom-class-name" color="red">I am red</BorderedText>
// => "custom-class-name a b c"

// the `FelaComponent` way:
<FelaComponent rule={borderedText} className="custom-class-name">I am blue</FelaComponent>
// => "a b c"
```

**Comment by kitce** [comment]
I know there is always a way to solve a problem, but it could have more clean code by implementing in this way, and even get rid of the custom prop/variable names:

```
const MyComponent = ({className, children}) => (
  <FelaComponent 
    className={className}
    rule={ruleFn}
    render={
      ({className}) => (
        <div className={className}>
          {children}
        </div>
      )
    }
  />
)

<MyComponent className="custom-class-name">
  I am blue
</MyComponent>
// => <div class="custom-class-name a b c">I am blue</div>
```

**Comment by rofrischmann** [comment]
I think it would be nice to concatenate classNames' as I often use the shorthand version:

```javascript
<FelaComponent style={...}>Foo</FelaComponent>

// <div class="...">Foo</div>
```

Using that with third-party classes seems like a massive use case to some.

**Comment by TxHawks** [comment]
I'll take care of it over the weekend

**Comment by TxHawks** [comment]
But how about using a different name for this prop? I just think the shadowwing could be confusing when people do use the render prop pattern:

```jsx
<FelaComponent
  className="custom-class-name"
  style={...}
  render={(className, theme) => ... }
/>
```

It can be a bit confusing that `className` inside the function isn't actually the same as the `className` prop.

Maybe call it something else that will be a bit more explicit? Best I can come up with is `customClass`, but happy to take other suggestions.

**Comment by TxHawks** [comment]
The pull request is ready at #560. It currently uses a `customClass` prop, but I'm happy to change that if there is consensus that `className` (or anything else) is better
