### ISSUE TITLE
The problem with responsive

### ISSUE THREAD

**Issue by MICHAspb** [rofrischmann/fela#569]
Not correctly reads specified screen sizes.
in head exhibited sizes 992px and then only 768px. As I understand it should be the opposite
Аccordingly, the same behavior on the page. 

how to solve the problem?

**Comment by TxHawks** [comment]
I'm not sure I understand what you mean. Can you point me to a code example?

**Comment by MICHAspb** [comment]
https://github.com/MICHAspb/test/tree/master/src/Content  -  this section.

When you change the screen size, styles for screen 992px do not apply. Uses styles for screen size 768px.

Errors in the code have not noticed.

**Comment by rofrischmann** [comment]
Looks like you have to configure the media query order. See http://fela.js.org/docs/advanced/RendererConfiguration.html for more information.
e.g.
```javascript
const renderer = createRenderer({
  mediaQueryOrder: [
    '(min-height: 768px)',
    '(min-height: 992px)'
  ]
})
