### ISSUE TITLE
Incompatibility with recompose withPropsOnChange, maybe due to hoisting getDerivedStateFromProps

### ISSUE THREAD

**Issue by bkniffler** [rofrischmann/fela#571]
Latest recompose introduced getDerivedStateFromProps and it causes issues with withTeme decorator.

Here is a simple example:
https://github.com/bkniffler/fela-recompose-issue

Maybe we could have https://github.com/mridgway/hoist-non-react-statics instead of the custom hoisting function?

**Comment by rofrischmann** [comment]
Did you try if that actually fixes the problem? If so, would you mind sending a PR to alter the current code? (I'd not like to use hoist-non-react-statics, as we also serve Preact and Inferno, which don't need all the settings over there)
