### ISSUE TITLE
Make fela-plugin-rtl initializer return a named function

### ISSUE THREAD

**Issue by danielstocks** [rofrischmann/fela#578]
**Type**: Feature

| Packages | Version |
| -------- | ------- |
| fela-plugin-rtl     | 1.0.6   |
| fela-plugin-unit | 5.0.17 |

-------------------
#### Description
I'm trying to add/remove plugins dynamically from the renderer. In this case it's because i need to toggle RTL rendering for react components in a storybook.

Since the plugins are just an array of functions, the easiest way to pop the right one is to look at the function name. This works for most plugins as they are named functions. fela-plugin-rtl and fela-plugin-unit exports anonymous functions. 

Doing a `console.log(renderer.plugins);` looks like this in chrome:

![screen shot 2018-06-19 at 09 00 37](https://user-images.githubusercontent.com/52788/41581774-e43f3aa4-739f-11e8-9596-3eea3701965f.png)

the two last functions are `fela-plugin-rtl` and `fela-plugin-unit`. It would be nice of these could be named `rtl´ and ´unit´ or something similar.

#### Proposal
I'm assuming that giving a name to the functions being returned here:

https://github.com/rofrischmann/fela/blob/master/packages/fela-plugin-unit/src/index.js#L52
and here:

https://github.com/rofrischmann/fela/blob/master/packages/fela-plugin-rtl/src/index.js#L10

would be a ideal solution.

Or maybe, there is a better/simpler way to dynamically load/unload plugins from fela at runtime. If so, please point me in the right direction!

Thanks.

**Comment by rofrischmann** [comment]
Heyo!

Do you need to rerender everything after updating the plugins? Or just silently switch out the plugins?
Going by name doesn't feel very safe to me (although, if only for storybook, it's totally plausible :P)

**Comment by danielstocks** [comment]
So I was able to solve this by assigning a faux name property to the rtl plugin.

But yeah i agree it's probably not a very good long term solution. I will open a new issue with the "real" issue which is about being able to switch out plugins.

**Comment by rofrischmann** [comment]
Alright! We could create an enhancer that enables reloading plugins and rerenders everything, because simply replacing the plugins won’t reevaluate all the styles.

Btw, off topic: just found your managing vcc-ui on npm (explored fela’s dependants). Are you working at Volvo? Would love to add it to the “Users” list ;)
