### ISSUE TITLE
react-fela: componentWillMount is unsafe React.StrictMode

### ISSUE THREAD

**Issue by mfdj** [rofrischmann/fela#589]
**Type**: ~Bug~ Improvement 

| Packages | Version |
| -------- | ------- |
| react-fela     | 7.1.0   |
| fela     | 6.1.5   |

-------------------
#### Description

Promoting this comment to an issue https://github.com/rofrischmann/fela/issues/532#issuecomment-380403527:

> As per 16.3, componentWillMount is entering deprecation phase in favor of componentDidMount.
>
> Right now, it means it is not realistically possible to use React.StrictMode in a codebase using Fela because it produces a swarm of warnings.

#### Steps to reproduce

1. Enable [React.StrictMode](https://reactjs.org/docs/strict-mode.html)
2. Implement a component using `createComponent` from react-fela
3. Build the app

#### Expected Behavior
No errors output.

#### Actual Behavior
Errors will be output:
```
"Warning: Unsafe lifecycle methods were found within a strict-mode tree:

componentWillMount: Please update the following components to use componentDidMount instead: FelaComponent
```

**Comment by rofrischmann** [comment]
It's not actually a bug, but a known issue with never React versions. Anyways, it should work as expected for now. We're working on a rework of all the bindings to support newer React features soon :)
