### ISSUE TITLE
fela-plugin-named-keys not rendering <style> tags in the correct order.

### ISSUE THREAD

**Issue by fersalas** [rofrischmann/fela#594]
**Type**: Bug / Feature / Infrastructure / Docs / Question

| Packages | Version |
| -------- | ------- |
| fela     | 6.1.x   |
| fela-plugin-named-keys     | 1.0.x   |
-------------------
#### Description
`<style>` tags generated by fela containing media queries are generating in an incorrect order. This makes media queries overlap.

#### Steps to reproduce
Apply this object of named media queries using `fela-plugin-named-keys`.
```javascript
const customKeys = {
  medium  : '@media (min-width: 640px)',
  large       : '@media (min-width: 1024px)',
  xlarge     : '@media (min-width: 1200px)',
  xxlarge   : '@media (min-width: 1368px)',
};

const renderer = createRenderer({
  plugins: [ namedKeys(customKeys) ]
  . . .
});
```
Then use them in a component:

```javascript
const rule = () => ({
  width: "100px",
  medium: {
    width: "200px",
  },
  large: {
    width: "300px",
  },
  xlarge: {
    width: "400px",
  }
});

export default createComponent(rule, Component);
```

#### Expected Behavior
Should compile as:
```html
<style data-fela-type="RULE" type="text/css"></style>
<style data-fela-type="RULE" type="text/css" media="(min-width: 640px)"></style>
<style data-fela-type="RULE" type="text/css" media="(min-width: 1024px)"></style>
<style data-fela-type="RULE" type="text/css" media="(min-width: 1200px)"></style>
```

#### Actual Behavior
Actually compiles as:
```html
<style data-fela-type="RULE" type="text/css"></style>
<style data-fela-type="RULE" type="text/css" media="(min-width: 640px)"></style>
<style data-fela-type="RULE" type="text/css" media="(min-width: 1200px)"></style>
<style data-fela-type="RULE" type="text/css" media="(min-width: 1024px)"></style>
```
This makes the element apply `width: 300px` (large breakpoint) value over `width: 400px` (xlarge breakpoint) value.

I tried moving `large` and `xlarge` properties around the `customKeys` object to see if that affected it somehow and it didn't work. I haven't been able to add more specificity to work around this.

*NOTE:* I changed the names of `customKeys` object properties to:

```javascript
export const namedKeys = {
  tablet  : '@media (min-width: 640px)',
  desktop   : '@media (min-width: 1024px)',
  extDesktop  : '@media (min-width: 1200px)',
  xExtDesktop : '@media (min-width: 1368px)',
};
```

This way it compiles correctly, but since we're moving a lot of code to fela that already uses other variable names for breakpoints, I'd like to keep the same name.

**Comment by rofrischmann** [comment]
Looks like you'd need to apply a `mediaQueryOrder` too. Check out the documentation:
http://fela.js.org/docs/advanced/RendererConfiguration.html
