### ISSUE TITLE
fela-monolithic with prettySelectors: true doesn't escape characters in displayName

### ISSUE THREAD

**Issue by Nitive** [rofrischmann/fela#596]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela | ^6.1.9 |
| fela-dom | ^7.0.9 |
| fela-monolithic | ^5.0.23 |
| react-fela | ^7.3.1 |

-------------------
#### Description
`fela-monolithic` with `prettySelectors: true` doesn't escape characters in class name such as parenthesis.

#### Steps to reproduce

1. Create component
2.  Add displayName with symbols which needs to be escaped in class name (e. g. parenthesis)
2. Use createComponent to add styles

[repository with minimal reproducable example](https://github.com/Nitive/fela-display-name-bug)

#### Expected Behavior
displayName is escaped

#### Actual Behavior
displayName is not escaped

**Comment by rofrischmann** [comment]
Heyhey, thanks for reporting!
Would you like to send a PR fixing the issue? I may guide to the correct code snippets and help out if required.

**Comment by Nitive** [comment]
@rofrischmann done!
