### ISSUE TITLE
fela-monolithic not rendering styles

### ISSUE THREAD

**Issue by JZBo** [rofrischmann/fela#600]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela-dom   | 8.0.0   |
| react-fela     | 8.0.0   |

-------------------
#### Description
Greetings. 
I have been using fela in an ongoing electron application project together with react (16.X), electron (2.X), redux (4.X), babel (6.X) and webpack (4.X), and have had no special issues so far. On the contrary, fela is my favourite CSS in JS package.
However, after the 15/08/2018 upgrade to the packages listed above, I had a breaking bug that I wasn't able to trace. 

In practice, after the update to version 8 of fela-dom and fela-react, fela produces an empty 
```html
<style data-fela-type="RULE"></style>
```
instead of one filled with the actual rules, like:
```html
<style data-fela-type="RULE">
.fela__1jwle7b{font-size:20px;color:white;background-color:black;height:9000px;width:100%}
[.....]
</style>
```

Using the following package combination everything works regularly:

| Packages | Version |
| -------- | ------- |
| fela     | 6.1.9   |
| fela-dom   | 7.0.9   |
| fela-monolithic     | 5.0.23   |
| fela-tools     | 5.1.7   |
| react-fela     | 7.3.1   |

From this I can deduce that the issue is either in fela-dom or in react-fela.

This is my fela-renderer setup, which works perfectly with the above listed packages version (I'll skip the imports). As you can see, I am just using fela-monolithic and the selectorPrefix option:
```javascript
export function configureFelaRenderer (options = {}) {
	const plugins = [];
	const keyframePrefixes = [];
	const enhancers = [
		monolithic()
	];
	const mediaQueryOrder = [];
	const supportQueryOrder = [];
	const selectorPrefix = 'fela_';
	
	const defaultOptions = {
		plugins,
		keyframePrefixes,
		enhancers,
		mediaQueryOrder,
		supportQueryOrder,
		selectorPrefix
	};
	
	const mergedOptions = mergeOptions(defaultOptions, options);
	const renderer = createRenderer(mergedOptions);
	return renderer;
}
```

Any ideas on what might be causing this? I looked at the changelog but I saw no recommended changes to the config or the usage of react-fela.

**Comment by rofrischmann** [comment]
Heyhey, thanks for that detailed issue!
Could you please try it without fela-monolithic? Maybe that’s somehow causing the issue as I did not test that one in particular...
Otherwise, it’d be good to just downgrade and stay until we’ve found the issue.
Sorry for th inconvenience and thanks for the kind words at the begining ;)

**Comment by JZBo** [comment]
Hey there, thanks for the quick reply.

I can confirm you that the fault seems to be reside in **fela-monolithic**: Disabling the monolithic enhancer in my config after updating again to the latest v8 version seems to solve the problem.

When the monolithic enhancer is off, the style tag is filled with the fela rules (although, obviously, with non-monolithic class names), and everything works correctly.

**Comment by JZBo** [comment]
I have another minor update to make.

Even disabling fela-monolithic, there's still something off in the behaviour of the latest **fela-dom** and **react-fela** v8 packages in the context of an electron application:

Normal behaviour until this update was for the <style data-fela-type="RULE"> to be filled with the actual rules, whether monolithic or not.

With version 8 of the abovementioned packages, the same style tag in the <head> appears to be empty, but somehow the fela-molothic styles are still processed and understood by the browser, but they are not allowed to be edited.
I sincerely don't know why and what is happening, so I have downgraded for good, but I'll attach a couple of images to explain myself better:

This is what is going on with the v8 version:
![2018-08-22_17-13-25](https://user-images.githubusercontent.com/36004602/44472725-05749400-a62f-11e8-9e8e-f1baee5e38f9.jpg)

And this is the normal behaviour (I kept the monolithic on):
![2018-08-22_17-20-29_1](https://user-images.githubusercontent.com/36004602/44473020-bbd87900-a62f-11e8-9ca1-98616e2dfa4a.jpg)

**Comment by bkniffler** [comment]
There clearly is some problem with fela-monolithic, after doing my annual `yarn upgrade-interactive` routine, fela would break since style tags are empty. Disabling monolithic has fixed the issue.

**Comment by kompot** [comment]
Same here but on another project we use `fela-monolithic` with a pretty similar setup and it works fine.

**Comment by tiagojsalmeida** [comment]
We are running into the same issue.
I've tested this changes locally and they fix the issue. @rofrischmann could we merge and publish a new version?
We need this change ASAP since we are running into some performance issues and upgrading fela would fix it. (so thanks for all the continuous performance upgrades!)
