### ISSUE TITLE
Monolithic prettySelectors

### ISSUE THREAD

**Issue by PepijnSenders** [rofrischmann/fela#602]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 7.0.x   |

-------------------
#### Description
In the latest `react-fela` version the `ruleName` is now prefixed with the `Component` which causes the CSS to break when the `displayName` of the `Component` contains invalid characters. Like `(` or `)`. `fela-monolithic.prettySelectors` uses this `ruleName`.

**Comment by rofrischmann** [comment]
Hey @PepijnSenders,
thanks for reporting that issues. Apparently it's a duplicate of #596 and is fixed with #599. Will close this one =)
