### ISSUE TITLE
Composition and passThroughProps

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#610]
**Type**: Discussion

-------------------
#### Description
In this issue, I'd like to discuss the expected output of several different composition cases.

**This is not about HoC vs. render-props!** With render-props, we do not have passThrough at all as it's on the user's side rather than within the library. This is all about using the `createComponent` API with passThroughProps.

## Example #1 
```javascript
const rule1 = ({ color = 'blue' })=> ({ color })
const rule2 = () => ({ fontSize: 15 })

const Button = createComponent(rule1, 'button', ['data-foo'])
const BigButton = createComponent(rule2, Button, ['data-bar'])

<BigButton color="red" data-foo="bar" data-bar="baz" />
```

#### Would we expect: 
1. `<button data-foo="bar" data-bar="baz" class="a" />` where `.a{color:red}`
2. `<button data-bar="baz" class="a" />` where `.a{color:red}`
3. `<button data-foo="bar" class="a" />` where `.a{color:red}`
4. `<button data-bar="baz" class="a" />` where `.a{color: blue}`

#### Explanation:
1. All props are passed down (if type !== string) and both `data-foo` and `data-bar` are passed to the DOM due to combined passThrough.
2.  Only `data-bar` is passed to the DOM as it overwrites the previously defined passThrough of Button. (Power to the composing source)
3. Only `data-foo` is passed to the DOM as the last passThrough wins and filters out `data-foo`. (Power to the rendering output)
4. Same as 2. but with but in blue as BigButton doesn't explicitly pass down `color`.

**Comment by rofrischmann** [comment]
@TxHawks @tajo Would love to hear your thoughts. More examples coming soon!

**Comment by rofrischmann** [comment]
Also speaking about `createComponentWithProxy`, as soon as we mix both, we can't predictably pass the right props all the time. Check https://github.com/rofrischmann/fela/issues/538 e.g.
We can either stop passing down all props on non-DOM elements to prevent color to be leaked or add additional checks for proxy-components where it ignores composed passThrough that has been passed down. (Both concepts seem to suck)

Another idea: What if we auto-allow all props following the pattern `data-*`, `aria-*` or `onX*` where X is any uppercase letter. Would that kinda solve the reason we use withProxy at all?

**Comment by tajo** [comment]
Interesting. **We just don't have nested `createComponent` in our codebase**. Originally we didn't know it's even possible and then we just thought it's a strange anti-pattern since there are other and better ways how to customize existing components. If I had to pick the behavior, it would be the number one - that seems the most logical implementation.

Also, we don't use createComponentWithProxy and I would rather avoid auto-allowing props like `onX*` since it is a major breaking change at this point and the benefit isn't that big.
