### ISSUE TITLE
Synced package versions

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#612]
**Type**:  Question

-------------------
#### Description
Rather than having independent versioning, we're considering synced package versions.
This would help us to ensure semantic versioning which we theoretically try to do already, but often fails due to massive dependency complexity and unconsidered cases.

Just like Babel, React and any other bigger monorepo, that'd mean every major of any package automatically adds a major release to all packages etc.
This would also help to think twice when introducing major updates, leading to more stable packages.

I'd recommend to do a fresh start with Version 10.0.0 to keep everything in sync.

**Comment by TxHawks** [comment]
👍

**Comment by tajo** [comment]
> but often fails due to massive dependency complexity and unconsidered cases

Do you have some specific examples?

**Comment by rofrischmann** [comment]
e.g. last fela-beautifier update (patch) should have been a major due to changes in fela-dom (major). If people update the patch without having the new fela-dom major its going to break.
But I just can’t keep track of all those micro changes everywhere (even if trying to you might forget while hacking) and there’s no tool that enforces the convention.
Also in general its hard for users to understand which fela version works with which plugin version, fela-dom, react-fela and so on. Even I can’t tell that - I always just rm -rf and fresh install latest version 😅
