### ISSUE TITLE
No typescript typings in latest `react-fela`

### ISSUE THREAD

**Issue by kompot** [rofrischmann/fela#627]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 6.2.3   |
| react-fela | 8.0.3   |

-------------------
#### Description
Looks like `react-fela` typings are nor longer published with latest (8.0.3) package. Before that I had 7.3.1 and typings were there.

![image](https://user-images.githubusercontent.com/231635/47434678-b0c6d400-d7ab-11e8-8d35-37330fbf1ab5.png)

**Comment by rofrischmann** [comment]
Just published new versions fixing that. We forgot to add them to the published files...
