### ISSUE TITLE
[Feature] Explore react hooks for react-fela

### ISSUE THREAD

**Issue by bkniffler** [rofrischmann/fela#629]
Type: *Feature*

#### Description
React hooks is currently in alpha. Its been said clearly that HOCs and enhancers are not what the react team imagines (more on that [here](https://reactjs.org/docs/hooks-intro.html#motivation)) as conceptual best practice to inject logic to components. 

I think hooks would be a nice addition to react-fela, since fela creating CSS classes and returning class names is a great use-case. I'm not sure if this should be introduced as an external library (`react-fela-hooks` or something) due to the alpha stage, or if this could be part of react-fela.

I've been trying to implement an example, but it seems like the new context API has not yet been adopted, thus `useContext` can not be used to access the renderer.

#### Proposal

**Example**:
```jsx
function FelaWithHooks(props) {
  const className = useFela({
    display: 'flex'
  });
  const classNameInner = useFela((theme) => ({
    flex: 1,
    backgroundColor: theme.color
  }));
  return (
    <article className={className}>
      <CustomComponent className={classNameInner}>Hi</CustomComponent>
    </article>
  );
}
```

**Current way**:
```jsx
function FelaWithHooks(props) {
  const style= {
    display: 'flex'
  };
  const rule = theme => ({
    flex: 1,
    backgroundColor: theme.color
  });
  return (
    <FelaComponent style={style} render="article">
      <FelaComponent rule={rule} render={({className}) => <CustomComponent className={className}>Hi</CustomComponent>} />
    </FelaComponent >
  );
}
```

**Comment by TxHawks** [comment]
I'm on board as well.

Render prod were a great intermediary API before hooks existed, but hooks are much nicer.

**Comment by rofrischmann** [comment]
I guess we could replace all APIs with hooks, but I don't want to jump in to fast. Just exploring a useCSS hook is cool and I'm up for it!

**Comment by TxHawks** [comment]
Maybe also a `useFelaTheme` hook? Other than that, I can't imagine needing anything else.

I think we should probably take a very conservative approach to deprecating the existing API, but do it over several major releases, and at the same time, make sure tree shaking works well (it may already work well, I didn't check), so that users only import the code they actually use.

**Comment by rofrischmann** [comment]
Alright, now that we have React 16 support, I hacked a bit on hooks and it took me 10 mins to get them work - dang I love it.

I got two different APIs for you, please tell me the prefered one.
```javascript
const Test = () => {
  const theme = useTheme()
  const css = useFela()

  return (
    <div className={css({ color: theme.primary, fontSize: 40 })}>Hello</div>
  )
}
```
vs.
```javascript
const Test = () => {
  const { css, theme } = useFela()

  return (
    <div className={css({ color: theme.primary, fontSize: 40 })}>Hello</div>
  )
}
```

I personally prefer the second one :P 
In both ways, css has the following signature `(...obj) => className` so we can use that to compose styles by passing a second obj e.g. (awesome for extending apis)

**Comment by TxHawks** [comment]
I prefer the second one as well. Don't see much point in having two separate hooks. 

However, I think there is one pretty common use case that isn't addressed by the current API. In larger components, when the style rule gets more complex than just a few properties, I often extract it to an external function, mostly for readability.

That's why we pass non fela-related props to the `style` function in `FelaComponent`.

I'd suggest keeping the current api, but overload `css`, so that it can also take a function of `theme`, and an object that was passed to `useFela`:

```js
const testStyle = ({ theme, myProp, }) => ({
  color: myProp ? theme.primary : 'pink',
})
const Test = ({myProp,}) => {
  const { css, theme, } = useFela({ myProp, })

  return (
    <div className={css(testStyle)}>
      <strong className={css({ fontWeight: 700, })}>Hello</strong> world
    </div>
  )
}
```

Aside from subjectively offering better readability, I think the bigger win of such an api would extendability, since we could do something like this, and the consumer will have access to both `theme` and `props`, or even `state`:

```tsx
type Props = {
  myProp: boolean,
  extend: ?Object | ({theme, myProp}: {theme: Object, myProp: string}) => Object,
};
const Test = ({myProp, extend}: Props): React.Node => {
  const { css, theme, } = useFela({ myProp, })

  return (
    <div className={css(testStyle, extend)}>Hello</div>
  )
}
```

**Comment by sgrishchenko** [comment]
I think it good solution. And i can use this approach for multi-rules too.
```ts
type Rule<T> =  ?Object | (props: T & {theme: Object}) => Object 

type Props = {
  myProp: boolean,
  extend: {
    root: Rule<{myProp: boolean}>,
    small: Rule<{myProp: boolean}>,
    big: Rule<{myProp: boolean}>,
  },
};

const containerStyle = ({myProp, theme}: {myProp: boolean, theme: Object}) => {
  const commonStyle = { display: 'flex'}
  return {
    root: {
      ...commonStyle
    },
    small: {
      ...commonStyle,
      flexBasis: '30%',
      backgroundColor: theme.primary
    },
    big: {
      ...commonStyle,
      flexBasis: '70%',
      backgroundColor: theme.secondary
    },
  }
}

const Container = ({myProp, extend}: Props): React.Node => {
  const { css, theme, } = useFela({ myProp, })
  const styles = containerStyle({ myProp, theme })

  return (
    <div className={css(styles.root, extend.root)}>
      <div className={css(styles.small, extend.small)}>
        Small Content
      </div>
      <div className={css(styles.big, extend.big)}>
        Big Content
      </div>
    <div>
  )
}
```

**Comment by sgrishchenko** [comment]
How about exporting the renderer? So that the user has the opportunity to draw a keyfram or something like that.
```
const { css, theme, renderer, } = useFela({ myProp, })
```

**Comment by brianespinosa** [comment]
@rofrischmann I prefer the second as well.

@TxHawks brings up some good points regarding extendability, which will be important using Fela in a large UI library.

**Comment by bkniffler** [comment]
Thanks for implementing this. Just a quick question: does it also work that way with react-native renderer?

```
function Component() {
  const { css } = useFela();
  return <View style={css({ backgroundColor: "red" })} />
}
```

**Comment by rofrischmann** [comment]
Oh, hmm it should yeah. But the naming definitely lacks here 😅
