### ISSUE TITLE
Migration to New React Сontext

### ISSUE THREAD

**Issue by sgrishchenko** [rofrischmann/fela#630]
**Type**: Question

| Packages | Version |
| -------- | ------- |
| fela     | 6.0.x   |

-------------------
#### Description
In React 16.6.0 Legacy Context deprecated. Therefore, it is necessary to migrate to New Context API. There is a problem: Preact and Inferno still do not support New Context API. I see 3 solutions:
1. Use peerDependency for [preact-context](https://github.com/valotas/preact-context) and [create-inferno-context](https://github.com/kurdin/create-inferno-context) polyfills.
1. Use _fela-bindings_ only for Preact and Inferno and separate code for React.
1. Completely stop supporting Preact and Inferno. (Subjectively, it seems to me that Fela did not become popular among the users of these libraries).

Of course, I am ready to make a pull request for each of the proposed ways to solve the problem.

**Comment by rofrischmann** [comment]
I guess the cleanest way would be to pass createContext to the bindings factory, so we can use preact-context etc. without adding any additional code to the react version.
I'd love to see that happening if you're open to send an PR (was planning to do it as soon as I got a new stable API ready, but doing it now would be way better actually).

I don't want to split the bindings or drop Preact and Inferno though. I know some ppl using those bindings in bigger projects and don't want to drop that.
