### ISSUE TITLE
Allow first param of createComponent(WithProxy) to be optional css rule object

### ISSUE THREAD

**Issue by rapheld** [rofrischmann/fela#649]
**Type**: Feature

| Packages | Version |
| -------- | ------- |
| fela     | 6.x   |

-------------------
#### Description
I often have static css rules. In these cases, it would be nice to pass in an object to `createComponent` and `createComponentWithProxy` instead of being required to wrap it in a function.

#### Proposal
 I would like to see `createComponent` and `createComponentWithProxy` changed to accept either an object or function as their first parameter. The other params would not change.

**Code Example**:
Current function-only param
```js
createComponent(() => ({
  some: 'rule',
  another: 'rule'
}));
```
Proposed optional object param
```js
createComponent({ some: 'rule', another: 'rule' });
```

**Comment by rofrischmann** [comment]
You're using version 6 right? The newly released Fela 10+ already supports plain object usage :P 
I'll add a test later to show that. For now I'll close this issue.

**Comment by rapheld** [comment]
Well..exellenct! ;)
