### ISSUE TITLE
Silent errors kill styles when styling pseudo elements 

### ISSUE THREAD

**Issue by MattCrouch** [rofrischmann/fela#659]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela         | 10.1.1   |
| fela-dom    | 10.1.1   |
| react-fela   | 10.1.1   |

-------------------
#### Description
While upgrading our Fela packages to the latest versions, we discovered some styling was not being applied.

It appears that when trying to add styles to a pseudo element that the browser does not understand, it then stops any other styles from being added to the page from that point. 

#### Steps to reproduce
```jsx
const CustomProgress = createComponent(
  {
    "::-moz-progress-bar": {
      backgroundColor: "red"
    }
  },
  "progress"
);
const OtherComponent = createComponent({ fontWeight: "bold" }, "div");
```

```jsx
class App extends Component {
  render() {
    return (
      <RendererProvider renderer={renderer}>
        <div>
          <CustomProgress />
          <OtherComponent>Other Component</OtherComponent>
        </div>
      </RendererProvider>
    );
  }
}
```
[Example repository](https://github.com/MattCrouch/fela-pseudo-element-bug)

#### Expected Behavior
Text within `<OtherComponent>` to be bold in all browsers.

#### Actual Behavior
Text within `<OtherComponent>` is not bold in any other browser other than Firefox.

**Comment by rofrischmann** [comment]
Oh, that's an interesting case indeed! We try-catch the insertRule calls as the browser would throw otherwise, but it feels odd that it doesn't render the next styles anymore...

**Comment by rofrischmann** [comment]
Oh you're right! Didn't think about that one. We should reset that index to the previous value if the try catch fails. (or only actually set it after the insertRule call to make sure it works).
Would you like to send a PR? I can help out if there's any question - that way it'll be fixed and published way sooner as I don't have that much time atm.
