### ISSUE TITLE
Angular 2 - Docs + Examples

### ISSUE THREAD

**Issue by clouless** [rofrischmann/fela#66]
#### Description

I really like your library and would like to contribute Angular 2 usage Docs and source-code examples.

So my questions:
 * Do you want me to wait until Angular 2 is fully released or is it fine doing it with a release candidate?
 * Is it sufficient to provide examples for JavaScript or do you also want examples for DART and Typescript? (Angular2 comes in three flavors)

I would provide you a pull request as soon as I am done. I would try to do a similar app like the current react example and provide a similar doc.

Do you have any other hints or wishes?

cheers,
Bernhard

**Comment by rofrischmann** [comment]
Oh that would actually be really awesome!

I am not quite into Angular, but I guess Angular 2 is already used a lot right? Also if its already a RC I guess we are fine to just use that one. Should not change much right? 
I would really love to see a TypeScript example if possible, but yet of course it is up to you. All 3 would be best, if 2 I would go with TypeScript, but it's also fine to just have the basic JS examples.

I am really looking forward to see your PR soon :)

**Comment by clouless** [comment]
Ok nice :). 
I just finished diving into a real live example with a tiny react application
and I might need to write some helper or think of something like this `mapStylesToProps` thing and what the corresponding thing in Angular 2 would be.

It will take me sometime but I will provide it :)

Since in my company we are sometimes forced by the customer to use Angular 2 instead of React I want to have at least the styling independent :)

**Comment by clouless** [comment]
@rofrischmann ok it seems the first basic thing we need to do is add some TypeScript typings to fela. 
Here you can see a very basic definition that seems to be enough to satisfy the typescript compiler:

https://github.com/rofrischmann/fela/compare/master...clouless:master

The question is: Is this the right place where I put it? Or are these `packages/` folders somehow autogenerated by a build-chain.
And is `packages/fela` the main package and contains everything? (So in the angular2-demo I will only `npm install --save fela` and use that)

I will experiment around a little more and see if we need any more typings.

**Comment by clouless** [comment]
@rofrischmann I am done for now. Typescript and ES6 Examples + Documentation is done.
We just need to clarify the stuff above :)

**Comment by clouless** [comment]
## FYI: Angular 2 Dart - Work in Progress

  * Example Angular2 Dart
  * UsageGuide

[fela-angular2-dart.zip](https://github.com/rofrischmann/fela/files/380253/fela-angular2-dart.zip)

**Comment by rofrischmann** [comment]
With the release of 1.2 we should be able to use Fela with Angular. I will close this issue for now, as the Dart example does not seem to be fixed too soon. I will yet try to bring some details back into the documentation, but I had to strip it off to be conform to the React/Inferno docs which only cover React/Inferno specific stuff but do not cover Fela configs at all (which was part of the Angular docs as well).
