### ISSUE TITLE
`devMode` is broken with multiple renderers

### ISSUE THREAD

**Issue by layershifter** [rofrischmann/fela#664]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| `fela`     | 10.1.3   |
| `react-fela`     | 10.1.3   |

-------------------
#### Description
`devMode` option breaks multiple renderers.

#### Steps to reproduce
One example is worth a thousand words 😸 
https://codesandbox.io/s/711kjkr1o6

#### Expected Behavior
Everything works.

#### Current Behavior
Styles are applied only for second header.

**Comment by layershifter** [comment]
Actually, the issue is caused by [`insertRuleInDevMode.js`](https://github.com/rofrischmann/fela/blob/master/packages/fela-dom/src/dom/connection/insertRuleInDevMode.js) which simply rewrites all styles in `devMode` ✍️

**Comment by rofrischmann** [comment]
First of all, I would consider having 2 renderers a code smell though. You should always have only one renderer.
But, yet you're right. No idea how to fix that tbh. It gets super complicated with sorting and specificity and adding dom nodes etc.

**Comment by rofrischmann** [comment]
Might allow a second argument to `render` (fela-dom) that sets some kind of "id" for style nodes but defaults to none. That way I'd allow those changes to happen.

**Comment by layershifter** [comment]
But it means that:
- we should add this `id` prop to `RendererProvider` to pass it to `render()`
- we should pass it to `createSubscription()` from `render()`
- and finally to `getNodeFromCache()`
- use optional `data-fela-id` attr or append `data-fela-type` (???)

However, we're passing `renderer` in all these cases 🤔 If you're fine with these I will create another PR for this

**Comment by rofrischmann** [comment]
Im also happy with a renderer option, so we dont change public APIs except the config and keep it a single source.
Then all happens within fela-dom entirely. I'd also want to see a data-fela-id here. Extending the type seems to require parsing that argument later on etc. Better to have a nice clean way.
Make sure to also add it to the server-side rendering methods and rehydration =)

But I'd really love to see that PR and test it!

**Comment by layershifter** [comment]
@rofrischmann ready for review in #664 🎉
