### ISSUE TITLE
How to properly handle specificity?

### ISSUE THREAD

**Issue by milesj** [rofrischmann/fela#666]
**Type**: Question

| Packages | Version |
| -------- | ------- |
| fela     | 10.0.3   |

-------------------
#### Description

**Preface:** I'm using Aesthetic v3 + Fela adapter, which transforms styles to classes using this method: https://github.com/milesj/aesthetic/blob/master/packages/adapter-fela/src/FelaAesthetic.ts#L43

According to the docs, `combineRules` should be used to avoid specificity order problems (which Aesthetic is using). However, this doesn't always seem to be the case. I've been running into issues where buttons are missing their background because of a `background: transparent` style being generated. Here's a screenshot.

<img width="1049" alt="screen shot 2019-01-28 at 11 15 07 am" src="https://user-images.githubusercontent.com/143744/51860604-0d77e480-22ef-11e9-8b55-8024166b6b25.png">

And another screenshot with the background intact. 

<img width="1064" alt="screen shot 2019-01-28 at 11 15 56 am" src="https://user-images.githubusercontent.com/143744/51860622-1668b600-22ef-11e9-84a7-fdda5f121564.png">

This obviously happens depending on the order of which components are rendered (and styles generated) in, and this order changes between usage. 

Haven't been able to lock this down entirely and will most likely have to use a different approach.

#### Steps to reproduce

N/A

#### Expected Behavior
```javascript
// your code here
```

#### Actual Behavior
```javascript
// your code here
```

**Comment by milesj** [comment]
@rofrischmann Here's the snippet of button styles.

```
button: {
      ...pattern.resetButton,
      ...transition.box,
      fontWeight: font.weights.bold,
      position: 'relative',
      color: color.primary,
      backgroundColor: color.core.hylian[3],
      border: `2px solid ${color.core.hylian[3]}`,
      borderRadius: ui.borderRadius,
      textAlign: 'center',

      '@selectors': {
        // Removes weird bonus padding from button in Firefox
        '::-moz-focus-inner': {
          border: 0,
          padding: 0,
          margin: 0,
        },

        // Only show hover states on non-disabled
        ':not([disabled]):hover': {
          backgroundColor: color.core.hylian[4],
          borderColor: color.core.hylian[4],
        },
      },
    },
```

And `pattern.resetButton` is this object. This is where I think the transparent styles are coming from.

```
{
  appearance: 'none',
  background: 'transparent',
  cursor: 'pointer',
  margin: 0,
  padding: 0,
  border: 0,
  userSelect: 'auto',
  textDecoration: 'none',
  fontSize: 'inherit',
  verticalAlign: 'middle',
  display: 'inline-block',
}
```

As for the important, we're using the fela important plugin because we have styles on our page that aren't CSS-in-JS and we need to avoid collisions.

**Comment by rofrischmann** [comment]
Alright. So right now, you can't mix `background` and `backgroundColor` (or in general, any shorthand and longhand values together) because Fela can't assure the correct order as of today. We only sort pseudo classes right now though this might change soon. The ideal goal is to sort all rules in alphabetic order, but I'm yet not sure about the performance implications.

**Comment by milesj** [comment]
Thanks for the info. I'll mess around with using the full form and see if that resolves the issue.
