### ISSUE TITLE
React warnings about key prop using fe

### ISSUE THREAD

**Issue by MarcNq** [rofrischmann/fela#668]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela-bindings     | 10.1.3   |

-------------------
#### Description
When using `/* @jsx fe */`, arrays of components with styles give React warnings about missing `key` prop, even if prop is passed.

This is because `key` prop gets transferred to FelaComponent's children, while React needs `key` prop at the outermost component in a loop/array: https://reactjs.org/docs/lists-and-keys.html#extracting-components-with-keys

#### Steps to reproduce

1. Add fe

```javascript
/* @jsx fe */
import { fe } from "react-fela";
```
2. Render an array of components with css and key props
```javascript
const movies = ["Inception", "Avatar", "The Return of the King", "The Matrix"];

const Example = () => (
  <ul>
    {movies.map(movie => (
      <li key={movie} css={{ color: "darkGrey" }}>
        {movie}
      </li>
    ))}
  </ul>
);
```

#### Expected Behavior
No React warnings

#### Actual Behavior
Some React warnings

**Comment by rofrischmann** [comment]
Addressed in the latest commit :)
