### ISSUE TITLE
codemod breakes when render is a non-function variable

### ISSUE THREAD

**Issue by TawKhoury** [rofrischmann/fela#672]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela-codemods  | 10.2.0   |

-------------------
#### Description
When the `render` prop is a variable that stores a `string`, for instance, when the rendered element is set dynamically, the codemod assumes it is a function, removes all children and places the variable as `children`.

#### Steps to reproduce
The following code:

```jsx
const Example = ({ as, children, })  => (
  <FelaComponent style={...} render={as}>
    {children}
  </FelaComponent>
);
```
is transformed into:

```jsx
const Example = ({ as, children, })  => (
  <FelaComponent style={...}>
    {as}
  </FelaComponent>
);
```

#### Expected Behavior

When `FelaComponent` is *NOT* a self-closing JSX element, and does not have a `children` prop set explicitly, `render` should be transformed into `as`, and it's children.

```jsx
<FelaComponent style={...} render={as}>{children}</FelaComponent>
// Should be transformed to 
//    <FelaComponent style={...} as={as}>{children}</FelaComponent>

<FelaComponent style={...} render={as} children={children} />
// Should be transformed to 
//    <FelaComponent style={...} as={as} children={children} />

<FelaComponent style={...} render={as} />
// Should be transformed to 
//     <FelaComponent style={...}>{as}</FelaComponent>
```

**Comment by TawKhoury** [comment]
Another bug in the codemod is that arguments of inline functions inside a `style` functions are transformed as if they were the args of the `style` function itself.

**Before:**  
```jsx
<FelaComponent style={theme => ({ 
  color: (a, b) => a + b, 
})} />
```

**After:**  
```jsx
<FelaComponent style={theme => ({ 
  color: ({ a }) => a + b,  // <- This is the problem
})} />
```

Should I keep this here, or open a separate issue?

**Comment by rofrischmann** [comment]
Hmm, The second one is invalid anyway as you can't have function values inside Fela rules.
I don't think we should check that as well.
However, the first one is definitely true and should be fixed. Feel free to send a PR that fixes that specific case!

**Comment by TxHawks** [comment]
@rofrischmann The second case could be a valid use case with a slightly less contrived example, in which you use a function that takes a callback to generate some styles:

```jsx
<FelaComponent style={({ theme, someProp}) => ({
  ...myFn((someProp) => `do something with ${someProp }'),
})} />
```

I think that generally speaking, we should only check for the arguments of the callback directly following `style={`.

I agree that the first issue is more serious
