### ISSUE TITLE
Type definitions for react-fela

### ISSUE THREAD

**Issue by marcneander** [rofrischmann/fela#676]
Type definitions for `react-fela` is completely broken and should probably be removed or fixed. 

Unfortunately I don't have enough experience with Typescript yet to fix this myself.

**Comment by tomwagner** [comment]
Maybe it's related with #677. From my point of view in my usage the TS typings looks good. Try to be more specific.

**Comment by marcneander** [comment]
I'm on my phone right now but here's a small list from the top of my head.

- useFela hook is not defined
- createComponent with ':hover' and other psuedo classes not compatible if not first argument is a function.
- createComponent with another component in second argument seems to be completely missing.

Probably more...

**Comment by reinhard** [comment]
I would not call the typescript support of Fela 'completelty broken' either. createComponent should not be used any longer (AFAIU it will or already is deprectated).

For useFela I created a pull request at #683 

Also see https://github.com/Indoqa/indoqa-react/blob/feature/theming-v2/packages/style-system-demo/src/main/fela/FelaComponentSamples.tsx and https://github.com/Indoqa/indoqa-react/blob/feature/theming-v2/packages/style-system-demo/src/main/fela/FelaHookSamples.tsx (FelaHookSamples require https://github.com/rofrischmann/fela/pull/683 to be merged into Fela though)

**Comment by rofrischmann** [comment]
Anything else to add here? I only accept PRs for TypeScript stuff, will never fix that on my own :P

**Comment by reinhard** [comment]
Nothing from me.

**Comment by marcneander** [comment]
@reinhard Your PR from yesterday is incorrect and does not let typescript users add arguments to useFela`. This is why this issue is here. We don't have `ThemeContext` definitions either.

I see two solutions:
- Test the type definitions here in the fela monorepo.
- Move definitions to https://github.com/DefinitelyTyped and let the community handle it.

Overriding type definitions from the installed package itself is messy, especially with `CRA --typescript`. I would love to see solution nr 2.

**Comment by TxHawks** [comment]
+1 for DefinitelyTyped. Since we don't really maintain the TS definitions, I see no added value in maintaining them here

**Comment by rofrischmann** [comment]
@marcneander Feel free to organize the migration to DefinitelyTyped. I would love to see that being improved in the future!

**Comment by marcneander** [comment]
I'd love to but I already have too much on my table right now. If this is still an issue after summer I'll make the effort 👍

**Comment by UberMouse** [comment]
I've created a PR to fix the specific issue introduced in #677 in #692

**Comment by rofrischmann** [comment]
So ill close this issue now. If there're still any issues, feel free to reopen or open a new one.
