### ISSUE TITLE
fela-native

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#68]
To be able to use Fela with React Native we need to improve the infrastructure.

- [x] **Native Renderer**
   - [x] Leverage React Native's StyleSheet.create for caching to reduce JS object bridging which is inperformant ( rofrischmann/react-look#273 )
- [x] Utilize shared Renderer methods
   - [x] `generatePropsReference(props)`
   - [x] `processStyle(style, meta, plugins)`
   - [x] `diffStyle(style, base)`
- [x] React Native example
- [x] Documentation

**Comment by dizlexik** [comment]
Is this usable right now? I know there's no documentation, and I don't expect you to write any here, but I'd be happy to dig around through the code a little and start using this if you can tell me whether or not it'll work. Thanks!

**Comment by rofrischmann** [comment]
Theoretically it should work right now as it actually outputs real style objects, but I never tested it yet. Be sure to give some feedback if you're going to try it out :)

**Comment by rofrischmann** [comment]
@dizlexik I updated the react-native renderer. It now is working fine (see the example), but I want to publish the docs before upgrading the npm version, so please be patient for some more hours :P

**Comment by dizlexik** [comment]
That's awesome, thanks so much for the example! I can't wait to try it out. I'll definitely keep you posted with any feedback I can provide. I won't have a chance to try it out until Monday so it would be really cool if you could find time to publish it before then :)  Thanks again!

**Comment by cpeddecord** [comment]
Awesome!
