### ISSUE TITLE
New option to isolate.

### ISSUE THREAD

**Issue by houd1ni** [rofrischmann/fela#688]
The isolate plugin: https://github.com/rofrischmann/fela/tree/master/packages/fela-plugin-isolation

I suggest to add an option or another plugin that adds some tunable prefix to fela's class names instead of adding the whole rule for each of them. E.g. 'f-a f-b f-ae' instead of making 3 copies of `all:initial`. That seems to be quite less code. I also can make a PR after negotiation.

**Comment by rofrischmann** [comment]
Could you gimme a quick example of how the rendered CSS and class names would look like and how you'd want to implement that?

**Comment by houd1ni** [comment]
Sure. First, it should be an option, 'cause it does not drop all previous styles, but only avoids class names collisions, that is often very close to the plugin target.

For example, one has picked `fela-` as a prefix.

### Input
```javascript
{
  color: 'green',
  fontWeight: 'bold'
}
```

### Classnames, renderRule() output:
```
fela-a fela-b
```

### Rendered CSS (beauty):
```css
.fela-a {
  color: 'green';
}
.fela-b {
  fontWeight: 'bold';
}
```

**Comment by TxHawks** [comment]
If I understand you correctly, Fela has this functionality out of the box, no plugin needed. Just pass a `selectorPrefix` to your renderer:

```js
import { createRenderer } from 'fela';

const renderer = createRenderer({ selectorPrefix: 'fela-', });
```

See https://fela.js.org/docs/advanced/RendererConfiguration.html

**Comment by houd1ni** [comment]
@TxHawks  Thank you! Yes, it's exactly what I thought of.

So, if one has some classnames inference, maybe, he should pick this plugin occasionally instead of solving it by `selectorPrefix`. How about a line in this README warning about it?

**Comment by TxHawks** [comment]
I don't think I understand what the need for a plugin is here. I wouldn't mind a note in the README, though it is pretty clearly documented in the link I sent above.

**Comment by houd1ni** [comment]
@TxHawks Clearly indeed. The case I'm asking, that fela could be easily used without remembering all these options, and one could easily face the problem of class collision and resolve it by the plugin instead of looking for the right solution for him/her. Sometimes it leads to stupid mistakes ;)

**Comment by TxHawks** [comment]
Sure, send a PR.

Though to be fair, a plugin wouldn't help here. You either need to check the documentation of the renderer, or the list of plugins. I'd assume, and I may be wrong, that you someone setting up Fela for a project, is likely, and should be expected to , look at the renderer's API. Seems much more basic than starting off with looking at plugins that are meant to extend the basic usage

**Comment by TxHawks** [comment]
Did you have two renderers? What sort of class name collisions did you run into?

**Comment by houd1ni** [comment]
Not at all: having two renderers looks like madness 😆 

I thought about possible collisions in my project due to third-side UI frameworks and so and how to solve them. One of the first was like if I have kinda small 2-3 letter class names somewhere in the large codebase, no matter inside or out of fela-styled components, hence it could be inference where some special salt should be useful after all.
