### ISSUE TITLE
Consideration: How to style child elements?

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#69]
As https://medium.com/@taion/the-problem-with-css-in-js-circa-mid-2016-14060e69bf68#.wv57un3dw describes there are several problems with **not** using selectors sometimes.
Actually we could solve this using Fela's props or using sth. like `:nth-child`, but we might want to consider adding a special plugin or some default functionality to style child elements e.g. `.btn > .child` as well as `.btn .child`.

Perhaps its enough to allow the `>` selector or use an explicit `&` before adding selectors.

```javascript
const rule = props => ({
  color: 'blue',
  ':hover': {
    color: 'red'
  }
  '& > button': {
    color: 'red',
    ':last-child': {
      paddingRight: 10
    }
  }
})
```

**Comment by hssrrw** [comment]
Does it work? I try to
```js
renderer.renderRule(
  () => ({
    backgroundColor: '#000',
    '> div': {
      backgroundColor: '#00f',
    }
  })
)
```
Appears not working :(

**Comment by rofrischmann** [comment]
This was removed with the latest release do to specificity issues, but I found a way to do it without problems. coming with 4.1.1

**Comment by hssrrw** [comment]
@rofrischmann such great news! Not being able to stylize children is a huge drawback even though with react components it's needed not very often. Thanks for your amazing job

**Comment by rofrischmann** [comment]
Yeah. Wanted to note the same: It's still considered an anti-pattern (well who cares about anti-patterns). But you simply don't need the child selector with React. It's only useful if you add a third-party component and need to style it's elements.
Btw. release is out in 5min :P
