### ISSUE TITLE
FelaRenderer typing does not resolve React.ComponentType

### ISSUE THREAD

**Issue by jp7837** [rofrischmann/fela#694]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| react-fela     | 10.2.2   |

-------------------
#### Description
When using react-fela typings alongside React typings from DefinitelyTyped (@types/react) v16.8.4, I'm getting the following error where FelaRenderer extends React.ComponentType

`Property 'ComponentType' does not exist on type 'typeof React'.ts(2339)`

#### Steps to reproduce

1. Compile TypeScript with the following typings
`react-fela@10.2.2`
`@types/react@16.8.4`

#### Expected Behavior
Code should compile successfully

#### Actual Behavior
`react-fela\10.2.2\node_modules\react-fela\index.d.ts(568,45): error TS2339: Build:Property 'ComponentType' does not exist on type 'typeof import("@types/react/16.8.4/node_modules/@types/react/index.d.ts")'`

**Comment by jp7837** [comment]
@tomwagner this was added in #677, were you building alongside React typings from DefinitelyTyped?

**Comment by tomwagner** [comment]
My fault :( Should be fixed in #692
