### ISSUE TITLE
Add withFela HoC

### ISSUE THREAD

**Issue by josemussa** [rofrischmann/fela#708]
**Type**:  Feature

| Packages | Version |
| -------- | ------- |
| fela     | 10   |

-------------------
#### Description
I'm loving the `useFela` hook, would you accept a pull request for a `withFela` HoC that piggybacks on `useFela` hook? The use-case for this is that hooks are great but not useful for class components.

The code would look similar to this:
```js
import React from 'react'
import useFela from './useFela'

const withFela = Component => {
  return props => {
    const fela = useFela(props)
    return <Component {...props} {...fela} />
  }
}

export default withFela
```

And you can consume it as:
```js
function Button(props) {
  const { css, theme } = props;

  return (
    <div className={css({ color: theme.primary })}>{theme.primary}</div>
  )
}

const ButtonWithFela = withFela(Button);
```

I'd be happy to contribute with this

**Comment by TxHawks** [comment]
Why not just create it in userland? I mean, what's thebenefit of having this backed in to the API vs just creating your own hoc that does exactly that?
