### ISSUE TITLE
Unexpected behavior during rendering if dynamic rule do not have default value

### ISSUE THREAD

**Issue by hufeihxw** [rofrischmann/fela#79]
**Version**: 1.1.0
**Environment**: DOM & Server, React-fela
**Type**: General

-------------------
#### Description

It seems dynamic rule functions must be able deal with empty props themselves

If you define a rule which requires some value in props, like this:

    const example = ({colorName}) =>{
      background: colorName.toUppercase()
    }
    //I use react-fela, so there's a mapStylesToProps method
    const mapStylesToProps = props => renderer => ({
      menuPanel: renderer.renderRule(example, {colorName: props.colorName || 'red'}),
    })
You wouldn't expect colorName to be undefined in the rule 'example', but it actually happens

I found its here in the code:
https://github.com/rofrischmann/fela/blob/master/modules/createRenderer.js#L49

I didn't really looked into the code, but I believe there're reasons for the renderer to cache a static base style for dynamic rules, and I should put the calculation into the mapStylesToProps function or set default values for my props.

 It's just some documents in obvious places could have made my life easier

like here:

[Rules](http://fela.js.org/docs/basics/Rules.html), just add one to describe this kind of behavior

    To keep your selectors pure you should not:
    - Mutate the props
    - Perform side effects e.g. API calls
    - Call non-pure functions e.g. Date.now()
    - Ignore default values for your props (... more explanations)

[React example](http://fela.js.org/docs/guides/UsageWithReact.html), codes here actually do calculation in mapStylesToProps function, a line of comments would be good for readers:

    const title = props => ({
      lineHeight: 1.2,
      fontSize: props.fontSize,
      color: props.color
    })

    // We use both the components props and
    // the renderer to compose our classNames
    // Do your calculation here instead of in your rule, props sent to rule could be empty for performance reasons
    const mapStylesToProps = props => renderer => ({
      container: renderer.renderRule(container),
      title: renderer.renderRule(title, {
        fontSize: props.size + 'px',
        color: props.color
      })
    })

**Comment by rofrischmann** [comment]
Hey @hufeihxw,
thanks for creating the issue. Indeed it does the static rendering to diff styles later on. Props should not have nested attributes as they then evaluate to undefined and throw. I might add this to the docs, but I can't think of a "fine" solution yet.

Will close the issue for now, but might reopen later.
