### ISSUE TITLE
fela-preset-dev module published to npm as fela-preset-web

### ISSUE THREAD

**Issue by miketrexler** [rofrischmann/fela#87]
I believe the incorrect module has been published to npm for 'fela-preset-web'.

It looks like the 'fela-preset-dev' module has been published in its place:
https://www.npmjs.com/package/fela-preset-web

**Comment by rofrischmann** [comment]
Oh lol :D thanks for mentioning, I'll update later today!

**Comment by rofrischmann** [comment]
fixed
