### ISSUE TITLE
Test Examples - (Complexities in testing leads to abandoning great idea)

### ISSUE THREAD

**Issue by DavideDaniel** [rofrischmann/fela#94]
**Version**: 3.0.x
**Environment**: Test
**Type**:  Docs / General

---
#### Description

Love the implementation. Chose to go with Fela but complexities in testing created push back to abandon it. Examples of testing would be an immense boon at the very least. Without that, it's been hard to have team buy-in to use Fela.

**Comment by rofrischmann** [comment]
Hey @DavideDaniel,

Sounds great. I am more than happy to add some information on testing. What exactly do you want to test? I've never tested any Fela specific code in my applications yet.
