### ISSUE TITLE
[react-fela] Add support for react inspector 

### ISSUE THREAD

**Issue by maxharris9** [rofrischmann/fela#99]
#### Proposal

Ensure that the component name passes through so as to be visible in the react inspector.

Currently many of the components styled with Fela show up as `<component>`, which is a small step backwards. To reiterate, it would be nice to see

``` javascript
const Drawer = props => (
  <div>drawer here</div>
)
```

show up in the react inspector as `<Drawer>...</Drawer>`

<img width="1352" alt="screen-shot-2016-10-23-at-4 10 27-pm" src="https://cloud.githubusercontent.com/assets/3769985/19703793/0085c22a-9aba-11e6-83aa-1b38ec90267b.png">

**Comment by rofrischmann** [comment]
Thanks for filling the issue. Right now I do not have the time to do this actually, but we will have to use a Babel plugin to enable this. Similar to the following: https://github.com/vdanchenkov/babel-plugin-styled-components-named

**Comment by rofrischmann** [comment]
This will be coming soon. I already prepared the API to allow the transformation.
